import type { Island } from '@/types'

export const island_1_1: Island = {
  id: '1.1',
  moduleId: 1,
  title: 'Common Threats',
  titleRu: 'Распространённые угрозы',
  objective: 'Explain the threats, vulnerabilities, and attacks that occur in the various threat domains.',
  icon: 'ShieldAlert',
  lessons: [
    {
      id: '1.1.1', title: 'Threat Domains', titleRu: 'Домены угроз', kind: 'flip',
      blocks: [
        { t: 'def', term: 'Threat domain', md: 'An area of control, authority, or protection that attackers can exploit to gain access to a system.' },
        { t: 'p', md: 'Организации сталкиваются с растущим числом киберугроз, поэтому им нужны сильные решения по безопасности. Но сначала надо понять, **какие уязвимости существуют внутри их доменов угроз**.' },
        {
          t: 'flip', title: 'Как атакующие эксплуатируют системы внутри домена',
          cards: [
            { front: 'Physical access', back: 'Прямой физический доступ к системам и сетям.' },
            { front: 'Wireless networking', back: 'Беспроводная сеть, которая выходит за границы организации.' },
            { front: 'Bluetooth / NFC', back: 'Устройства Bluetooth или near-field communication (NFC).' },
            { front: 'Malicious email attachments', back: 'Вредоносные вложения в письмах.' },
            { front: 'Supply chain', back: 'Менее защищённые элементы в цепочке поставок организации.' },
            { front: 'Social media accounts', back: 'Аккаунты организации в социальных сетях.' },
            { front: 'Removable media', back: 'Съёмные носители, например флешки.' },
            { front: 'Cloud-based applications', back: 'Облачные приложения.' },
          ],
        },
      ],
    },
    {
      id: '1.1.2', title: 'Types of Cyber Threats', titleRu: 'Типы киберугроз', kind: 'accordion',
      blocks: [
        { t: 'p', md: 'Киберугрозы классифицируют по категориям, чтобы организация могла оценить, **насколько вероятна** угроза, понять её **денежное влияние** (monetary impact) и на основе этого **расставить приоритеты** в защите.' },
        {
          t: 'accordion', title: '8 категорий и примеры',
          items: [
            { title: 'Software attacks', md: 'A successful denial-of-service (DoS) attack; a computer virus.' },
            { title: 'Software errors', md: 'A software bug; an application going offline; a cross-site script or illegal file server share.' },
            { title: 'Sabotage', md: 'An authorized user penetrating and compromising the organization’s primary database; defacement of the organization’s website.' },
            { title: 'Human error', md: 'Inadvertent data entry errors; a firewall misconfiguration.' },
            { title: 'Theft', md: 'Laptops or equipment stolen from an unlocked room.' },
            { title: 'Hardware failures', md: 'Hard drive crashes.' },
            { title: 'Utility interruption', md: 'Electrical power outages; water damage from sprinkler failure.' },
            { title: 'Natural disasters', md: 'Severe storms (hurricanes, tornados); earthquakes; floods; fires.' },
          ],
        },
        { t: 'note', variant: 'exam', md: '**Sabotage** совершает **авторизованный** пользователь, а **software attacks** это классическая семья malware и DoS. **Human error** это случайность, **sabotage** это умысел.' },
      ],
    },
    {
      id: '1.1.3', title: 'Avatar note', titleRu: 'Заметка курса', kind: 'text',
      blocks: [
        { t: 'note', variant: 'avatar', md: 'У киберпреступников огромный и постоянно развивающийся арсенал. Они часто **комбинируют две и более тактики**, чтобы повысить шансы на успех. Задача специалистов по кибербезопасности — **повышать осведомлённость и обучать** остальных в организации, чтобы те не стали жертвами.' },
      ],
    },
    {
      id: '1.1.4', title: 'Internal vs External Threats', titleRu: 'Внутренние и внешние угрозы', kind: 'text',
      blocks: [
        { t: 'p', md: 'Угрозы приходят **изнутри и снаружи** организации. Атакующим нужна ценная чувствительная информация: **personnel records, intellectual property, and financial data**.' },
        { t: 'h', text: 'Internal threats' },
        { t: 'list', items: [
          'Осуществляются **нынешними или бывшими сотрудниками** и **контрактными партнёрами**.',
          'Могут быть **случайными или намеренными**.',
          'Типичные действия: неправильное обращение с конфиденциальными данными, подключение **заражённых носителей**, открытие **вредоносных писем или сайтов**, угроза работе серверов и сетевых устройств.',
        ] },
        { t: 'h', text: 'External threats' },
        { t: 'list', items: [
          'Исходят от **любителей или опытных атакующих** вне организации.',
          'Они **эксплуатируют уязвимости** сетевых устройств либо используют **social engineering** (обман), чтобы получить доступ к внутренним ресурсам.',
        ] },
        { t: 'table', caption: 'Кто к какой категории относится (схема курса)', headers: ['Категория', 'Кто входит'], rows: [
          ['Internal', 'Employees and ex-employees, contract staff, trusted partners'],
          ['External', 'Organized hackers (hacktivists, terrorists, state-sponsored attackers), black / grey / white hat hackers, amateurs'],
        ] },
      ],
    },
    {
      id: '1.1.5', title: 'Why internal threats can be worse', titleRu: 'Почему внутренние опаснее', kind: 'text',
      blocks: [
        { t: 'note', variant: 'exam', title: 'Три причины', md: 'Внутренние угрозы способны нанести **больший ущерб**, чем внешние, потому что у инсайдеров есть прямой доступ и знания.' },
        { t: 'list', items: [
          '**прямой доступ** к помещениям и инфраструктурным устройствам,',
          '**инсайдерское знание** сети, ресурсов и конфиденциальных данных,',
          'знание **уже внедрённых мер защиты** (security countermeasures).',
        ] },
      ],
    },
    {
      id: '1.1.6', title: 'Know the Difference', titleRu: 'Внутренняя или внешняя', kind: 'activity',
      blocks: [
        {
          t: 'activity', title: 'Know the Difference (@Apollo)',
          prompt: 'Определи, внутренняя это угроза или внешняя.',
          options: ['INTERNAL', 'EXTERNAL'],
          items: [
            { q: 'An employee unknowingly connected an infected USB to their work laptop', a: 'INTERNAL' },
            { q: 'A former employee downloaded customer files by remotely accessing @Apollo’s network', a: 'INTERNAL' },
            { q: 'An employee entered the wrong information into the @Apollo database', a: 'INTERNAL' },
            { q: 'An employee was tricked into giving out confidential information by someone pretending to be their manager', a: 'EXTERNAL' },
            { q: 'An employee granted someone unauthorized physical access to @Apollo’s HQ', a: 'EXTERNAL' },
            { q: 'An employee clicked on a suspicious email', a: 'INTERNAL' },
          ],
          feedback: 'Правило: классифицируем по тому, **откуда пришёл threat actor**, а не по тому, кто нажал. Нынешние и бывшие сотрудники и контрактные партнёры (намеренно или случайно) = internal. Посторонний, получивший доступ, в том числе через social engineering или физический вход = external.',
        },
      ],
    },
    {
      id: '1.1.7', title: 'How threats spread', titleRu: 'Как распространяются угрозы', kind: 'text',
      blocks: [
        { t: 'note', variant: 'avatar', md: 'Киберугрозы распространяются несколькими путями: через **самих пользователей**, через **устройства** в сети, через **сервисы в публичном или частном облаке** и через **физические атаки**, когда нет нужных мер защиты.' },
      ],
    },
    {
      id: '1.1.8', title: 'User Threats and Vulnerabilities', titleRu: 'Домен пользователей', kind: 'accordion',
      blocks: [
        { t: 'def', term: 'User domain', md: 'Includes **anyone with access** to the organization’s information system: employees, customers, and contract partners.' },
        { t: 'p', md: 'Пользователи — **самое слабое звено** (weakest link) в системах информационной безопасности. Они существенная угроза для **confidentiality, integrity, and availability (CIA)** данных организации.' },
        {
          t: 'accordion', title: '7 самых частых угроз со стороны пользователей',
          items: [
            { title: 'No awareness of security', md: 'Пользователи обязаны знать и понимать чувствительные данные организации, политики и процедуры безопасности, технологии и контрмеры, внедрённые для защиты информации и информационных систем.' },
            { title: 'Poorly enforced security policies', md: 'Все пользователи должны знать политики безопасности **и последствия их несоблюдения**.' },
            { title: 'Data theft', md: 'Кража данных пользователями это крупная финансовая угроза: и **репутационный ущерб**, и **юридическая ответственность** за раскрытие чувствительной информации.' },
            { title: 'Unauthorized downloads and media', md: 'Многие заражения и атаки отслеживаются до загрузки неавторизованных писем, фото, музыки, игр, приложений и видео либо до использования неавторизованных носителей: внешних дисков и USB.' },
            { title: 'Unauthorized virtual private networks (VPNs)', md: 'VPN может **скрыть кражу информации**, потому что шифрование, обычно защищающее конфиденциальность, одновременно мешает администратору отследить передачу данных (если ему это не разрешено).' },
            { title: 'Unauthorized websites', md: 'Часто предлагают скачать скрипты или плагины с **вредоносным кодом или adware**; некоторые способны перехватить устройства пользователя, например камеры и приложения.' },
            { title: 'Destruction of systems, applications, or data', md: 'Случайное или намеренное разрушение либо саботаж. Делают **активисты, недовольные сотрудники или конкуренты**, которые удаляют данные и ломают или неверно настраивают устройства, чтобы сделать данные и системы **недоступными**.' },
          ],
        },
        { t: 'note', variant: 'exam', md: 'Ключевая фраза: никакое техническое решение, контроль или контрмера не сделают информационную систему безопаснее, чем **поведение и процессы людей, которые ею пользуются**.' },
      ],
    },
    {
      id: '1.1.9', title: 'Threats to Devices', titleRu: 'Домен устройств', kind: 'text',
      blocks: [
        { t: 'def', term: 'Device domain', md: 'Refers to any computers and other devices connected to a computer network.' },
        { t: 'list', items: [
          'Устройства, оставленные **включёнными и без присмотра**, дают постороннему доступ к сетевым ресурсам.',
          '**Загрузка файлов, фото, музыки или видео из ненадёжных источников** может привести к выполнению вредоносного кода.',
          'Киберпреступники эксплуатируют **уязвимости в установленном ПО**.',
          'Команды ИБ должны успевать за **ежедневным появлением новых вирусов, червей и другого malware**.',
          'Подключение **неавторизованных USB, CD или DVD** рискует занести malware или скомпрометировать данные на устройстве.',
          '**Намеренное нарушение политик** имеет серьёзные последствия для пользователя; политики существуют, чтобы защитить ИТ-инфраструктуру.',
          'Использование **устаревшего железа или ПО** делает системы и данные уязвимее.',
        ] },
      ],
    },
    {
      id: '1.1.10', title: 'Threats to the Local Area Network', titleRu: 'Домен LAN', kind: 'flip',
      blocks: [
        { t: 'def', term: 'LAN', md: 'A collection of devices, typically in the same geographic area, connected by **cables (wired)** or **airwaves (wireless)**.' },
        { t: 'p', md: 'Так как пользователи достигают систем, приложений и данных организации именно из домена LAN, ему нужны **сильная защита и строгий контроль доступа**.' },
        {
          t: 'flip', title: 'Угрозы LAN',
          cards: [
            { front: 'Wiring closets, data centers, computer rooms', back: 'Несанкционированный доступ в кроссовые, ЦОД и серверные.' },
            { front: 'Systems, applications, and data', back: 'Несанкционированный доступ к системам, приложениям и данным.' },
            { front: 'Network OS / software vulnerabilities', back: 'Уязвимости сетевой ОС или ПО и их обновления.' },
            { front: 'Rogue users', back: 'Посторонние получают доступ к беспроводным сетям.' },
            { front: 'Exploits of data in transit', back: 'Эксплуатация данных при передаче.' },
            { front: 'Mixed server platforms', back: 'LAN-серверы с разным железом или ОС усложняют управление и траблшутинг.' },
            { front: 'Network probing and port scanning', back: 'Несанкционированное зондирование сети и сканирование портов.' },
            { front: 'Misconfigured firewalls', back: 'Неправильно настроенные межсетевые экраны.' },
          ],
        },
      ],
    },
    {
      id: '1.1.11', title: 'Threats to the Private Cloud', titleRu: 'Частное облако', kind: 'text',
      blocks: [
        { t: 'def', term: 'Private cloud domain', md: 'Includes any private servers, resources, and IT infrastructure available **to members of a single organization** via the Internet.' },
        { t: 'p', md: 'Многие считают частное облако безопаснее, но у него остаются существенные угрозы:' },
        { t: 'list', items: [
          'Несанкционированное **network probing and port scanning**.',
          '**Unauthorized access to resources**.',
          'Уязвимости **ОС или ПО роутера, файрвола или сетевого устройства**.',
          '**Ошибки конфигурации** роутера, файрвола или сетевого устройства.',
          '**Удалённые пользователи**, которые обращаются к инфраструктуре и скачивают чувствительные данные.',
        ] },
      ],
    },
    {
      id: '1.1.12', title: 'Threats to the Public Cloud', titleRu: 'Публичное облако и модели сервиса', kind: 'carousel',
      blocks: [
        { t: 'def', term: 'Public cloud domain', md: 'The entirety of computing services hosted by a cloud, service, or Internet provider that are **available to the public and shared across organizations**. Для сравнения: частное облако размещает вычислительные ресурсы для **одной** организации.' },
        {
          t: 'carousel', title: 'Три модели облачного сервиса',
          slides: [
            { title: 'SaaS — Software as a Service', md: 'Software that is **centrally hosted** and accessed by users through a web browser, app, or other software. Софт не хранится локально, он в облаке.' },
            { title: 'PaaS — Platform as a Service', md: 'A **platform** that lets the organization develop, run, and manage its applications on the provider’s hardware, using the provider’s tools, accessed via the public cloud.' },
            { title: 'IaaS — Infrastructure as a Service', md: '**Virtual computing resources**: hardware, software, servers, storage, and other infrastructure components over the Internet.' },
          ],
        },
        { t: 'note', variant: 'tip', md: 'Мнемоника: SaaS = готовый софт, PaaS = платформа для разработки, IaaS = сырая инфраструктура.' },
      ],
    },
    {
      id: '1.1.13', title: 'Public Cloud threats', titleRu: 'Угрозы публичного облака', kind: 'text',
      blocks: [
        { t: 'note', variant: 'exam', md: 'Провайдеры публичного облака внедряют меры защиты облачной среды, **но организация сама отвечает за защиту своих ресурсов в облаке**.' },
        { t: 'h', text: 'Самые частые угрозы публичного облака' },
        { t: 'list', items: ['**Data breaches**.', '**Loss or theft of intellectual property**.', '**Compromised credentials or account hijacking**.', '**Social engineering attacks**.', '**Compliance violation**.'] },
      ],
    },
    {
      id: '1.1.14', title: 'What Do You Think?', titleRu: 'Физические объекты', kind: 'text',
      blocks: [
        { t: 'p', md: 'Физические угрозы часто недооценивают, но физическая безопасность критична, чтобы организация не стала жертвой киберпреступления.' },
        { t: 'def', term: 'Physical facilities domain', md: 'Includes all the services used by an organization, such as **heating, ventilation and air conditioning (HVAC)**, **water and fire detection**, and the **physical security measures** used to safeguard the premises.' },
        { t: 'h', text: 'Угрозы домена физических объектов (модельный ответ)' },
        { t: 'list', items: [
          '**Natural threats**: экстремальная погода и геологические опасности.',
          '**Unauthorized access to the premises**.',
          '**Power interruptions or outages**.',
          '**Social engineering attacks**, нацеленные на выведывание политик и процедур безопасности.',
          '**Breaches of electronic perimeter defenses**.',
          '**Theft**.',
          'An **unlocked data center**.',
          '**Lack of surveillance** on the premises.',
        ] },
      ],
    },
    {
      id: '1.1.15', title: 'Threats to Applications', titleRu: 'Домен приложений', kind: 'text',
      blocks: [
        { t: 'def', term: 'Application domain', md: 'Includes all critical **systems, applications, and data** used by the organization to support operations.' },
        { t: 'p', md: 'Организации всё чаще переносят приложения — **email, security monitoring, database management** — в публичное облако.' },
        { t: 'list', items: [
          'Несанкционированный доступ к **data centers, computer rooms, wiring closets, or systems**.',
          '**Server downtime** во время обслуживания.',
          '**Network operating system software vulnerabilities**.',
          '**Data loss**.',
          '**Client-server or web application development vulnerabilities**.',
        ] },
      ],
    },
    {
      id: '1.1.16', title: 'Domain Checker', titleRu: 'Проверка доменов', kind: 'activity',
      blocks: [
        {
          t: 'activity', title: 'Domain Checker (@Apollo)',
          prompt: 'Выбери правильный домен для каждого фрагмента.',
          options: ['User domain', 'Physical facilities domain', 'Device domain', 'LAN domain', 'SaaS', 'Public'],
          items: [
            { q: '**Employees** ...', a: 'User domain' },
            { q: '... gain access to the @Apollo offices with an **electronic staff ID card**', a: 'Physical facilities domain' },
            { q: 'They use a **desktop, laptop, tablet or smartphone** ...', a: 'Device domain' },
            { q: '... to log into **@Apollo’s network**', a: 'LAN domain' },
            { q: '@Apollo offers customers **centrally hosted eLearning modules for a subscription fee**, so it is a ... provider', a: 'SaaS' },
            { q: '... operating on a ... cloud domain', a: 'Public' },
          ],
          feedback: 'Определения из фидбэка курса: **User domain** — anyone with access to the organization’s information system. **Device domain** — any computers and other devices connected to a computer network. **Physical facilities domain** — все помещения плюс физические меры защиты. **LAN domain** — устройства, соединённые локально кабелем или по воздуху. **Private cloud domain** — ресурсы только для одной организации. **Public cloud domain** — сервисы провайдера, доступные публично и общие для организаций.',
        },
      ],
    },
    {
      id: '1.1.17', title: 'Threat Complexity', titleRu: 'Сложность угроз', kind: 'text',
      blocks: [
        { t: 'def', term: 'Advanced persistent threat (APT)', md: 'A **continuous** attack using **elaborate espionage tactics**, multiple actors, and/or **sophisticated malware**, to gain access to and analyze a target’s network.' },
        { t: 'list', items: [
          'Атакующие действуют **под радаром** и остаются **незамеченными долгое время**, последствия могут быть разрушительными.',
          'Обычно целят в **правительства и организации высокого уровня**, атаки **хорошо организованы и хорошо финансируются**.',
        ] },
        { t: 'def', term: 'Algorithm attacks', md: 'Take advantage of **algorithms in legitimate software** to generate **unintended behaviors**.' },
        { t: 'list', items: [
          'Пример: алгоритмы, отслеживающие потребление **энергии** компьютером, можно использовать, чтобы **выбирать цели** или **вызывать ложные тревоги**.',
          'Также могут **вывести компьютер из строя**, заставив его израсходовать всю **RAM** или перегрузив **CPU**.',
        ] },
      ],
    },
    {
      id: '1.1.18', title: 'Threat Intelligence', titleRu: 'Разведка угроз', kind: 'text',
      blocks: [
        { t: 'p', md: 'Организации полагаются на **threat intelligence data**, чтобы понять свой **общий риск** и построить эффективные **превентивные меры и меры реагирования**.' },
        { t: 'table', headers: ['Источник', 'Что это'], rows: [
          ['**Closed source**', 'Данные, требующие **платной подписки**'],
          ['**Open source intelligence (OSINT)**', 'Данные, собранные из **публично доступных** источников'],
        ] },
        { t: 'p', md: 'Обмен разведданными об угрозах набирает популярность: правительства, университеты, здравоохранение и частный бизнес сотрудничают, чтобы повысить общую защищённость.' },
      ],
    },
    {
      id: '1.1.19', title: 'Backdoors and Rootkits', titleRu: 'Бэкдоры и руткиты', kind: 'flip',
      blocks: [
        { t: 'p', md: 'Киберпреступники используют много типов **malicious software (malware)**. Два распространённых типа:' },
        { t: 'def', term: 'Backdoor', md: 'Backdoor programs such as **Netbus** and **Back Orifice** give cybercriminals **unauthorized access to a system by bypassing normal authentication procedures**.' },
        { t: 'list', items: [
          'Преступники обычно заставляют авторизованных пользователей неосознанно запустить **remote administrative tool (RAT)**, который ставит бэкдор и даёт **административный контроль** над компьютером.',
          'Бэкдоры дают **продолжающийся доступ** даже **после того, как организация закрыла исходную уязвимость**.',
        ] },
        { t: 'def', term: 'Rootkit', md: 'Malware designed to **modify the operating system** to create a **backdoor** for remote access.' },
        { t: 'list', items: [
          'Большинство руткитов эксплуатируют **уязвимости ПО**, чтобы дотянуться до недоступных ресурсов (**privilege escalation**) и **изменить системные файлы**.',
          'Руткиты могут менять **инструменты форензики и мониторинга**, из-за чего их **очень трудно обнаружить**.',
          'В большинстве случаев заражённый компьютер приходится **полностью очистить и переустановить ПО**.',
        ] },
      ],
    },
    {
      id: '1.1.20', title: 'Threat Intelligence and Research Sources', titleRu: 'Источники данных об угрозах', kind: 'carousel',
      blocks: [
        { t: 'def', term: 'CVE — Common Vulnerabilities and Exposures', md: 'A **dictionary of common vulnerabilities and exposures**. Sponsored by **US-CERT** and the **U.S. Department of Homeland Security**.' },
        { t: 'list', items: [
          'У каждой записи есть **стандартный идентификатор**, **краткое описание** уязвимости и **ссылки** на связанные отчёты.',
          'Список ведёт **MITRE Corporation**, некоммерческая организация, на публичном сайте.',
        ] },
        {
          t: 'carousel', title: 'Ещё три источника',
          slides: [
            { title: 'Automated Indicator Sharing (AIS)', md: 'A **CISA** capability enabling the **real-time exchange of cybersecurity threat indicators** using a standardized, structured language: **STIX (Structured Threat Information Expression)** and **TAXII (Trusted Automated Exchange of Intelligence Information)**.' },
            { title: 'Indicator of compromise (IOC)', md: 'Evidence of a security breach and details about it, for example **malware signatures** or **domain names**.' },
            { title: 'The dark web', md: '**Encrypted web content not indexed by conventional search engines**, requiring specific software, authorization, or configuration to access. Эксперты мониторят её ради новой threat intelligence.' },
          ],
        },
      ],
    },
    {
      id: '1.1.S', title: 'Summary: 7 threat domains', titleRu: 'Сводка: 7 доменов угроз', kind: 'summary',
      blocks: [
        { t: 'table', headers: ['Domain', 'Что охватывает', 'Главные угрозы'], rows: [
          ['**User**', 'Все с доступом: employees, customers, contract partners', 'No security awareness, poorly enforced policies, data theft, unauthorized downloads/media, unauthorized VPNs, unauthorized websites, destruction of systems/apps/data'],
          ['**Device**', 'Компьютеры и другие устройства в сети', 'Unattended devices, downloads from unreliable sources, software vulnerabilities, new malware, unauthorized USB/CD/DVD, policy violations, outdated hardware/software'],
          ['**LAN**', 'Устройства, соединённые локально кабелем или по воздуху', 'Access to wiring closets/data centers, access to systems and data, OS/software vulnerabilities, rogue wireless users, data in transit exploits, mixed server platforms, network probing and port scanning, misconfigured firewalls'],
          ['**Private cloud**', 'Частные серверы и инфраструктура одной организации', 'Probing and port scanning, unauthorized access to resources, device OS/software vulnerabilities, configuration errors, remote users downloading sensitive data'],
          ['**Public cloud**', 'Общие сервисы провайдера (SaaS, PaaS, IaaS)', 'Data breaches, IP loss or theft, compromised credentials / account hijacking, social engineering, compliance violation'],
          ['**Physical facilities**', 'Помещения, HVAC, water and fire detection, физическая охрана', 'Natural threats, unauthorized entry, power outages, social engineering, breach of electronic perimeter defenses, theft, unlocked data center, no surveillance'],
          ['**Application**', 'Критичные системы, приложения и данные', 'Unauthorized access to data centers/rooms/closets/systems, server downtime during maintenance, network OS software vulnerabilities, data loss, client-server or web app development vulnerabilities'],
        ] },
      ],
    },
    {
      id: '1.1.G', title: 'Glossary and exam facts', titleRu: 'Глоссарий и факты для экзамена', kind: 'glossary',
      blocks: [
        { t: 'table', headers: ['Термин', 'Значение'], rows: [
          ['**Threat domain**', 'Area of control, authority, or protection that attackers can exploit to gain access to a system'],
          ['**Internal threat**', 'Threat from current/former employees or contract partners, accidental or intentional'],
          ['**External threat**', 'Threat from outside: amateur or skilled attackers exploiting vulnerabilities or using social engineering'],
          ['**CIA**', 'Confidentiality, Integrity, Availability'],
          ['**NFC**', 'Near-field communication, короткодистанционная беспроводная технология, возможный вектор атаки'],
          ['**OSINT**', 'Open source intelligence, данные об угрозах из публичных источников'],
          ['**APT**', 'Advanced persistent threat: долгая, хорошо финансируемая, скрытная шпионская атака'],
          ['**Algorithm attack**', 'Злоупотребление алгоритмами легитимного ПО ради непредусмотренного поведения'],
          ['**Backdoor**', 'Доступ в обход обычной аутентификации, переживает закрытие исходной уязвимости'],
          ['**RAT**', 'Remote administrative tool, запускается жертвой, ставит бэкдор с админ-правами'],
          ['**Rootkit**', 'Malware, изменяющее ОС ради бэкдора, использует privilege escalation, прячется от форензики'],
          ['**Privilege escalation**', 'Получение доступа к ресурсам, которые не должны быть доступны'],
          ['**CVE**', 'Common Vulnerabilities and Exposures, словарь MITRE, спонсоры US-CERT и DHS'],
          ['**AIS**', 'Automated Indicator Sharing, возможность CISA для обмена индикаторами в реальном времени'],
          ['**STIX**', 'Structured Threat Information Expression, язык описания индикаторов'],
          ['**TAXII**', 'Trusted Automated Exchange of Intelligence Information, транспорт для обмена'],
          ['**IOC**', 'Indicator of compromise: сигнатура malware, доменное имя и подобное'],
          ['**Dark web**', 'Зашифрованный контент, не индексируемый поисковиками, нужен спец-софт или авторизация'],
          ['**SaaS / PaaS / IaaS**', 'Software / Platform / Infrastructure as a Service'],
          ['**HVAC**', 'Heating, ventilation and air conditioning, часть physical facilities domain'],
        ] },
        { t: 'note', variant: 'exam', title: 'Факты, которые спрашивают чаще всего', md: '1) Threat domain = area of control, authority, or protection. 2) Категорий угроз **восемь**. 3) **Users are the weakest link**. 4) Внутренние опаснее: прямой доступ плюс знание сети и контрмер. 5) Sabotage делает **авторизованный** пользователь, human error случаен. 6) **VPN может быть угрозой**, потому что шифрование скрывает кражу от админа. 7) SaaS готовый софт, PaaS платформа, IaaS инфраструктура. 8) В публичном облаке **организация всё равно отвечает** за свои ресурсы. 9) APT долгий, скрытный, финансируемый. 10) Бэкдор живёт после патча, руткит обычно требует wipe. 11) CVE ведёт **MITRE**, спонсируют **US-CERT и DHS**. 12) AIS это **CISA** и использует **STIX и TAXII**.' },
        { t: 'h', text: 'Self-check questions' },
        { t: 'list', ordered: true, items: [
          'Define a threat domain in one sentence.',
          'Name all 8 categories of cyber threats with one example each.',
          'Give three reasons internal threats can be more damaging than external ones.',
          'List the 7 user domain threats.',
          'Why is an unauthorized VPN listed as a user threat?',
          'Name five threats to the LAN domain.',
          'What is the difference between the private cloud domain and the public cloud domain?',
          'Match SaaS, PaaS, IaaS to their definitions.',
          'Who is responsible for protecting an organization’s resources in the public cloud?',
          'List five threats to the physical facilities domain.',
          'What makes an APT different from an ordinary attack?',
          'How does an algorithm attack disable a computer?',
          'Why is a backdoor dangerous even after patching?',
          'Why are rootkits so hard to detect, and what is the usual remediation?',
          'What do CVE, AIS, STIX, TAXII, IOC and OSINT each stand for?',
        ] },
      ],
    },
  ],
  atoms: [
    // --- домены угроз ---
    { id: '1.1-d1', lesson: '1.1.1', kind: 'term', group: 'domains', groupLabel: 'Домены угроз', weight: 3,
      term: 'Threat domain', definition: 'An area of control, authority, or protection that attackers can exploit to gain access to a system.',
      cloze: 'A ___ is an area of control, authority, or protection that attackers can exploit to gain access to a system.',
      ru: 'Область контроля, полномочий или защиты, которую атакующие могут использовать для доступа к системе.' },
    { id: '1.1-d2', lesson: '1.1.8', kind: 'term', group: 'domains', groupLabel: 'Домены угроз', weight: 3,
      term: 'User domain', definition: 'Includes anyone with access to the organization’s information system: employees, customers, and contract partners.',
      cloze: 'The ___ includes anyone with access to the organization’s information system.',
      ru: 'Все, у кого есть доступ к информационной системе: сотрудники, клиенты, контрактные партнёры.' },
    { id: '1.1-d3', lesson: '1.1.9', kind: 'term', group: 'domains', groupLabel: 'Домены угроз', weight: 3,
      term: 'Device domain', definition: 'Refers to any computers and other devices connected to a computer network.',
      cloze: 'The ___ refers to any computers and other devices connected to a computer network.',
      ru: 'Любые компьютеры и устройства, подключённые к сети.' },
    { id: '1.1-d4', lesson: '1.1.10', kind: 'term', group: 'domains', groupLabel: 'Домены угроз', weight: 3,
      term: 'LAN domain', definition: 'A collection of devices, typically in the same geographic area, connected by cables (wired) or airwaves (wireless).',
      cloze: 'The ___ is a collection of devices connected locally by cables or airwaves.',
      aliases: ['LAN', 'local area network'],
      ru: 'Устройства в одной географической зоне, соединённые кабелем или по воздуху.' },
    { id: '1.1-d5', lesson: '1.1.11', kind: 'term', group: 'domains', groupLabel: 'Домены угроз', weight: 3,
      term: 'Private cloud domain', definition: 'Includes any private servers, resources, and IT infrastructure available to members of a single organization via the Internet.',
      cloze: 'The ___ is available to members of a single organization via the Internet.',
      ru: 'Частные серверы и инфраструктура, доступные только членам одной организации.' },
    { id: '1.1-d6', lesson: '1.1.12', kind: 'term', group: 'domains', groupLabel: 'Домены угроз', weight: 3,
      term: 'Public cloud domain', definition: 'The entirety of computing services hosted by a cloud, service, or Internet provider that are available to the public and shared across organizations.',
      cloze: 'The ___ is available to the public and shared across organizations.',
      ru: 'Сервисы провайдера, доступные публично и общие для разных организаций.' },
    { id: '1.1-d7', lesson: '1.1.14', kind: 'term', group: 'domains', groupLabel: 'Домены угроз', weight: 3,
      term: 'Physical facilities domain', definition: 'Includes all the services used by an organization such as HVAC, water and fire detection, and the physical security measures used to safeguard the premises.',
      cloze: 'The ___ covers HVAC, water and fire detection, and physical security measures.',
      ru: 'Помещения, HVAC, пожарная и водяная сигнализация и физические меры охраны.' },
    { id: '1.1-d8', lesson: '1.1.15', kind: 'term', group: 'domains', groupLabel: 'Домены угроз', weight: 3,
      term: 'Application domain', definition: 'Includes all critical systems, applications, and data used by the organization to support operations.',
      cloze: 'The ___ includes all critical systems, applications, and data used to support operations.',
      ru: 'Критичные системы, приложения и данные, поддерживающие работу организации.' },

    // --- 8 категорий киберугроз ---
    { id: '1.1-c1', lesson: '1.1.2', kind: 'term', group: 'threat-categories', groupLabel: '8 категорий киберугроз', weight: 3,
      term: 'Software attacks', definition: 'A successful denial-of-service (DoS) attack; a computer virus.', ru: 'DoS-атака, компьютерный вирус.' },
    { id: '1.1-c2', lesson: '1.1.2', kind: 'term', group: 'threat-categories', groupLabel: '8 категорий киберугроз', weight: 3,
      term: 'Software errors', definition: 'A software bug; an application going offline; a cross-site script or illegal file server share.', ru: 'Баг, приложение упало, XSS или незаконная шара на файловом сервере.' },
    { id: '1.1-c3', lesson: '1.1.2', kind: 'term', group: 'threat-categories', groupLabel: '8 категорий киберугроз', weight: 3,
      term: 'Sabotage', definition: 'An authorized user penetrating and compromising the organization’s primary database; defacement of the organization’s website.', ru: 'Делает АВТОРИЗОВАННЫЙ пользователь, намеренно. Дефейс сайта, взлом главной БД.' },
    { id: '1.1-c4', lesson: '1.1.2', kind: 'term', group: 'threat-categories', groupLabel: '8 категорий киберугроз', weight: 3,
      term: 'Human error', definition: 'Inadvertent data entry errors; a firewall misconfiguration.', ru: 'Случайность: опечатка при вводе, неверная настройка файрвола.' },
    { id: '1.1-c5', lesson: '1.1.2', kind: 'term', group: 'threat-categories', groupLabel: '8 категорий киберугроз', weight: 2,
      term: 'Theft', definition: 'Laptops or equipment stolen from an unlocked room.', ru: 'Кража ноутбуков или оборудования из незапертой комнаты.' },
    { id: '1.1-c6', lesson: '1.1.2', kind: 'term', group: 'threat-categories', groupLabel: '8 категорий киберугроз', weight: 2,
      term: 'Hardware failures', definition: 'Hard drive crashes.', ru: 'Отказ жёсткого диска.' },
    { id: '1.1-c7', lesson: '1.1.2', kind: 'term', group: 'threat-categories', groupLabel: '8 категорий киберугроз', weight: 2,
      term: 'Utility interruption', definition: 'Electrical power outages; water damage from sprinkler failure.', ru: 'Отключение электричества, залив из-за спринклера.' },
    { id: '1.1-c8', lesson: '1.1.2', kind: 'term', group: 'threat-categories', groupLabel: '8 категорий киберугроз', weight: 2,
      term: 'Natural disasters', definition: 'Severe storms (hurricanes, tornados); earthquakes; floods; fires.', ru: 'Ураганы, торнадо, землетрясения, наводнения, пожары.' },
    { id: '1.1-c9', lesson: '1.1.2', kind: 'enum', group: 'threat-categories-enum', groupLabel: 'Список категорий', weight: 3,
      term: 'The 8 categories of cyber threats', definition: 'Software attacks, software errors, sabotage, human error, theft, hardware failures, utility interruption, natural disasters.',
      items: ['Software attacks', 'Software errors', 'Sabotage', 'Human error', 'Theft', 'Hardware failures', 'Utility interruption', 'Natural disasters'],
      decoys: ['Social engineering', 'Phishing', 'Compliance violation', 'Data exfiltration'],
      ru: 'Всего восемь категорий.' },
    // --- внутренние и внешние угрозы ---
    { id: '1.1-t1', lesson: '1.1.4', kind: 'term', group: 'threat-actors', groupLabel: 'Внутренние и внешние', weight: 3,
      term: 'Internal threat', definition: 'A threat carried out by current or former employees and contract partners, either accidental or intentional.',
      cloze: 'An ___ is carried out by current or former employees and contract partners, accidentally or intentionally.',
      ru: 'Нынешние или бывшие сотрудники и контрактные партнёры, случайно или намеренно.' },
    { id: '1.1-t2', lesson: '1.1.4', kind: 'term', group: 'threat-actors', groupLabel: 'Внутренние и внешние', weight: 3,
      term: 'External threat', definition: 'A threat from amateur or skilled attackers outside the organization who exploit vulnerabilities in networked devices or use social engineering.',
      cloze: 'An ___ comes from amateur or skilled attackers outside the organization.',
      ru: 'Атакующие снаружи: эксплуатируют уязвимости или применяют social engineering.' },
    { id: '1.1-t3', lesson: '1.1.5', kind: 'enum', group: 'insider-risk', groupLabel: 'Почему инсайдер опаснее', weight: 3,
      term: 'Why internal threats can cause greater damage', definition: 'Insiders have direct access to premises and infrastructure devices, insider knowledge of the network, resources and confidential data, and knowledge of the security countermeasures in place.',
      items: ['Direct access to the premises and infrastructure devices', 'Insider knowledge of the network, resources and confidential data', 'Knowledge of the security countermeasures in place'],
      decoys: ['Unlimited budget for tools', 'Physical distance from the target', 'Access to the dark web'],
      ru: 'Три причины: прямой доступ, знание сети и данных, знание контрмер.' },
    { id: '1.1-b1', lesson: '1.1.6', kind: 'bucket', bucket: 'INTERNAL', group: 'int-ext-cases', groupLabel: 'Internal или External', weight: 3,
      term: 'An employee unknowingly connected an infected USB to their work laptop', definition: 'INTERNAL — действие сотрудника организации.', ru: 'Сотрудник = internal.' },
    { id: '1.1-b2', lesson: '1.1.6', kind: 'bucket', bucket: 'INTERNAL', group: 'int-ext-cases', groupLabel: 'Internal или External', weight: 3,
      term: 'A former employee downloaded customer files remotely', definition: 'INTERNAL — бывший сотрудник тоже относится к внутренним.', ru: 'Бывший сотрудник = internal.' },
    { id: '1.1-b3', lesson: '1.1.6', kind: 'bucket', bucket: 'INTERNAL', group: 'int-ext-cases', groupLabel: 'Internal или External', weight: 3,
      term: 'An employee entered the wrong information into the database', definition: 'INTERNAL — случайная ошибка сотрудника.', ru: 'Ошибка сотрудника = internal.' },
    { id: '1.1-b4', lesson: '1.1.6', kind: 'bucket', bucket: 'EXTERNAL', group: 'int-ext-cases', groupLabel: 'Internal или External', weight: 3,
      term: 'An employee was tricked by someone pretending to be their manager', definition: 'EXTERNAL — threat actor снаружи, это social engineering.', ru: 'Обманул посторонний, значит external.' },
    { id: '1.1-b5', lesson: '1.1.6', kind: 'bucket', bucket: 'EXTERNAL', group: 'int-ext-cases', groupLabel: 'Internal или External', weight: 3,
      term: 'An employee granted someone unauthorized physical access to HQ', definition: 'EXTERNAL — доступ получил посторонний человек.', ru: 'Внутрь попал посторонний, значит external.' },
    { id: '1.1-b6', lesson: '1.1.6', kind: 'bucket', bucket: 'INTERNAL', group: 'int-ext-cases', groupLabel: 'Internal или External', weight: 3,
      term: 'An employee clicked on a suspicious email', definition: 'INTERNAL — действие совершил сотрудник.', ru: 'Кликнул сотрудник = internal.' },

    // --- 7 угроз домена пользователей ---
    { id: '1.1-u1', lesson: '1.1.8', kind: 'term', group: 'user-threats', groupLabel: '7 угроз User domain', weight: 3,
      term: 'No awareness of security', definition: 'Users must know the organization’s sensitive data, security policies and procedures, technologies and countermeasures put in place.', ru: 'Пользователь не знает политик, данных и контрмер.' },
    { id: '1.1-u2', lesson: '1.1.8', kind: 'term', group: 'user-threats', groupLabel: '7 угроз User domain', weight: 3,
      term: 'Poorly enforced security policies', definition: 'All users must know the security policies and the consequences of non-compliance.', ru: 'Политики есть, но их не соблюдают и не знают о последствиях.' },
    { id: '1.1-u3', lesson: '1.1.8', kind: 'term', group: 'user-threats', groupLabel: '7 угроз User domain', weight: 3,
      term: 'Data theft', definition: 'Data stolen by users is a major financial threat through reputational damage and legal liability for the disclosure of sensitive information.', ru: 'Кража данных: репутационный ущерб плюс юридическая ответственность.' },
    { id: '1.1-u4', lesson: '1.1.8', kind: 'term', group: 'user-threats', groupLabel: '7 угроз User domain', weight: 3,
      term: 'Unauthorized downloads and media', definition: 'Infections traced back to users downloading unauthorized emails, photos, music, games, apps and videos, or using unauthorized media such as external hard disks and USB drives.', ru: 'Неавторизованные загрузки и носители.' },
    { id: '1.1-u5', lesson: '1.1.8', kind: 'term', group: 'user-threats', groupLabel: '7 угроз User domain', weight: 3,
      term: 'Unauthorized virtual private networks (VPNs)', definition: 'A VPN can hide the theft of information, because the encryption that protects confidentiality also stops a network administrator from tracking the data transmission.',
      aliases: ['unauthorized vpn', 'vpn'], ru: 'Шифрование VPN скрывает кражу данных от администратора.' },
    { id: '1.1-u6', lesson: '1.1.8', kind: 'term', group: 'user-threats', groupLabel: '7 угроз User domain', weight: 3,
      term: 'Unauthorized websites', definition: 'They prompt users to download scripts or plugins containing malicious code or adware, and some can take over user devices such as cameras and applications.', ru: 'Сайты с вредоносными скриптами и adware, могут захватить камеру.' },
    { id: '1.1-u7', lesson: '1.1.8', kind: 'term', group: 'user-threats', groupLabel: '7 угроз User domain', weight: 3,
      term: 'Destruction of systems, applications, or data', definition: 'Accidental or deliberate destruction or sabotage by activists, disgruntled employees or industry competitors to make data and information systems unavailable.', ru: 'Активисты, обиженные сотрудники, конкуренты делают системы недоступными.' },
    { id: '1.1-u8', lesson: '1.1.8', kind: 'fact', group: 'user-domain-facts', groupLabel: 'Факты о пользователях', weight: 3,
      term: 'The weakest link in information security', definition: 'Users are the weakest link in information security systems.',
      cloze: '___ are the weakest link in information security systems.', clozeAnswer: 'Users', aliases: ['users'],
      ru: 'Пользователи это самое слабое звено.' },
    { id: '1.1-u9', lesson: '1.1.8', kind: 'fact', group: 'user-domain-facts', groupLabel: 'Факты о пользователях', weight: 2,
      term: 'CIA', definition: 'Confidentiality, Integrity, Availability — the three properties of data that users can threaten.',
      cloze: 'Users are a significant threat to the ___ of the organization’s data.', clozeAnswer: 'CIA',
      ru: 'Конфиденциальность, целостность, доступность.' },
    // --- перечни угроз по доменам ---
    { id: '1.1-e1', lesson: '1.1.9', kind: 'enum', group: 'domain-threat-lists', groupLabel: 'Угрозы по доменам', weight: 2,
      term: 'Threats to the device domain', definition: 'Unattended powered-on devices, downloads from unreliable sources, software vulnerabilities, new viruses and worms, unauthorized USB/CD/DVD, deliberate policy violations, outdated hardware or software.',
      items: ['Devices left powered on and unattended', 'Downloading files from unreliable sources', 'Security vulnerabilities in installed software', 'Unauthorized USB drives, CDs or DVDs', 'Violating policies on purpose', 'Outdated hardware or software'],
      decoys: ['Misconfigured firewalls', 'Compliance violation', 'Unlocked data center'],
      ru: 'Угрозы домена устройств.' },
    { id: '1.1-e2', lesson: '1.1.10', kind: 'enum', group: 'domain-threat-lists', groupLabel: 'Угрозы по доменам', weight: 3,
      term: 'Threats to the LAN domain', definition: 'Unauthorized access to wiring closets, data centers and computer rooms; unauthorized access to systems, applications and data; network OS or software vulnerabilities; rogue users on wireless; exploits of data in transit; LAN servers with different hardware or operating systems; unauthorized network probing and port scanning; misconfigured firewalls.',
      items: ['Unauthorized access to wiring closets, data centers and computer rooms', 'Rogue users gaining access to wireless networks', 'Exploits of data in transit', 'Unauthorized network probing and port scanning', 'Misconfigured firewalls', 'LAN servers with different hardware or operating systems'],
      decoys: ['Compliance violation', 'Loss or theft of intellectual property', 'Server downtime during maintenance'],
      ru: 'Угрозы домена LAN.' },
    { id: '1.1-e3', lesson: '1.1.11', kind: 'enum', group: 'domain-threat-lists', groupLabel: 'Угрозы по доменам', weight: 3,
      term: 'Threats to the private cloud domain', definition: 'Unauthorized network probing and port scanning; unauthorized access to resources; router, firewall or network device OS or software vulnerabilities; router, firewall or network device configuration errors; remote users accessing the infrastructure and downloading sensitive data.',
      items: ['Unauthorized network probing and port scanning', 'Unauthorized access to resources', 'Router, firewall or network device software vulnerabilities', 'Router, firewall or network device configuration errors', 'Remote users downloading sensitive data'],
      decoys: ['Compliance violation', 'Account hijacking', 'Natural threats'],
      ru: 'Угрозы частного облака.' },
    { id: '1.1-e4', lesson: '1.1.13', kind: 'enum', group: 'domain-threat-lists', groupLabel: 'Угрозы по доменам', weight: 3,
      term: 'Most common public cloud domain threats', definition: 'Data breaches; loss or theft of intellectual property; compromised credentials or account hijacking; social engineering attacks; compliance violation.',
      items: ['Data breaches', 'Loss or theft of intellectual property', 'Compromised credentials or account hijacking', 'Social engineering attacks', 'Compliance violation'],
      decoys: ['Misconfigured firewalls', 'Hard drive crashes', 'Unlocked data center'],
      ru: 'Пять угроз публичного облака.' },
    { id: '1.1-e5', lesson: '1.1.14', kind: 'enum', group: 'domain-threat-lists', groupLabel: 'Угрозы по доменам', weight: 3,
      term: 'Threats to the physical facilities domain', definition: 'Natural threats; unauthorized access to the premises; power interruptions or outages; social engineering attacks; breaches of electronic perimeter defenses; theft; an unlocked data center; lack of surveillance on the premises.',
      items: ['Natural threats such as extreme weather', 'Unauthorized access to the premises', 'Power interruptions or outages', 'Breaches of electronic perimeter defenses', 'An unlocked data center', 'Lack of surveillance on the premises'],
      decoys: ['Port scanning', 'Cross-site scripting', 'Account hijacking'],
      ru: 'Угрозы физических объектов.' },
    { id: '1.1-e6', lesson: '1.1.15', kind: 'enum', group: 'domain-threat-lists', groupLabel: 'Угрозы по доменам', weight: 3,
      term: 'Common threats to applications', definition: 'Unauthorized access to data centers, computer rooms, wiring closets or systems; server downtime during maintenance periods; network operating system software vulnerabilities; data loss; client-server or web application development vulnerabilities.',
      items: ['Unauthorized access to data centers, computer rooms, wiring closets or systems', 'Server downtime during maintenance periods', 'Network operating system software vulnerabilities', 'Data loss', 'Client-server or web application development vulnerabilities'],
      decoys: ['Rogue wireless users', 'Natural disasters', 'Dumpster diving'],
      ru: 'Угрозы домена приложений.' },
    { id: '1.1-e7', lesson: '1.1.1', kind: 'enum', group: 'domain-threat-lists', groupLabel: 'Векторы внутри домена', weight: 2,
      term: 'Ways attackers exploit systems within a threat domain', definition: 'Direct physical access; wireless networking beyond the boundaries; Bluetooth or NFC devices; malicious email attachments; less secure supply chain elements; the organization’s social media accounts; removable media; cloud-based applications.',
      items: ['Direct physical access to systems and networks', 'Wireless networking that extends beyond the boundaries', 'Bluetooth or near-field communication (NFC) devices', 'Malicious email attachments', 'Less secure elements in the supply chain', 'Removable media such as flash drives', 'Cloud-based applications'],
      decoys: ['Hard drive crashes', 'Power outages', 'Sprinkler failure'],
      ru: 'Восемь путей эксплуатации внутри домена.' },

    // --- облачные модели ---
    { id: '1.1-s1', lesson: '1.1.12', kind: 'term', group: 'cloud-models', groupLabel: 'Модели облака', weight: 3,
      term: 'SaaS', definition: 'Software as a Service: software that is centrally hosted and accessed by users through a web browser, app or other software; it is not stored locally.',
      cloze: 'Centrally hosted software accessed through a browser is ___.', aliases: ['software as a service'],
      ru: 'Готовый софт в облаке, доступ через браузер.' },
    { id: '1.1-s2', lesson: '1.1.12', kind: 'term', group: 'cloud-models', groupLabel: 'Модели облака', weight: 3,
      term: 'PaaS', definition: 'Platform as a Service: a platform that lets the organization develop, run and manage its applications on the provider’s hardware using the provider’s tools.',
      cloze: 'A platform to develop, run and manage applications on the provider’s hardware is ___.', aliases: ['platform as a service'],
      ru: 'Платформа для разработки и запуска приложений.' },
    { id: '1.1-s3', lesson: '1.1.12', kind: 'term', group: 'cloud-models', groupLabel: 'Модели облака', weight: 3,
      term: 'IaaS', definition: 'Infrastructure as a Service: virtual computing resources — hardware, software, servers, storage and other infrastructure components over the Internet.',
      cloze: 'Virtual hardware, servers and storage delivered over the Internet is ___.', aliases: ['infrastructure as a service'],
      ru: 'Сырая виртуальная инфраструктура.' },
    { id: '1.1-s4', lesson: '1.1.13', kind: 'fact', group: 'cloud-models', groupLabel: 'Модели облака', weight: 3,
      term: 'Responsibility in the public cloud', definition: 'The cloud provider secures the cloud environment, but the organization is responsible for protecting its own resources in the cloud.',
      cloze: 'In the public cloud the ___ is responsible for protecting its own resources.', clozeAnswer: 'organization',
      ru: 'За свои ресурсы в облаке отвечает сама организация.' },
    // --- сложность угроз и malware ---
    { id: '1.1-x1', lesson: '1.1.17', kind: 'term', group: 'complexity', groupLabel: 'Сложные угрозы', weight: 3,
      term: 'Advanced persistent threat (APT)', definition: 'A continuous attack using elaborate espionage tactics, multiple actors and/or sophisticated malware to gain access to and analyze a target’s network, staying undetected for a long time.',
      cloze: 'An ___ is a continuous, well-funded espionage attack that stays undetected for a long time.', aliases: ['APT', 'advanced persistent threat'],
      ru: 'Долгая скрытная шпионская атака, обычно против правительств и крупных организаций.' },
    { id: '1.1-x2', lesson: '1.1.17', kind: 'term', group: 'complexity', groupLabel: 'Сложные угрозы', weight: 3,
      term: 'Algorithm attack', definition: 'Takes advantage of algorithms in legitimate software to generate unintended behaviors, for example disabling a computer by exhausting its RAM or overworking its CPU.',
      cloze: 'An ___ abuses algorithms in legitimate software to generate unintended behaviors.',
      ru: 'Злоупотребление алгоритмами легитимного ПО: ложные тревоги, исчерпание RAM, перегрузка CPU.' },
    { id: '1.1-m1', lesson: '1.1.19', kind: 'term', group: 'malware', groupLabel: 'Malware', weight: 3,
      term: 'Backdoor', definition: 'A program such as Netbus or Back Orifice that gives cybercriminals unauthorized access to a system by bypassing normal authentication procedures, and grants continued access even after the original vulnerability is fixed.',
      cloze: 'A ___ bypasses normal authentication procedures and keeps working after the original vulnerability is fixed.',
      ru: 'Обход обычной аутентификации, живёт даже после патча. Примеры: Netbus, Back Orifice.' },
    { id: '1.1-m2', lesson: '1.1.19', kind: 'term', group: 'malware', groupLabel: 'Malware', weight: 3,
      term: 'Rootkit', definition: 'Malware designed to modify the operating system to create a backdoor for remote access; it uses privilege escalation, modifies system files and monitoring tools, and usually requires wiping the computer.',
      cloze: 'A ___ modifies the operating system to create a backdoor and is very hard to detect.',
      ru: 'Меняет ОС ради бэкдора, прячется от форензики, обычно нужен wipe и переустановка.' },
    { id: '1.1-m3', lesson: '1.1.19', kind: 'term', group: 'malware', groupLabel: 'Malware', weight: 3,
      term: 'Remote administrative tool (RAT)', definition: 'A tool that authorized users are tricked into running, which installs a backdoor and gives the criminal administrative control of the target computer.',
      aliases: ['RAT'], ru: 'Жертва сама запускает, ставится бэкдор с админ-правами.' },
    { id: '1.1-m4', lesson: '1.1.19', kind: 'term', group: 'malware', groupLabel: 'Malware', weight: 3,
      term: 'Privilege escalation', definition: 'Getting access to resources that should not normally be accessible.',
      cloze: 'Rootkits exploit software vulnerabilities to perform ___ and modify system files.',
      ru: 'Получение доступа к ресурсам, которые не должны быть доступны.' },

    // --- threat intelligence ---
    { id: '1.1-i1', lesson: '1.1.20', kind: 'term', group: 'threat-intel', groupLabel: 'Источники threat intelligence', weight: 3,
      term: 'CVE', definition: 'Common Vulnerabilities and Exposures: a dictionary of common vulnerabilities and exposures, maintained by the MITRE Corporation and sponsored by US-CERT and the U.S. Department of Homeland Security.',
      cloze: 'The dictionary of vulnerabilities maintained by MITRE is called ___.', aliases: ['common vulnerabilities and exposures'],
      ru: 'Словарь уязвимостей. Ведёт MITRE, спонсоры US-CERT и DHS.' },
    { id: '1.1-i2', lesson: '1.1.20', kind: 'term', group: 'threat-intel', groupLabel: 'Источники threat intelligence', weight: 3,
      term: 'Automated Indicator Sharing (AIS)', definition: 'A CISA capability enabling the real-time exchange of cybersecurity threat indicators using STIX and TAXII.',
      cloze: '___ is a CISA capability for the real-time exchange of threat indicators.', aliases: ['AIS'],
      ru: 'Возможность CISA для обмена индикаторами в реальном времени.' },
    { id: '1.1-i3', lesson: '1.1.20', kind: 'term', group: 'threat-intel', groupLabel: 'Источники threat intelligence', weight: 3,
      term: 'STIX', definition: 'Structured Threat Information Expression: the standardized structured language used to describe cybersecurity threat indicators.',
      aliases: ['structured threat information expression'], ru: 'Язык описания индикаторов угроз.' },
    { id: '1.1-i4', lesson: '1.1.20', kind: 'term', group: 'threat-intel', groupLabel: 'Источники threat intelligence', weight: 3,
      term: 'TAXII', definition: 'Trusted Automated Exchange of Intelligence Information: the transport used for sharing threat indicators.',
      aliases: ['trusted automated exchange of intelligence information'], ru: 'Транспорт для обмена индикаторами.' },
    { id: '1.1-i5', lesson: '1.1.20', kind: 'term', group: 'threat-intel', groupLabel: 'Источники threat intelligence', weight: 3,
      term: 'Indicator of compromise (IOC)', definition: 'Evidence of a security breach and details about it, for example malware signatures or domain names.',
      aliases: ['IOC'], ru: 'Свидетельство взлома: сигнатура malware, доменное имя.' },
    { id: '1.1-i6', lesson: '1.1.20', kind: 'term', group: 'threat-intel', groupLabel: 'Источники threat intelligence', weight: 3,
      term: 'The dark web', definition: 'Encrypted web content not indexed by conventional search engines, requiring specific software, authorization or configuration to access.',
      aliases: ['dark web'], ru: 'Зашифрованный контент вне поисковиков, нужен спец-софт или авторизация.' },
    { id: '1.1-i7', lesson: '1.1.18', kind: 'term', group: 'threat-intel', groupLabel: 'Источники threat intelligence', weight: 3,
      term: 'Open source intelligence (OSINT)', definition: 'Threat intelligence gathered from publicly available information sources.',
      cloze: 'Threat data gathered from publicly available sources is called ___.', aliases: ['OSINT'],
      ru: 'Разведданные из публичных источников.' },
    { id: '1.1-i8', lesson: '1.1.18', kind: 'term', group: 'threat-intel', groupLabel: 'Источники threat intelligence', weight: 2,
      term: 'Closed source data', definition: 'Threat intelligence data that requires a paid subscription.',
      ru: 'Данные по платной подписке.' },

    // --- акронимы ---
    { id: '1.1-a1', lesson: '1.1.1', kind: 'term', group: 'acronyms', groupLabel: 'Акронимы', weight: 2,
      term: 'NFC', definition: 'Near-field communication: a short range wireless technology and a possible attack vector.',
      aliases: ['near-field communication', 'near field communication'], ru: 'Ближняя бесконтактная связь, возможный вектор атаки.' },
    { id: '1.1-a2', lesson: '1.1.14', kind: 'term', group: 'acronyms', groupLabel: 'Акронимы', weight: 2,
      term: 'HVAC', definition: 'Heating, ventilation and air conditioning: part of the physical facilities domain.',
      aliases: ['heating ventilation and air conditioning'], ru: 'Отопление, вентиляция и кондиционирование.' },
  ],
}
