import type { Island } from '@/types'

export const island_1_2: Island = {
  id: '1.2',
  moduleId: 1,
  title: 'Deception',
  titleRu: 'Обман',
  objective: 'Identify the different deception methods used by attackers to deceive their victims.',
  icon: 'VenetianMask',
  lessons: [
    {
      id: '1.2.1', title: 'Social Engineering', titleRu: 'Социальная инженерия', kind: 'carousel',
      blocks: [
        { t: 'def', term: 'Social engineering', md: 'A non-technical strategy that attempts to manipulate individuals into performing certain actions or divulging confidential information.' },
        { t: 'p', md: 'Вместо уязвимостей софта или железа social engineering эксплуатирует **человеческую природу**: готовность помочь либо слабости вроде жадности или тщеславия.' },
        {
          t: 'carousel', title: 'Три распространённых типа атак',
          slides: [
            { title: 'Pretexting', md: 'This type of attack occurs when an individual **lies to gain access to privileged data**. Например, атакующий притворяется, что ему нужны личные или финансовые данные, чтобы подтвердить личность человека.' },
            { title: 'Something for something (quid pro quo)', md: 'Quid pro quo attacks involve **a request for personal information in exchange for something**, like a gift. Например, письмо просит выдать чувствительные данные в обмен на бесплатный отпуск.' },
            { title: 'Identity fraud', md: 'The use of a person’s **stolen identity** to obtain goods or services by deception. Например, кто-то получил ваши данные и пытается выпустить кредитку на ваше имя.' },
          ],
        },
        { t: 'figure', caption: 'Pretexting — театральная маска с речевым облачком; quid pro quo — две фигуры со стрелками по кругу; identity fraud — иконка хакера.' },
      ],
    },
    {
      id: '1.2.2', title: 'Social Engineering Tactics', titleRu: '7 тактик', kind: 'accordion',
      blocks: [
        { t: 'p', md: 'Киберпреступники опираются на несколько тактик социальной инженерии, чтобы получить доступ к чувствительной информации.' },
        {
          t: 'accordion', title: '7 тактик',
          items: [
            { title: 'Authority', md: 'Attackers prey on the fact that people are more likely to comply when instructed by someone they perceive as **an authority figure**.', example: 'Руководитель открывает вложение, похожее на официальную повестку (subpoena), а это заражённый PDF.' },
            { title: 'Intimidation', md: 'Cybercriminals will often **bully a victim** into taking an action that compromises security.', example: 'Секретарю звонят: у начальника важная презентация, файлы повреждены, это ваша вина, срочно пришлите файлы или вас уволят.' },
            { title: 'Consensus', md: 'Often called **social proof**: people tend to act the same way as other people around them, думая, что раз так делают все, значит это правильно.', example: 'Пост о бизнес-возможности с десятками комментариев от реальных и поддельных аккаунтов, подтверждающих его надёжность.' },
            { title: 'Scarcity', md: 'Известная маркетинговая тактика: люди действуют, когда думают, что **количество ограничено**.', example: 'Письмо о люксовом товаре по смешной цене, но экземпляров осталось всего несколько.' },
            { title: 'Urgency', md: 'Люди действуют, когда думают, что **времени мало**.', example: 'Поддельное предложение с ограниченным сроком доставки, чтобы жертва действовала быстро.' },
            { title: 'Familiarity', md: 'People are more likely to do what another person asks **if they like this person**. Атакующие выстраивают контакт или **клонируют профиль друга** в соцсети.' },
            { title: 'Trust', md: 'Построение доверия требует больше времени.', example: 'Киберпреступник под видом эксперта по безопасности звонит жертве, помогает и «обнаруживает серьёзную ошибку», требующую немедленного вмешательства. Решение даёт ему возможность нарушить безопасность жертвы.' },
          ],
        },
      ],
    },
    {
      id: '1.2.3', title: 'Avatar', titleRu: 'Заметка курса', kind: 'text',
      blocks: [
        { t: 'note', variant: 'avatar', md: 'Арсенал киберпреступников обширен и постоянно развивается. Иногда они **комбинируют две и более тактики**, чтобы повысить шансы. Задача специалистов по ИБ — повышать осведомлённость и обучать людей в организации, чтобы те не стали жертвами.' },
      ],
    },
    {
      id: '1.2.4', title: 'Watch Out!', titleRu: 'Определи атаку', kind: 'activity',
      blocks: [
        { t: 'p', md: 'Сценарий: подозрительное письмо удалённым сотрудникам @Apollo. Выглядит так, будто его отправил Guru, и просит перейти по ссылке и скачать VPN, который защитит домашний Wi-Fi. Письмо выглядит легитимно, но переход по ссылке ставит malware на устройство сотрудника.' },
        {
          t: 'activity', title: 'Watch Out!', prompt: 'Какой тип атаки социальной инженерии здесь используется?',
          options: ['Pretexting', 'Quid pro quo', 'Identity fraud'],
          items: [{ q: 'Письмо якобы от Guru с ссылкой на «VPN для защиты домашнего Wi-Fi»', a: 'Pretexting' }],
          feedback: 'Атакующий попытался получить доступ к устройствам сотрудников, выдав себя за Guru — человека, которому в @Apollo доверяют, и отправив правдоподобное письмо с убедительным предлогом. Напоминание: pretexting это ложь ради доступа к привилегированным данным; quid pro quo это запрос информации в обмен на что-то; identity fraud это использование украденной личности.',
        },
      ],
    },
    {
      id: '1.2.5', title: 'Avatar', titleRu: 'Переход', kind: 'text',
      blocks: [
        { t: 'note', variant: 'avatar', md: 'Большинство кибератак включают **какую-либо форму обмана**. Рассмотрим основные.' },
      ],
    },
    {
      id: '1.2.6', title: 'Shoulder Surfing and Dumpster Diving', titleRu: 'Подглядывание и мусор', kind: 'text',
      blocks: [
        { t: 'def', term: 'Shoulder surfing', md: 'A simple attack that involves observing or literally looking over a target’s shoulder to gain valuable information such as PINs, access codes or credit card details.' },
        { t: 'p', md: 'Преступникам не обязательно быть рядом с жертвой: можно использовать **бинокль или камеры наблюдения**. Именно поэтому экран банкомата видно только под определёнными углами — такие меры сильно усложняют shoulder surfing.' },
        { t: 'def', term: 'Dumpster diving', md: 'The process of going through a target’s trash to see what information has been thrown out.' },
        { t: 'p', md: 'Поэтому документы с чувствительной информацией нужно **измельчать (shred)** или хранить в **burn bags**, пока их не уничтожат огнём через определённый срок.' },
        { t: 'figure', caption: 'Shoulder surfing — ноутбук, из экрана которого выезжает сёрфер на волне; dumpster diving — большой бак, полный денег и драгоценностей.' },
      ],
    },
    {
      id: '1.2.7', title: 'Impersonation and Hoaxes', titleRu: 'Выдача себя за другого и мистификации', kind: 'flip',
      blocks: [
        { t: 'p', md: 'У киберпреступников есть много других приёмов обмана.' },
        {
          t: 'flip', title: 'Нажми, чтобы открыть карточку',
          cards: [
            { front: 'Impersonation', back: 'The act of tricking someone into doing something they would not ordinarily do **by pretending to be someone else**. Пример: преступник под видом сотрудника IRS говорил налогоплательщикам, что они должны деньги и обязаны немедленно заплатить переводом, иначе арест. Преступники также выдают себя за жертву онлайн и публикуют посты, чтобы подорвать её репутацию.' },
            { front: 'Hoaxes', back: 'A hoax is an act intended to deceive or trick someone, and can cause **just as much disruption as an actual security breach**. Пример: сообщение о несуществующей вирусной угрозе с просьбой переслать всем знакомым. Такая мистификация вызывает лишний страх и иррациональное поведение, которое расходится через почту и соцсети.' },
          ],
        },
      ],
    },
    {
      id: '1.2.8', title: 'Piggybacking and Tailgating', titleRu: 'Проход следом', kind: 'text',
      blocks: [
        { t: 'def', term: 'Piggybacking / Tailgating', md: 'Occurs when a criminal **follows an authorized person** to gain physical entry into a secure location or a restricted area.' },
        { t: 'h', text: 'Как этого добиваются' },
        { t: 'list', items: [
          'Создавая вид, что их сопровождает авторизованный человек.',
          'Присоединяясь к большой толпе, входящей в здание, и притворяясь её частью.',
          'Выбирая авторизованного человека, который небрежно относится к правилам.',
        ] },
        { t: 'note', variant: 'tip', title: 'Защита', md: 'Один из способов предотвращения — **две двери подряд**. Это называется **mantrap**: человек входит через внешнюю дверь, она должна закрыться, прежде чем откроется внутренняя.' },
      ],
    },
    {
      id: '1.2.9', title: 'Other Methods of Deception', titleRu: 'Другие методы обмана', kind: 'accordion',
      blocks: [
        { t: 'p', md: 'У атакующих в рукаве ещё много трюков.' },
        {
          t: 'accordion', title: '5 методов',
          items: [
            { title: 'Invoice scam', md: 'Fake invoices are sent with the goal of receiving money from a victim by prompting them to put their credentials into **a fake login screen**. Поддельный счёт может содержать срочные или угрожающие формулировки.' },
            { title: 'Watering hole attack', md: 'An exploit in which an attacker **observes or guesses what websites an organization uses most often**, and infects one or more of them with malware.' },
            { title: 'Typosquatting', md: 'Relies on common mistakes such as **typos** made when inputting a website address. Неверный URL приводит на похожий на легитимный сайт, принадлежащий атакующему, цель которого собрать личные или финансовые данные.' },
            { title: 'Prepending', md: 'Attackers can **remove the «external» email tag** used by organizations to warn the recipient that an email came from an external source. Это заставляет думать, что вредоносное письмо пришло изнутри организации.' },
            { title: 'Influence campaigns', md: 'Часто применяются в **кибервойне**, обычно очень хорошо скоординированы и смешивают методы: **fake news, disinformation campaigns and social media posts**.' },
          ],
        },
      ],
    },
    {
      id: '1.2.10', title: 'Spot the Attack', titleRu: 'Распознай атаку', kind: 'activity',
      blocks: [
        { t: 'p', md: 'В @Apollo произошло несколько необычных инцидентов, есть опасения, что организацию атакуют.' },
        {
          t: 'activity', title: 'Spot the Attack', prompt: 'Определи тип атаки в каждом случае.',
          options: ['Typosquatting', 'Impersonation', 'Tailgating'],
          items: [
            { q: 'Друг пишет и поздравляет с новой должностью в @Apollo, увидев обновление статуса в твоём профиле. Ты этого не публиковал.', a: 'Impersonation' },
            { q: 'Коллега рассказал, что утром мужчина попросил придержать входную дверь, потому что забыл ID-карту. Коллега этого человека раньше не видел.', a: 'Tailgating' },
            { q: 'Клиентка сообщила, что её компьютер заразился malware после посещения сайта @Apollo. Расследование показало, что она случайно ошиблась в адресе сайта.', a: 'Typosquatting' },
          ],
          feedback: 'Киберпреступники часто выдают себя за других и публикуют посты на их страницах, чтобы получить личную информацию или подорвать репутацию. Tailgating срабатывает через авторизованного человека, небрежного к правилам входа. Typosquatting нацелен на тех, кто неверно вводит адрес сайта.',
        },
      ],
    },
    {
      id: '1.2.11', title: 'Defending Against Deception', titleRu: 'Защита от обмана', kind: 'text',
      blocks: [
        { t: 'p', md: 'Организациям нужно продвигать осведомлённость о тактиках социальной инженерии и правильно обучать сотрудников мерам предотвращения.' },
        { t: 'list', items: [
          'Never disclose confidential information or credentials via email, chat, text messages, in person or over the phone to unknown parties.',
          'Resist the urge to click on enticing emails and web links.',
          'Be wary of uninitiated or automatic downloads.',
          'Establish and educate employees on key security policies.',
          'Encourage employees to take ownership of security issues.',
          'Do not give in to pressure by unknown individuals.',
        ] },
        { t: 'figure', caption: 'Анимация: появляются четыре открытых замка, вокруг них пунктиром складываются шестиугольники, после чего замки закрываются.' },
      ],
    },
    {
      id: '1.2.12', title: 'Explore Social Engineering Techniques (video)', titleRu: 'Видео к лабораторной', kind: 'video',
      blocks: [
        { t: 'p', md: 'Короткое демо-видео (~1:00) с обзором лабораторной работы.' },
        {
          t: 'transcript', title: 'Транскрипт видео',
          lines: [
            { time: '00:00', text: 'This video is an overview of the lab for social engineering techniques.' },
            { time: '00:05', text: 'This lab requires a PC or some other device with internet access.' },
            { time: '00:09', text: 'Not all cybersecurity attacks come from some random attacker who is breaking into a network from a computer that is thousands of miles away.' },
            { time: '00:17', text: 'Many times, attackers steal personal or organizational information that they acquired by getting someone to unknowingly give them access.' },
            { time: '00:25', text: 'This is called social engineering, and it happens more often than you might think.' },
            { time: '00:31', text: 'These are the objectives of this lab.' },
            { time: '00:33', text: 'In part one, you will learn about the different types of social engineering techniques that are used to gain access to personal or organizational data. You will view an interactive lesson about social engineering and answer questions.' },
            { time: '00:47', text: 'In part two, you will create a cybersecurity awareness poster to encourage others to be aware of social engineering attacks.' },
            { time: '00:56', text: 'We hope you enjoy this lab.' },
          ],
        },
      ],
    },
    {
      id: '1.2.13', title: 'Lab — Explore Social Engineering Techniques', titleRu: 'Лабораторная работа', kind: 'lab',
      blocks: [
        { t: 'h', text: 'Objectives' },
        { t: 'list', items: ['**Part 1:** Explore Social Engineering Techniques', '**Part 2:** Create a Cybersecurity Awareness Poster'] },
        { t: 'p', md: 'Требуемые ресурсы: PC или мобильное устройство с доступом в интернет.' },
        { t: 'p', md: 'Кибербезопасность критична, потому что защищает от несанкционированного доступа к чувствительным данным: **PII, PHI, personal information, intellectual property (IP)** и чувствительным системам. Social engineering это широкий набор вредоносных действий через психологическую манипуляцию людьми. Иногда это называют **human hacking**.' },
        { t: 'p', md: 'Атаки социальной инженерии очень эффективны, потому что люди хотят доверять другим людям, и от такой атаки средний пользователь не защищается: он думает про ботнеты, кражу личности и ransomware, то есть про большие внешние угрозы, и не подвергает сомнению легитимно выглядящее сообщение.' },
        {
          t: 'accordion', title: 'Техники из фона лабораторной',
          items: [
            { title: 'Baiting', md: 'Relies on the **curiosity or greed** of the victim. От других техник отличает **обещание предмета или блага**. Например, бесплатная музыка или фильмы в обмен на учётные данные. Не ограничено онлайном: атакующие эксплуатируют любопытство и через физические носители, например USB-флешки.' },
            { title: 'Shoulder surfing', md: 'Буквально заглядывание через плечо. Эффективно в людных местах: легко встать рядом и смотреть, как человек заполняет форму или вводит PIN в банкомате. Возможно и на расстоянии с помощью телефона, бинокля или других оптических устройств. Защита: прикрывать бумаги и клавиатуру телом или ладонью, использовать экранные шторки.' },
            { title: 'Pretexting', md: 'Использование обмана для создания сценария, который убедит жертву раскрыть то, что раскрывать нельзя. Часто применяется против организаций, хранящих клиентские данные: финансовые данные, номера карт, номера коммунальных счетов. Претекстеры запрашивают информацию, выдавая себя за **supervisor, helpdesk clerk или клиента**, обычно по телефону, почте или в сообщениях.' },
            { title: 'Phishing, spear phishing, whaling', md: 'В phishing атакующие пытаются получить личную информацию или данные (username, password, credit card details), **маскируясь под доверенные сущности**. В основном через email и телефонные звонки. **Spear phishing** это более целевая версия: атакующий выбирает конкретных людей или предприятия и кастомизирует атаку. **Whaling** это когда цель — высокопоставленный сотрудник, например CEO или CFO.' },
            { title: 'Scareware and ransomware', md: '**Ransomware** внедряет malware, шифрующее критичные данные жертвы. Преступники требуют выкуп за расшифровку, но даже при оплате нет гарантии. Это один из самых быстрорастущих типов атак, пострадали тысячи финансовых организаций, госагентств, медучреждений и школ. **Scareware** пользуется страхом пользователя и склоняет его установить поддельный антивирус.' },
            { title: 'Tailgating', md: 'Обманом заставляет жертву помочь атакующему попасть в физические помещения организации. Атакующий стремится в закрытую зону, где доступ контролируют электронные устройства или охрана. Может выражаться в том, что атакующий идёт вплотную за сотрудником и проходит через дверь до того, как она закроется.' },
            { title: 'Dumpster diving', md: 'Техника извлечения выброшенной информации из мусора для атаки на человека или организацию. Не ограничивается поиском явных сокровищ вроде кодов доступа или паролей на стикерах: сюда же входит электронная информация, оставленная на рабочих столах или хранящаяся на USB-накопителях.' },
          ],
        },
      ],
    },
    {
      id: '1.2.L', title: 'Lab answers (Part 1 and Part 2)', titleRu: 'Ответы лабораторной', kind: 'lab',
      blocks: [
        { t: 'p', md: 'CSSIA хостит интерактив Social Engineering Interactive. Актуальная ссылка курса: `https://www.caeepnc.org/social_engineering/`. Если ссылка изменится, искать «CSSIA Social Engineering Interactive».' },
        { t: 'h', text: 'Step 1: Baiting, Shoulder Surfing, Pretexting' },
        { t: 'table', headers: ['Вопрос', 'Официальный ответ'], rows: [
          ['**1. What is baiting? Did you click on the USB drive? What happened to the victim’s system?**', 'Baiting is using a false promise to gain a victim’s interest to lure them into a trap that steals their personal information or infects their systems with malware. Yes — the system is compromised by malware.'],
          ['**2. What is shoulder surfing? What device was used? What information was gained?**', 'Shoulder surfing is looking over someone’s shoulder while they are using a computer and visually capturing logins or passwords or other sensitive information. A cell phone. Login and password information.'],
          ['**3. What is pretexting? What type of information did the cybercriminal request?**', 'Pretexting is when an attacker establishes trust with their victim by impersonating persons who have right-to-know authority and asking questions that appear to be required to confirm the victim’s identity, but through which they gather important personal data. Information requested: name, work role, etc.'],
        ] },
        { t: 'h', text: 'Step 2: Phishing, Spear Phishing, Whaling' },
        { t: 'table', headers: ['Вопрос', 'Официальный ответ'], rows: [
          ['**4. What is the ploy the attacker uses, and what is the trap website for?**', 'The phishing scheme sends a fake notice that the victim has recently attempted to withdraw funds from their account while in another country: **$174.99**. The scheme is designed to steal the victim credentials including username and password.'],
          ['**5. Difference between phishing, spear phishing and whaling?**', 'Spear phishing is a more targeted version of phishing, in which an attacker chooses specific individuals or enterprises and customizes the attack to make it less conspicuous. Whaling is when the specific target is a high-profile employee such as a CEO or CFO.'],
        ] },
        { t: 'h', text: 'Step 3: Scareware and Ransomware' },
        { t: 'table', headers: ['Вопрос', 'Официальный ответ'], rows: [
          ['**6. What data does the attacker claim to have?**', 'Facebook Login; Credit Card Details; Email Account Login. Нет, зная, что такое scareware, не звонят на неизвестный номер и не делятся данными аккаунта.'],
          ['**7. What is the attacker requesting the victim do?**', '«Please call the attacker within the next 5 minutes to prevent your computer from being disabled. Call: 44-8000-903-274.»'],
          ['**8. What is tailgating?**', 'Tailgating is when an attacker who lacks the proper authorization follows a victim with authorized credentials through a door or other secure building access point into a restricted area.'],
        ] },
        { t: 'h', text: '9. Three ways to prevent social engineering attacks' },
        { t: 'list', ordered: true, items: [
          '**Think before you act** — never share personal information over the phone, email, or on unsecure websites. Do not click on links, download files, or open email attachments from unknown senders.',
          '**Stay aware of your surroundings** — be skeptical of links to web forms that request personal information, even if the email appears to come from a legitimate source. Never click on or enter sensitive information into a pop-up.',
          '**Keep your accounts and devices safe** — use antivirus software and spam filters, and update and patch your devices regularly.',
        ] },
        { t: 'h', text: 'Part 2. Create a Cybersecurity Awareness Poster' },
        { t: 'p', md: 'Сделать в PowerPoint плакат об одной из техник: **Baiting, Shoulder Surfing, Pretexting, Phishing, Scareware, Ransomware, Tailgating, Dumpster Diving**. Плакат должен показывать саму технику и то, как пользователи могут её избежать, а также содержать указание, где именно в организации его разместить.' },
        { t: 'note', variant: 'info', title: 'Next up', md: 'Киберпреступники атакуют устройства пользователей через установку malware. Далее раздел **1.3 Cyber Attacks**.' },
      ],
    },
    {
      id: '1.2.G', title: 'Glossary of module 1.2', titleRu: 'Глоссарий 1.2', kind: 'glossary',
      blocks: [
        { t: 'table', headers: ['Термин', 'Краткое определение'], rows: [
          ['Social engineering', 'Нетехническая стратегия манипуляции людьми ради действий или конфиденциальной информации'],
          ['Pretexting', 'Ложь или выдуманный сценарий ради доступа к привилегированным данным'],
          ['Quid pro quo', 'Запрос личной информации в обмен на что-то: подарок, приз'],
          ['Identity fraud', 'Использование украденной личности для получения товаров или услуг'],
          ['Authority', 'Давление через мнимый авторитет'],
          ['Intimidation', 'Запугивание жертвы'],
          ['Consensus / social proof', 'Давление через «все так делают»'],
          ['Scarcity', 'Давление через ограниченное количество'],
          ['Urgency', 'Давление через ограниченное время'],
          ['Familiarity', 'Построение симпатии или подмена профиля знакомого'],
          ['Trust', 'Долгая игра на доверии, например «эксперт по безопасности»'],
          ['Shoulder surfing', 'Подглядывание через плечо: PIN, коды, карты'],
          ['Dumpster diving', 'Поиск информации в мусоре цели'],
          ['Impersonation', 'Выдача себя за другого человека'],
          ['Hoax', 'Обманное сообщение или ложная тревога'],
          ['Piggybacking / Tailgating', 'Проход в закрытую зону следом за авторизованным человеком'],
          ['Mantrap', 'Шлюз из двух дверей как защита от tailgating'],
          ['Invoice scam', 'Поддельные счета с уводом на фейковый логин'],
          ['Watering hole attack', 'Заражение сайтов, которыми часто пользуется организация'],
          ['Typosquatting', 'Эксплуатация опечаток в адресе сайта'],
          ['Prepending', 'Удаление метки external у письма'],
          ['Influence campaigns', 'Скоординированные кампании влияния: фейки и дезинформация'],
          ['Baiting', 'Приманка: бесплатный контент, подброшенная USB-флешка'],
          ['Phishing', 'Массовая рассылка под видом доверенного отправителя'],
          ['Spear phishing', 'Целевой фишинг под конкретного человека или компанию'],
          ['Whaling', 'Фишинг против топ-менеджеров: CEO, CFO'],
          ['Scareware', 'Запугивание мнимым заражением ради установки фейкового ПО'],
          ['Ransomware', 'Шифрование данных с требованием выкупа'],
        ] },
      ],
    },
  ],
  atoms: [
    { id: '1.2-s0', lesson: '1.2.1', kind: 'term', group: 'se-types', groupLabel: '3 типа атак SE', weight: 3,
      term: 'Social engineering', definition: 'A non-technical strategy that attempts to manipulate individuals into performing certain actions or divulging confidential information, exploiting human nature rather than software or hardware vulnerabilities.',
      cloze: '___ is a non-technical strategy that manipulates people into performing actions or divulging confidential information.',
      ru: 'Манипуляция людьми вместо взлома техники.' },
    { id: '1.2-s1', lesson: '1.2.1', kind: 'term', group: 'se-types', groupLabel: '3 типа атак SE', weight: 3,
      term: 'Pretexting', definition: 'An attack that occurs when an individual lies to gain access to privileged data, for example pretending to need personal or financial data in order to confirm a person’s identity.',
      cloze: '___ occurs when an individual lies to gain access to privileged data.',
      ru: 'Ложь или выдуманный предлог ради привилегированных данных.' },
    { id: '1.2-s2', lesson: '1.2.1', kind: 'term', group: 'se-types', groupLabel: '3 типа атак SE', weight: 3,
      term: 'Quid pro quo', definition: 'An attack that involves a request for personal information in exchange for something, like a gift or a free vacation.',
      cloze: 'A ___ attack requests personal information in exchange for something, like a gift.', aliases: ['something for something', 'quid pro quo'],
      ru: 'Личные данные в обмен на подарок или приз.' },
    { id: '1.2-s3', lesson: '1.2.1', kind: 'term', group: 'se-types', groupLabel: '3 типа атак SE', weight: 3,
      term: 'Identity fraud', definition: 'The use of a person’s stolen identity to obtain goods or services by deception, for example issuing a credit card in someone else’s name.',
      cloze: '___ is the use of a person’s stolen identity to obtain goods or services by deception.',
      ru: 'Использование украденной личности ради товаров или услуг.' },

    { id: '1.2-t1', lesson: '1.2.2', kind: 'term', group: 'se-tactics', groupLabel: '7 тактик SE', weight: 3,
      term: 'Authority', definition: 'Attackers prey on the fact that people are more likely to comply when instructed by someone they perceive as an authority figure.',
      ru: 'Давление авторитетом. Пример: заражённый PDF под видом официальной повестки.' },
    { id: '1.2-t2', lesson: '1.2.2', kind: 'term', group: 'se-tactics', groupLabel: '7 тактик SE', weight: 3,
      term: 'Intimidation', definition: 'Cybercriminals bully a victim into taking an action that compromises security.',
      ru: 'Запугивание. Пример: угроза увольнением, чтобы секретарь срочно прислал файлы.' },
    { id: '1.2-t3', lesson: '1.2.2', kind: 'term', group: 'se-tactics', groupLabel: '7 тактик SE', weight: 3,
      term: 'Consensus', definition: 'Often called social proof: people tend to act in the same way as other people around them, thinking that something must be right if others are doing it.',
      aliases: ['social proof', 'consensus'], ru: 'Социальное доказательство: «все так делают».' },
    { id: '1.2-t4', lesson: '1.2.2', kind: 'term', group: 'se-tactics', groupLabel: '7 тактик SE', weight: 3,
      term: 'Scarcity', definition: 'Attackers know that people tend to act when they think there is a limited quantity of something available.',
      cloze: '___ works because people act when they think there is a limited quantity available.',
      ru: 'Ограниченное количество.' },
    { id: '1.2-t5', lesson: '1.2.2', kind: 'term', group: 'se-tactics', groupLabel: '7 тактик SE', weight: 3,
      term: 'Urgency', definition: 'People tend to act when they think there is a limited time to do so, for example a fake time-limited shipping offer.',
      cloze: '___ works because people act when they think there is a limited time to do so.',
      ru: 'Ограниченное время.' },
    { id: '1.2-t6', lesson: '1.2.2', kind: 'term', group: 'se-tactics', groupLabel: '7 тактик SE', weight: 3,
      term: 'Familiarity', definition: 'People are more likely to do what another person asks if they like this person, so attackers build rapport or clone the social media profile of a friend.',
      ru: 'Симпатия и клонирование профиля знакомого.' },
    { id: '1.2-t7', lesson: '1.2.2', kind: 'term', group: 'se-tactics', groupLabel: '7 тактик SE', weight: 3,
      term: 'Trust', definition: 'Building trust in a relationship with a victim may require more time; for example a criminal disguised as a security expert discovers a serious error that needs immediate attention.',
      ru: 'Долгая игра на доверии, например «эксперт по безопасности».' },
    { id: '1.2-t8', lesson: '1.2.2', kind: 'enum', group: 'se-tactics-enum', groupLabel: 'Список тактик', weight: 3,
      term: 'The 7 social engineering tactics', definition: 'Authority, intimidation, consensus, scarcity, urgency, familiarity, trust.',
      items: ['Authority', 'Intimidation', 'Consensus', 'Scarcity', 'Urgency', 'Familiarity', 'Trust'],
      decoys: ['Baiting', 'Tailgating', 'Prepending', 'Hoax'],
      ru: 'Семь тактик.' },
    { id: '1.2-d1', lesson: '1.2.6', kind: 'term', group: 'deception-methods', groupLabel: 'Методы обмана', weight: 3,
      term: 'Shoulder surfing', definition: 'Observing or literally looking over a target’s shoulder to gain valuable information such as PINs, access codes or credit card details; it can also be done from a distance with binoculars or security cameras.',
      cloze: '___ means observing a target’s screen or keypad to capture PINs, access codes or card details.',
      ru: 'Подглядывание через плечо, в том числе издалека через бинокль или камеру.' },
    { id: '1.2-d2', lesson: '1.2.6', kind: 'term', group: 'deception-methods', groupLabel: 'Методы обмана', weight: 3,
      term: 'Dumpster diving', definition: 'The process of going through a target’s trash to see what information has been thrown out; prevented by shredding documents or using burn bags.',
      cloze: '___ is the process of going through a target’s trash to find information.',
      ru: 'Поиск информации в мусоре. Защита: шредер и burn bags.' },
    { id: '1.2-d3', lesson: '1.2.7', kind: 'term', group: 'deception-methods', groupLabel: 'Методы обмана', weight: 3,
      term: 'Impersonation', definition: 'The act of tricking someone into doing something they would not ordinarily do by pretending to be someone else.',
      cloze: '___ is tricking someone by pretending to be someone else.',
      ru: 'Выдача себя за другого. Пример: мнимый сотрудник IRS требует срочный перевод.' },
    { id: '1.2-d4', lesson: '1.2.7', kind: 'term', group: 'deception-methods', groupLabel: 'Методы обмана', weight: 3,
      term: 'Hoax', definition: 'An act intended to deceive or trick someone, which can cause just as much disruption as an actual security breach, for example a warning about a non-existent virus threat.',
      cloze: 'A ___ can cause just as much disruption as an actual security breach.',
      ru: 'Мистификация, ложная тревога. Вызывает страх и иррациональное поведение.' },
    { id: '1.2-d5', lesson: '1.2.8', kind: 'term', group: 'deception-methods', groupLabel: 'Методы обмана', weight: 3,
      term: 'Tailgating', definition: 'Occurs when a criminal follows an authorized person to gain physical entry into a secure location or a restricted area.',
      cloze: '___ occurs when a criminal follows an authorized person into a restricted area.', aliases: ['piggybacking', 'tailgating'],
      ru: 'Проход следом за авторизованным человеком.' },
    { id: '1.2-d6', lesson: '1.2.8', kind: 'term', group: 'deception-methods', groupLabel: 'Методы обмана', weight: 3,
      term: 'Mantrap', definition: 'Two sets of doors where individuals enter through an outer door which must close before they can gain access through an inner door; used to prevent tailgating.',
      cloze: 'Two sets of doors used to prevent tailgating are called a ___.',
      ru: 'Шлюз из двух дверей против tailgating.' },
    { id: '1.2-d7', lesson: '1.2.8', kind: 'enum', group: 'tailgating-how', groupLabel: 'Как проходят следом', weight: 2,
      term: 'How criminals achieve tailgating', definition: 'By appearing to be escorted into the facility by an authorized person; by joining and pretending to be part of a large crowd; by targeting an authorized person who is careless about the rules.',
      items: ['Giving the appearance of being escorted by an authorized person', 'Joining and pretending to be part of a large crowd', 'Targeting an authorized person who is careless about the rules'],
      decoys: ['Guessing the door code', 'Cutting the power to the lock', 'Cloning an ID card'],
      ru: 'Три способа из курса.' },
    { id: '1.2-o1', lesson: '1.2.9', kind: 'term', group: 'other-deception', groupLabel: 'Другие методы', weight: 3,
      term: 'Invoice scam', definition: 'Fake invoices sent with the goal of receiving money from a victim by prompting them to put their credentials into a fake login screen, often with urgent or threatening language.',
      ru: 'Поддельный счёт и фейковый экран логина.' },
    { id: '1.2-o2', lesson: '1.2.9', kind: 'term', group: 'other-deception', groupLabel: 'Другие методы', weight: 3,
      term: 'Watering hole attack', definition: 'An exploit in which an attacker observes or guesses what websites an organization uses most often, and infects one or more of them with malware.',
      cloze: 'In a ___ the attacker infects websites the organization visits most often.',
      ru: 'Заражение любимых сайтов организации.' },
    { id: '1.2-o3', lesson: '1.2.9', kind: 'term', group: 'other-deception', groupLabel: 'Другие методы', weight: 3,
      term: 'Typosquatting', definition: 'An attack that relies on typos made when inputting a website address; the incorrect URL leads to a legitimate-looking website owned by the attacker.',
      cloze: '___ relies on typos made when entering a website address into the browser.',
      ru: 'Ловля опечаток в адресе сайта.' },
    { id: '1.2-o4', lesson: '1.2.9', kind: 'term', group: 'other-deception', groupLabel: 'Другие методы', weight: 3,
      term: 'Prepending', definition: 'Attackers remove the «external» email tag used by organizations to warn the recipient that an email originated from an external source, so the malicious email looks internal.',
      cloze: '___ removes the external tag from an email so it looks like it came from inside the organization.',
      ru: 'Снятие метки external с письма.' },
    { id: '1.2-o5', lesson: '1.2.9', kind: 'term', group: 'other-deception', groupLabel: 'Другие методы', weight: 3,
      term: 'Influence campaigns', definition: 'Well coordinated campaigns often used in cyberwarfare that blend fake news, disinformation campaigns and social media posts.',
      ru: 'Кампании влияния в кибервойне.' },
    { id: '1.2-l1', lesson: '1.2.13', kind: 'term', group: 'lab-techniques', groupLabel: 'Техники из лабораторной', weight: 3,
      term: 'Baiting', definition: 'Using a false promise of an item or good to gain a victim’s interest and lure them into a trap that steals their personal information or infects their systems with malware; it relies on curiosity or greed and also works with physical media such as USB drives.',
      cloze: '___ uses a false promise of an item or good to lure a victim into a trap.',
      ru: 'Приманка: бесплатный контент или подброшенная флешка.' },
    { id: '1.2-l2', lesson: '1.2.13', kind: 'term', group: 'phishing-family', groupLabel: 'Семейство phishing', weight: 3,
      term: 'Phishing', definition: 'Attackers try to obtain personal information or data such as username, password and credit card details by disguising themselves as trustworthy entities, mainly through emails and phone calls.',
      cloze: 'In ___ attackers disguise themselves as trustworthy entities to obtain credentials.',
      ru: 'Массовая рассылка под видом доверенного отправителя.' },
    { id: '1.2-l3', lesson: '1.2.13', kind: 'term', group: 'phishing-family', groupLabel: 'Семейство phishing', weight: 3,
      term: 'Spear phishing', definition: 'A more targeted version of phishing in which an attacker chooses specific individuals or enterprises and customizes the attack to the victims to make it less conspicuous.',
      cloze: '___ is a targeted phishing attack customized for specific individuals or enterprises.',
      ru: 'Целевой фишинг под конкретного человека или компанию.' },
    { id: '1.2-l4', lesson: '1.2.13', kind: 'term', group: 'phishing-family', groupLabel: 'Семейство phishing', weight: 3,
      term: 'Whaling', definition: 'A phishing attack where the specific target is a high-profile employee such as a CEO or CFO.',
      cloze: '___ targets a high-profile employee such as a CEO or CFO.',
      ru: 'Фишинг против топ-менеджмента.' },
    { id: '1.2-l5', lesson: '1.2.13', kind: 'term', group: 'lab-techniques', groupLabel: 'Техники из лабораторной', weight: 3,
      term: 'Ransomware', definition: 'An attack that injects malware which encrypts a victim’s critical data; the criminals request a ransom to decrypt it, and even if the ransom is paid there is no guarantee the data will be decrypted.',
      cloze: '___ encrypts the victim’s critical data and demands a ransom.',
      ru: 'Шифрование данных с требованием выкупа. Гарантий расшифровки нет.' },
    { id: '1.2-l6', lesson: '1.2.13', kind: 'term', group: 'lab-techniques', groupLabel: 'Техники из лабораторной', weight: 3,
      term: 'Scareware', definition: 'An attack that takes advantage of a user’s fear by coaxing them into installing fake antivirus software.',
      cloze: '___ takes advantage of a user’s fear to make them install fake antivirus software.',
      ru: 'Запугивание ради установки фейкового антивируса.' },
    { id: '1.2-l7', lesson: '1.2.L', kind: 'fact', group: 'lab-facts', groupLabel: 'Детали лабораторной', weight: 2,
      term: 'The amount in the lab phishing notice', definition: 'The fake notice claims the victim attempted to withdraw $174.99 from their account while in another country.',
      cloze: 'The phishing notice in the lab claims a withdrawal attempt of ___.', clozeAnswer: '$174.99',
      decoys: ['$600', '$74.99', '$1,749'], ru: 'Сумма из фишингового уведомления: $174.99.' },
    { id: '1.2-l8', lesson: '1.2.L', kind: 'enum', group: 'lab-facts', groupLabel: 'Детали лабораторной', weight: 2,
      term: 'Data the scareware attacker claims to have', definition: 'Facebook login, credit card details and email account login.',
      items: ['Facebook Login', 'Credit Card Details', 'Email Account Login'],
      decoys: ['Bank account PIN', 'Passport scan', 'Work badge number'],
      ru: 'Три позиции из сценария scareware.' },
    { id: '1.2-l9', lesson: '1.2.11', kind: 'enum', group: 'se-defense', groupLabel: 'Защита от обмана', weight: 3,
      term: 'Top tips for defending against deception', definition: 'Never disclose confidential information or credentials to unknown parties; resist clicking enticing emails and links; be wary of automatic downloads; establish and educate employees on key security policies; encourage ownership of security issues; do not give in to pressure by unknown individuals.',
      items: ['Never disclose confidential information or credentials to unknown parties', 'Resist the urge to click on enticing emails and web links', 'Be wary of uninitiated or automatic downloads', 'Establish and educate employees on key security policies', 'Encourage employees to take ownership of security issues', 'Do not give in to pressure by unknown individuals'],
      decoys: ['Share passwords only with your manager', 'Disable the antivirus while travelling', 'Reply to every external email'],
      ru: 'Шесть советов курса.' },
    { id: '1.2-l10', lesson: '1.2.L', kind: 'enum', group: 'se-defense', groupLabel: 'Защита от обмана', weight: 3,
      term: 'Three ways to prevent social engineering attacks (lab answer)', definition: 'Think before you act; stay aware of your surroundings; keep your accounts and devices safe.',
      items: ['Think before you act', 'Stay aware of your surroundings', 'Keep your accounts and devices safe'],
      decoys: ['Pay the ransom quickly', 'Trust internal-looking emails', 'Reuse one strong password'],
      ru: 'Три формулировки из официального ответа.' },

    { id: '1.2-c1', lesson: '1.2.10', kind: 'bucket', bucket: 'Impersonation', group: 'spot-attack', groupLabel: 'Spot the Attack', weight: 3,
      term: 'A friend congratulates you on a status update you never posted', definition: 'Impersonation — кто-то выдал себя за тебя в соцсети.', ru: 'Чужой пост от твоего имени = impersonation.' },
    { id: '1.2-c2', lesson: '1.2.10', kind: 'bucket', bucket: 'Tailgating', group: 'spot-attack', groupLabel: 'Spot the Attack', weight: 3,
      term: 'A stranger asks a colleague to hold the front door because he forgot his ID card', definition: 'Tailgating — проход следом за авторизованным человеком.', ru: 'Придержали дверь постороннему = tailgating.' },
    { id: '1.2-c3', lesson: '1.2.10', kind: 'bucket', bucket: 'Typosquatting', group: 'spot-attack', groupLabel: 'Spot the Attack', weight: 3,
      term: 'A customer got malware after mistyping the company website address', definition: 'Typosquatting — опечатка в адресе привела на сайт атакующего.', ru: 'Опечатка в адресе = typosquatting.' },
    { id: '1.2-c4', lesson: '1.2.4', kind: 'fact', group: 'se-cases', groupLabel: 'Кейсы', weight: 3,
      term: 'The fake VPN email sent to @Apollo remote workers', definition: 'Pretexting — the attacker impersonated Guru and used a believable pretext to get employees to install malware.',
      decoys: ['Quid pro quo', 'Identity fraud', 'Watering hole attack'],
      ru: 'Ответ курса: pretexting.' },
  ],
}
