import type { Island } from '@/types'

export const island_1_3: Island = {
  id: '1.3',
  moduleId: 1,
  title: 'Cyber Attacks',
  titleRu: 'Кибератаки',
  objective: 'Explain the different types of malware and attacks used against networks and hosts.',
  icon: 'Bug',
  lessons: [
    {
      id: '1.3.1', title: "What's the Difference? (Virus / Worm / Trojan)", titleRu: 'Вирус, червь, троян', kind: 'accordion',
      blocks: [
        { t: 'def', term: 'Malware', md: 'Any code that can be used to **steal data**, **bypass access controls** or **cause harm to or compromise a system**.' },
        {
          t: 'accordion', title: 'Три классических типа вредоносного ПО',
          items: [
            { title: 'Virus', md: 'A type of computer program that, when executed, **replicates and attaches itself to other files**, such as a legitimate program, by **inserting its own code into it**.\n\n- Некоторые безвредны, другие разрушительны (изменяют или удаляют данные).\n- **Most viruses require end-user interaction** to initiate activation.\n- Can be written to act on a **specific date or time**.\n- Пути распространения: removable media (USB), Internet downloads, email attachments.\n- Триггер: простое открытие файла или запуск программы.\n- После активации заражает другие программы на компьютере или на других компьютерах сети.\n- **Viruses mutate to avoid detection.**', example: 'Melissa virus, 1999, распространялся по email, затронул десятки тысяч пользователей, ущерб около **$1.2 billion**.' },
            { title: 'Worm', md: 'A malicious software program that **replicates by independently exploiting vulnerabilities in networks**.\n\n- Unlike a virus, which requires a **host program** to run, worms **can run by themselves**.\n- Кроме первичного заражения хоста, **не требуют участия пользователя**.\n- Распространяются очень быстро по сети и обычно **замедляют её**.\n- **Три общих признака червей:** they exploit system vulnerabilities, they have a way to propagate themselves, they contain malicious code (**payload**) to cause damage.', example: 'Code Red, 2001: заразил более **300 000 серверов за 19 часов**.' },
            { title: 'Trojan horse', md: 'Malware that carries out malicious operations by **masking its true intent**. It might appear legitimate but is in fact very dangerous.\n\n- **Trojans exploit the privileges of the user who runs them.**\n- Unlike viruses, Trojans **do not self-replicate**.\n- Часто привязываются к **non-executable files** (image, audio, video), действуя как приманка (**decoy**).' },
          ],
        },
        { t: 'table', caption: 'Быстрое сравнение (это и спрашивают)', headers: ['Признак', 'Virus', 'Worm', 'Trojan horse'], rows: [
          ['Нужна host-программа', 'Да', 'Нет', 'Привязывается к неисполняемым файлам'],
          ['Нужно действие пользователя', 'Обычно да', 'Нет (кроме первого заражения)', 'Да, пользователь запускает'],
          ['Самокопирование', 'Да, в другие файлы', 'Да, через уязвимости сети', '**Нет**'],
          ['Ключевая фраза курса', 'Inserts its own code, mutates to avoid detection', 'Exploits vulnerabilities independently, slows the network', 'Masks its true intent, exploits the privileges of the user'],
        ] },
        { t: 'note', variant: 'exam', title: 'Ловушка', md: 'Вирусу нужен носитель и обычно пользователь. Червю не нужно ни то, ни другое. Троян **не самокопируется** вообще.' },
      ],
    },
    {
      id: '1.3.2', title: 'Logic Bombs', titleRu: 'Логические бомбы', kind: 'text',
      blocks: [
        { t: 'def', term: 'Logic bomb', md: 'A malicious program that **waits for a trigger**, such as a **specified date** or a **database entry**, to set off the malicious code. Until this trigger event happens, the logic bomb **remains inactive**.' },
        { t: 'h', text: 'Что делает после активации' },
        { t: 'list', items: [
          'Sabotage **database records**.',
          'Erase files.',
          'Attack operating systems or applications.',
        ] },
        { t: 'note', variant: 'warn', title: 'Атака на железо', md: 'Специалисты обнаружили логические бомбы, которые **разрушают аппаратные компоненты**: cooling fans, CPU, memory, hard drives и power supplies. Бомба **перегружает** компоненты, пока они не перегреются или не выйдут из строя.' },
      ],
    },
    {
      id: '1.3.3', title: 'Ransomware', titleRu: 'Программы-вымогатели', kind: 'text',
      blocks: [
        { t: 'def', term: 'Ransomware', md: 'Malware designed to **hold a computer system or the data it contains captive until a payment is made**.' },
        { t: 'list', items: [
          'Обычно работает через **шифрование данных**, чтобы вы не могли к ним обратиться.',
          'Выкуп платится через **untraceable payment system**, после чего преступник обещает программу-дешифратор или unlock code.',
          '**В реальности многие жертвы не получают доступ к данным даже после оплаты.**',
          'Некоторые версии используют **specific system vulnerabilities**, чтобы заблокировать систему.',
          'Пути распространения: **phishing emails** с вредоносным вложением или **software vulnerability**.',
        ] },
      ],
    },
    {
      id: '1.3.4', title: 'Denial of Service Attacks', titleRu: 'Отказ в обслуживании', kind: 'text',
      blocks: [
        { t: 'p', md: 'DoS-атаки **относительно просты в исполнении, даже для неопытного атакующего**. Это серьёзный риск: они обычно приводят к прерыванию сетевых сервисов и значительной потере времени и денег.' },
        { t: 'note', variant: 'info', md: 'Даже **operational technologies** (оборудование и ПО, управляющее физическими устройствами или процессами в зданиях, на заводах, у коммунальных провайдеров) уязвимы к DoS, в крайних случаях вплоть до полной остановки (**shutdown**).' },
        { t: 'h', text: 'Два основных типа DoS' },
        {
          t: 'accordion',
          items: [
            { title: 'Overwhelming quantity of traffic', md: 'Сети, хосту или приложению отправляется **огромный объём данных со скоростью, которую они не могут обработать**. Результат: замедление передачи или ответа, либо падение устройства или сервиса.' },
            { title: 'Maliciously formatted packets', md: '**Packet** — a collection of data that flows between a source and a receiver computer or application over a network. Когда отправлен злонамеренно сформированный пакет, **получатель не может его обработать**.\n\nПример: атакующий шлёт пакеты с ошибками или неправильно сформированные пакеты, которые приложение не может идентифицировать, и устройство-получатель начинает очень медленно работать или падает.' },
          ],
        },
      ],
    },
    {
      id: '1.3.5', title: 'DDoS', titleRu: 'Распределённый отказ в обслуживании', kind: 'text',
      blocks: [
        { t: 'def', term: 'DDoS (Distributed Denial of Service)', md: 'Похожа на DoS, но исходит **from multiple coordinated sources**.' },
        { t: 'h', text: 'Как это происходит' },
        { t: 'list', ordered: true, items: [
          'An attacker builds a network (**botnet**) of infected hosts called **zombies**, which are controlled by **handler systems**.',
          'The zombie computers constantly **scan and infect more hosts**, creating more and more zombies.',
          'When ready, the hacker will **instruct the handler systems** to make the botnet of zombies carry out a DDoS attack.',
        ] },
        { t: 'note', variant: 'exam', title: 'Цепочка', md: '**attacker → handler systems → botnet of zombies → цель**. Именно в таком порядке.' },
      ],
    },
    {
      id: '1.3.6', title: 'Domain Name System', titleRu: 'Атаки на DNS и домены', kind: 'accordion',
      blocks: [
        { t: 'p', md: 'Для работы сети нужны важнейшие технические сервисы: **routing, addressing и domain naming**. Это **prime targets for attack**.' },
        {
          t: 'accordion',
          items: [
            { title: 'DNS (что это)', md: 'The **Domain Name System** is used by DNS servers to translate a domain name, such as www.cisco.com, into a **numerical IP address** so that computers can understand it. If a DNS server **does not know an IP address, it will ask another DNS server**.' },
            { title: 'Domain reputation', md: 'An organization needs to **monitor its domain reputation**, including its IP address, to help protect against **malicious external domains**.' },
            { title: 'DNS spoofing (DNS cache poisoning)', md: 'An attack in which **false data is introduced into a DNS resolver cache** — the temporary database on a computer operating system that records recent visits to websites and other Internet domains.\n\nЭти poison-атаки эксплуатируют **слабость в ПО DNS**, из-за которой DNS-серверы **перенаправляют трафик конкретного домена на компьютер атакующего**.' },
            { title: 'Domain hijacking', md: 'When an attacker **wrongfully gains control of a target DNS information** and makes unauthorized changes to it.\n\n**The most common way** of hijacking a domain name is to **change the administrator contact email address** through social engineering or by hacking into the administrator email account. Этот адрес легко найти через **WHOIS record**, которая является публичной.' },
            { title: 'URL redirection', md: 'A **uniform resource locator (URL)** is a unique identifier for finding a specific resource on the Internet. Перенаправление URL обычно происходит в легитимных целях (например, выход из портала возвращает вас на страницу логина).\n\nИменно эту функциональность атакующие эксплуатируют: вместо страницы логина вас перенаправляют **на вредоносный сайт**.' },
          ],
        },
      ],
    },
    {
      id: '1.3.7', title: 'Layer 2 Attacks', titleRu: 'Атаки второго уровня', kind: 'text',
      blocks: [
        { t: 'def', term: 'Layer 2', md: 'The **data link layer** in the **OSI (Open Systems Interconnection)** data communication model. Этот уровень используется, чтобы двигать данные по связанной физической сети.' },
        { t: 'p', md: 'IP-адреса сопоставляются с адресом каждого физического устройства (**MAC address**, media access control) с помощью процедуры **ARP (address resolution protocol)**.' },
        { t: 'note', variant: 'tip', md: 'Проще говоря: **MAC address identifies the intended receiver** of an IP address sent over the network, а **ARP resolves IP addresses to MAC addresses** for transmitting data.' },
        { t: 'h', text: 'Spoofing (poisoning)' },
        { t: 'def', term: 'Spoofing', md: 'A type of **impersonation attack** that takes advantage of a **trusted relationship between two systems**.' },
        { t: 'table', headers: ['Вид', 'Что делает'], rows: [
          ['**MAC address spoofing**', 'Атакующий маскирует своё устройство под валидное в сети и таким образом **обходит процесс аутентификации**.'],
          ['**ARP spoofing**', 'Отправляет **поддельные ARP-сообщения по LAN**. Это привязывает MAC-адрес атакующего к IP-адресу авторизованного устройства сети.'],
          ['**IP spoofing**', 'Отправляет IP-пакеты **с подделанного адреса источника**, чтобы замаскировать его.'],
        ] },
        { t: 'h', text: 'MAC Flooding' },
        { t: 'p', md: 'Устройства в сети соединены через **network switch** с помощью packet switching. **MAC flooding** компрометирует данные, передаваемые устройству: атакующий **затапливает сеть фейковыми MAC-адресами**, компрометируя безопасность коммутатора.' },
      ],
    },
    {
      id: '1.3.8', title: 'Spot the Attack (activity)', titleRu: 'Определи атаку', kind: 'activity',
      blocks: [
        { t: 'p', md: '**Сценарий.** Несколько сотрудников @Apollo жалуются на проблемы с производительностью: приложения тормозят, появляются заметные всплывающие рекламные окна. Инструмент мониторинга сети показывает **аномальный трафик**.' },
        {
          t: 'activity', title: 'What type of attack might @Apollo be involved with?',
          prompt: 'Выбери тип атаки',
          options: ['DoS attack', 'DDoS attack', 'Layer 2 attack', 'DNS attack'],
          items: [{ q: 'Медленные приложения, всплывающая реклама, аномальный сетевой трафик', a: 'DDoS attack', why: 'Атакующий создавал botnet из zombies внутри @Apollo. Рабочие станции превращались в зомби.' }],
          feedback: 'Признаки заражения ботнетом: performance issues, программы и приложения работают неправильно, реклама всплывает на экране.',
        },
        { t: 'table', caption: 'Разбор остальных вариантов', headers: ['Вариант', 'Почему не он'], rows: [
          ['DoS attack', 'Прерывает работу сети, перегружая её данными или maliciously formatted packets, но **из одного источника**.'],
          ['DDoS attack', '**Верно.** Исходит из botnet заражённых хостов (zombies); атакующий даёт команду handler systems.'],
          ['Layer 2 attack', 'Целится в data link layer, обходя протоколы аутентификации.'],
          ['DNS attack', 'Целится в уязвимости системы доменных имён, заставляя её вести себя неожиданно.'],
        ] },
      ],
    },
    {
      id: '1.3.9', title: 'MitM and MitMo', titleRu: 'Человек посередине', kind: 'text',
      blocks: [
        { t: 'p', md: 'Атакующие могут **перехватывать или изменять связь между двумя устройствами**, чтобы украсть информацию или выдать себя за одно из устройств.' },
        { t: 'def', term: 'Man-in-the-Middle (MitM)', md: 'Happens when a cybercriminal **takes control of a device without the user knowledge**. With this level of access, an attacker can **intercept, manipulate and relay false information** between the sender and the intended destination.' },
        { t: 'def', term: 'Man-in-the-Mobile (MitMo)', md: 'A variation of man-in-the-middle used to **take control over a user mobile device**. When infected, the mobile device is instructed to **exfiltrate user-sensitive information** and send it to the attackers.' },
        { t: 'note', variant: 'exam', title: 'Пример из курса', md: '**ZeuS** — пример пакета malware с возможностями MitMo. Он позволяет атакующим **тихо перехватывать SMS двухфакторной верификации** (two-step verification), отправленные пользователям.' },
      ],
    },
    {
      id: '1.3.10', title: 'Replay attack', titleRu: 'Атака повтора', kind: 'text',
      blocks: [
        { t: 'def', term: 'Replay attack', md: 'Occurs when an attacker **captures communication between two hosts** and then **retransmits the message to the recipient**, to trick the recipient into doing what the attacker wants, thus **circumventing any authentication mechanisms**.' },
        { t: 'note', variant: 'tip', md: 'Отличие от MitM: при replay атакующий не обязан контролировать устройство и менять содержимое, он просто **переотправляет** уже перехваченное сообщение.' },
      ],
    },
    {
      id: '1.3.11', title: 'Zero-Day Attacks', titleRu: 'Атаки нулевого дня', kind: 'text',
      blocks: [
        { t: 'def', term: 'Zero-day attack (zero-day threat)', md: 'Exploits software vulnerabilities **before they become known or before they are disclosed by the software vendor**.' },
        { t: 'p', md: 'Сеть крайне уязвима в промежутке между моментом обнаружения эксплойта (**zero hour**) и моментом, когда вендор разработает и выпустит **патч**.' },
        { t: 'p', md: 'Защита от таких быстрых атак требует от специалистов более **sophisticated and holistic view** на архитектуру сети.' },
      ],
    },
    {
      id: '1.3.12', title: 'Keyboard Logging', titleRu: 'Кейлоггинг', kind: 'text',
      blocks: [
        { t: 'def', term: 'Keyboard logging (keylogging)', md: '**Recording or logging every key struck on a computer keyboard.**' },
        { t: 'list', items: [
          'Два способа: **software installed on a computer system** или **hardware devices physically attached to a computer**.',
          'ПО настраивается так, чтобы **отправлять лог-файл преступнику**.',
          'Лог может раскрыть **usernames, passwords, websites visited** и другую чувствительную информацию.',
          'Противодействие: **many anti-spyware suites can detect and remove unauthorized key loggers**.',
        ] },
      ],
    },
    {
      id: '1.3.13', title: 'Legitimate keylogging', titleRu: 'Легальное применение', kind: 'text',
      blocks: [
        { t: 'note', variant: 'info', md: 'Важно: keylogging software **can be legitimate**. Many parents use it to keep an eye on their children internet behavior.' },
      ],
    },
    {
      id: '1.3.14', title: 'Confirm Your Details (activity)', titleRu: 'Подтверди свои данные', kind: 'activity',
      blocks: [
        { t: 'p', md: '**Сценарий.** Письмо якобы от HR-отдела @Apollo просит добавить банковские реквизиты, перейдя по ссылке, и подчёркивает, что сделать это надо **до конца дня**, иначе вы не попадёте в выплаты этого месяца. Письмо выглядит внутренним, но при внимательном осмотре **домен отправителя слегка отличается**.' },
        {
          t: 'activity', title: 'Жертвой какой атаки вы можете быть?',
          prompt: 'Выбери тип атаки',
          options: ['Impersonation', 'Man-in-the-middle', 'Domain hijacking', 'Trojan horse'],
          items: [{ q: 'Письмо со слегка изменённым доменом отправителя требует срочно ввести банковские данные', a: 'Impersonation', why: 'Преступник использовал spoofed email, чтобы обманом заставить раскрыть личные данные.' }],
          feedback: 'Spoofed emails могут выглядеть как настоящие, но переход по ссылке может скачать вирусы или увести на вредоносный сайт.',
        },
        { t: 'h', text: 'Четыре признака, на которые надо смотреть всегда' },
        { t: 'list', items: [
          'The **sender email domain**.',
          'The **URL of the link**.',
          'The **language, spelling and grammar**.',
          'The **graphics**.',
        ] },
        { t: 'table', caption: 'Разбор вариантов', headers: ['Вариант', 'Определение курса'], rows: [
          ['**Impersonation**', 'The act of **tricking someone into divulging their personal information by pretending to be someone else**.'],
          ['Man-in-the-middle', 'Преступник берёт контроль над устройством без ведома цели, чтобы перехватывать, изменять и ретранслировать ложную информацию.'],
          ['Domain hijacking', 'Атакующий незаконно получает контроль над DNS-информацией цели и вносит несанкционированные изменения.'],
          ['Trojan horse', 'Malware, привязывающийся к неисполняемым файлам (image, audio, video) как приманка.'],
        ] },
      ],
    },
    {
      id: '1.3.15', title: 'Defending Against Attacks', titleRu: 'Защита от атак', kind: 'text',
      blocks: [
        { t: 'h', text: 'Четыре меры из курса' },
        { t: 'list', ordered: true, items: [
          '**Configure firewalls** to remove any packets from outside the network that have addresses indicating that they originated from inside the network. (Это защита от **IP spoofing**.)',
          'Ensure **patches and upgrades are current**.',
          '**Distribute the workload** across server systems.',
          'Block external **ICMP packets** with firewalls to prevent **DoS and DDoS attacks**.',
        ] },
        { t: 'def', term: 'ICMP', md: '**Internet Control Message Protocol**. Network devices use ICMP packets to send **error and control messages**, such as whether or not a device can communicate with another on the network.' },
      ],
    },
    {
      id: '1.3.S', title: 'Summary table', titleRu: 'Итоговая таблица 1.3', kind: 'summary',
      blocks: [
        { t: 'table', headers: ['Атака', 'Суть', 'Отличительный признак'], rows: [
          ['Virus', 'Код, встраивающийся в другие файлы при запуске', 'Нужен файл-носитель и обычно действие пользователя, мутирует'],
          ['Worm', 'Самостоятельная программа', 'Не нужен host и пользователь, размножается через уязвимости сети'],
          ['Trojan horse', 'Вредонос под видом легитимного', 'Не самокопируется, использует права запустившего'],
          ['Logic bomb', 'Спящий вредонос, ждёт триггер', 'Может выводить из строя железо'],
          ['Ransomware', 'Шифрует данные и требует выкуп', 'Оплата часто не возвращает доступ'],
          ['DoS', 'Отказ в обслуживании из одного источника', 'Объём трафика или maliciously formatted packets'],
          ['DDoS', 'То же из множества источников', 'Botnet, zombies, handler systems'],
          ['DNS spoofing', 'Ложные данные в кеше DNS-резолвера', 'Трафик уводится на машину атакующего'],
          ['Domain hijacking', 'Захват контроля над DNS-записями', 'Через смену email администратора, WHOIS'],
          ['URL redirection', 'Подмена редиректа', 'Вместо логина уводит на вредоносный сайт'],
          ['MAC spoofing', 'Устройство выдаёт себя за валидное', 'Обход аутентификации на L2'],
          ['ARP spoofing', 'Поддельные ARP-сообщения в LAN', 'MAC атакующего привязан к IP авторизованного устройства'],
          ['IP spoofing', 'Подделка адреса источника', 'Маскировка источника'],
          ['MAC flooding', 'Затопление фейковыми MAC', 'Компрометация коммутатора'],
          ['MitM', 'Контроль над устройством без ведома', 'Перехват и подмена данных между сторонами'],
          ['MitMo', 'MitM для мобильных', 'ZeuS, перехват SMS двухфакторки'],
          ['Replay attack', 'Повторная отправка перехваченного сообщения', 'Обход аутентификации'],
          ['Zero-day', 'Эксплуатация до выхода патча', 'Окно zero hour до patch'],
          ['Keylogging', 'Запись нажатий клавиш', 'Софт или железо, бывает легальным'],
          ['Impersonation', 'Выдача себя за другого', 'Спуфленное письмо, почти правильный домен'],
        ] },
        { t: 'table', caption: 'Ключи к вопросам раздела', headers: ['Вопрос', 'Ответ'], rows: [
          ['1.3.8 Spot the Attack', '**DDoS attack**'],
          ['1.3.14 Confirm Your Details', '**Impersonation**'],
        ] },
      ],
    },
  ],
  atoms: [
    /* --- malware --- */
    { id: '1.3-m0', lesson: '1.3.1', kind: 'term', group: 'malware', groupLabel: 'Типы вредоносного ПО', weight: 3,
      term: 'Malware', definition: 'Any code that can be used to steal data, bypass access controls, or cause harm to or compromise a system.',
      cloze: '___ is any code that can be used to steal data, bypass access controls or cause harm to a system.',
      ru: 'Любой код для кражи данных, обхода контроля доступа или вреда системе.' },
    { id: '1.3-m1', lesson: '1.3.1', kind: 'term', group: 'malware', groupLabel: 'Типы вредоносного ПО', weight: 3,
      term: 'Virus', definition: 'A program that, when executed, replicates and attaches itself to other files by inserting its own code into them; most viruses require end-user interaction to activate and mutate to avoid detection.',
      cloze: 'A ___ replicates and attaches itself to other files by inserting its own code into them.',
      ru: 'Встраивает свой код в другие файлы, нужен носитель и обычно действие пользователя.' },
    { id: '1.3-m2', lesson: '1.3.1', kind: 'term', group: 'malware', groupLabel: 'Типы вредоносного ПО', weight: 3,
      term: 'Worm', definition: 'A malicious program that replicates by independently exploiting vulnerabilities in networks; unlike a virus it does not require a host program and does not require user participation after the initial infection.',
      cloze: 'A ___ replicates by independently exploiting vulnerabilities in networks and needs no host program.',
      ru: 'Работает сам, host не нужен, размножается через уязвимости сети и замедляет её.' },
    { id: '1.3-m3', lesson: '1.3.1', kind: 'term', group: 'malware', groupLabel: 'Типы вредоносного ПО', weight: 3,
      term: 'Trojan horse', definition: 'Malware that carries out malicious operations by masking its true intent; it does not self-replicate, binds itself to non-executable files such as image, audio or video files, and exploits the privileges of the user who runs it.',
      cloze: 'A ___ masks its true intent, does not self-replicate, and exploits the privileges of the user who runs it.',
      ru: 'Маскирует намерение, не самокопируется, работает с правами запустившего.' },
    { id: '1.3-m4', lesson: '1.3.2', kind: 'term', group: 'malware', groupLabel: 'Типы вредоносного ПО', weight: 3,
      term: 'Logic bomb', definition: 'A malicious program that waits for a trigger, such as a specified date or a database entry, to set off the malicious code; it remains inactive until the trigger event happens.',
      cloze: 'A ___ remains inactive until a trigger such as a specified date or database entry occurs.',
      ru: 'Ждёт триггер (дата, запись в БД), до срабатывания неактивна.' },
    { id: '1.3-m5', lesson: '1.3.3', kind: 'term', group: 'malware', groupLabel: 'Типы вредоносного ПО', weight: 3,
      term: 'Ransomware', definition: 'Malware designed to hold a computer system or the data it contains captive until a payment is made, usually by encrypting the data; the ransom is paid via an untraceable payment system.',
      cloze: '___ holds a computer system or its data captive until a payment is made.',
      ru: 'Держит данные в заложниках до выкупа, обычно через шифрование.' },
    { id: '1.3-m6', lesson: '1.3.1', kind: 'enum', group: 'malware-facts', groupLabel: 'Факты о вредоносах', weight: 3,
      term: 'The three shared patterns of worms', definition: 'They exploit system vulnerabilities, they have a way to propagate themselves, and they all contain malicious code (payload) to cause damage to computer systems or networks.',
      items: ['They exploit system vulnerabilities', 'They have a way to propagate themselves', 'They contain malicious code (payload) to cause damage'],
      decoys: ['They require a host program', 'They require user interaction to spread', 'They mutate to avoid detection'],
      ru: 'Три признака червя: уязвимость, механизм распространения, payload.' },
    { id: '1.3-m7', lesson: '1.3.2', kind: 'enum', group: 'malware-facts', groupLabel: 'Факты о вредоносах', weight: 2,
      term: 'Hardware components attacked by modern logic bombs', definition: 'Cooling fans, central processing unit (CPU), memory, hard drives and power supplies; the logic bomb overdrives these components until they overheat or fail.',
      items: ['Cooling fans', 'CPU', 'Memory', 'Hard drives', 'Power supplies'],
      decoys: ['Network switches', 'Firewall appliances', 'DNS resolver cache'],
      ru: 'Логическая бомба может физически убивать железо.' },
    { id: '1.3-m8', lesson: '1.3.1', kind: 'fact', group: 'malware-facts', groupLabel: 'Факты о вредоносах', weight: 2,
      term: 'The Melissa virus', definition: 'Released in 1999, spread via email, affected tens of thousands of users and caused an estimated $1.2 billion in damage.',
      cloze: 'The Melissa virus was released in ___ and spread via email.', clozeAnswer: '1999',
      decoys: ['2001', '1995', '2003'], ru: 'Melissa: 1999, email, $1.2 млрд ущерба.' },
    { id: '1.3-m9', lesson: '1.3.1', kind: 'fact', group: 'malware-facts', groupLabel: 'Факты о вредоносах', weight: 2,
      term: 'The Code Red worm', definition: 'In 2001 the Code Red worm had infected over 300,000 servers in just 19 hours.',
      cloze: 'In 2001 the Code Red worm infected over 300,000 servers in just ___.', clozeAnswer: '19 hours',
      decoys: ['19 days', '90 hours', '3 hours'], ru: 'Code Red: 2001, 300 000 серверов за 19 часов.' },

    /* --- DoS --- */
    { id: '1.3-d1', lesson: '1.3.4', kind: 'term', group: 'dos', groupLabel: 'DoS и DDoS', weight: 3,
      term: 'DoS attack', definition: 'A network attack that is relatively simple to conduct and usually results in interruption to network services; it works either by an overwhelming quantity of traffic or by maliciously formatted packets.',
      aliases: ['denial of service attack', 'DoS'], ru: 'Отказ в обслуживании из одного источника.' },
    { id: '1.3-d2', lesson: '1.3.4', kind: 'term', group: 'dos', groupLabel: 'DoS и DDoS', weight: 3,
      term: 'Overwhelming quantity of traffic', definition: 'When a network, host or application is sent an enormous amount of data at a rate which it cannot handle, causing a slowdown in transmission or response, or the device or service to crash.',
      ru: 'Первый тип DoS: объём данных, который цель не тянет.' },
    { id: '1.3-d3', lesson: '1.3.4', kind: 'term', group: 'dos', groupLabel: 'DoS и DDoS', weight: 3,
      term: 'Maliciously formatted packets', definition: 'Packets containing errors or improperly formatted packets that cannot be identified by an application, so the receiving device runs very slowly or crashes.',
      ru: 'Второй тип DoS: пакеты, которые получатель не может обработать.' },
    { id: '1.3-d4', lesson: '1.3.5', kind: 'term', group: 'dos', groupLabel: 'DoS и DDoS', weight: 3,
      term: 'DDoS attack', definition: 'Similar to a DoS attack but originating from multiple coordinated sources: an attacker builds a botnet of infected hosts called zombies controlled by handler systems, and instructs the handlers to make the botnet attack.',
      aliases: ['distributed denial of service attack', 'DDoS'], ru: 'DoS из множества скоординированных источников.' },
    { id: '1.3-d5', lesson: '1.3.5', kind: 'term', group: 'dos', groupLabel: 'DoS и DDoS', weight: 3,
      term: 'Botnet', definition: 'A network of infected hosts called zombies, which are controlled by handler systems and constantly scan and infect more hosts.',
      cloze: 'A ___ is a network of infected hosts called zombies controlled by handler systems.',
      ru: 'Сеть заражённых хостов-зомби под управлением handler systems.' },
    { id: '1.3-d6', lesson: '1.3.5', kind: 'term', group: 'dos', groupLabel: 'DoS и DDoS', weight: 2,
      term: 'Handler systems', definition: 'The systems that control the zombies in a botnet; the hacker instructs the handler systems to make the botnet carry out the DDoS attack.',
      ru: 'Управляющие системы между хакером и ботнетом.' },
    { id: '1.3-d7', lesson: '1.3.8', kind: 'enum', group: 'dos', groupLabel: 'DoS и DDoS', weight: 3,
      term: 'Signs that you have been infected by a botnet', definition: 'Performance issues, programs and applications not working properly, and advertisements popping up on screen, plus abnormal traffic on the network.',
      items: ['Performance issues', 'Programs and applications not working properly', 'Advertisements popping up on screen', 'Abnormal traffic on the network'],
      decoys: ['Files renamed with a new extension', 'A ransom note on the desktop', 'The DNS cache is empty'],
      ru: 'Признаки ботнета из задания 1.3.8.' },
    { id: '1.3-d8', lesson: '1.3.15', kind: 'term', group: 'defense', groupLabel: 'Защита от атак', weight: 3,
      term: 'ICMP', definition: 'Internet Control Message Protocol: network devices use ICMP packets to send error and control messages, such as whether a device can communicate with another; blocking external ICMP packets with firewalls helps prevent DoS and DDoS attacks.',
      aliases: ['internet control message protocol'], ru: 'Протокол служебных сообщений; внешний ICMP блокируют ради защиты от DoS и DDoS.' },
    { id: '1.3-d9', lesson: '1.3.15', kind: 'enum', group: 'defense', groupLabel: 'Защита от атак', weight: 3,
      term: 'Steps organizations take to defend against attacks', definition: 'Configure firewalls to remove packets from outside the network with addresses indicating they originated inside it; ensure patches and upgrades are current; distribute the workload across server systems; block external ICMP packets with firewalls.',
      items: ['Configure firewalls to drop spoofed inbound packets', 'Ensure patches and upgrades are current', 'Distribute the workload across server systems', 'Block external ICMP packets with firewalls'],
      decoys: ['Disable all logging', 'Publish the WHOIS record', 'Use a flat network'],
      ru: 'Четыре меры защиты из 1.3.15.' },

    /* --- DNS --- */
    { id: '1.3-n1', lesson: '1.3.6', kind: 'term', group: 'dns', groupLabel: 'DNS и домены', weight: 3,
      term: 'DNS', definition: 'The Domain Name System, used by DNS servers to translate a domain name such as www.cisco.com into a numerical IP address; if a DNS server does not know an IP address it will ask another DNS server.',
      aliases: ['domain name system'], ru: 'Переводит доменное имя в IP-адрес.' },
    { id: '1.3-n2', lesson: '1.3.6', kind: 'term', group: 'dns', groupLabel: 'DNS и домены', weight: 3,
      term: 'DNS spoofing', definition: 'Also called DNS cache poisoning: an attack in which false data is introduced into a DNS resolver cache, exploiting a weakness in DNS software that causes DNS servers to redirect traffic for a specific domain to the attacker computer.',
      aliases: ['dns cache poisoning', 'cache poisoning'],
      cloze: '___ introduces false data into a DNS resolver cache so traffic is redirected to the attacker.',
      ru: 'Подмена данных в кеше DNS-резолвера.' },
    { id: '1.3-n3', lesson: '1.3.6', kind: 'term', group: 'dns', groupLabel: 'DNS и домены', weight: 3,
      term: 'DNS resolver cache', definition: 'The temporary database on a computer operating system that records recent visits to websites and other Internet domains.',
      ru: 'Временная БД ОС с недавними посещениями сайтов.' },
    { id: '1.3-n4', lesson: '1.3.6', kind: 'term', group: 'dns', groupLabel: 'DNS и домены', weight: 3,
      term: 'Domain hijacking', definition: 'When an attacker wrongfully gains control of a target DNS information and makes unauthorized changes to it; the most common way is to change the administrator contact email address through social engineering or by hacking the administrator email account.',
      cloze: '___ is when an attacker wrongfully gains control of a target DNS information.',
      ru: 'Незаконный контроль над DNS-записями цели.' },
    { id: '1.3-n5', lesson: '1.3.6', kind: 'fact', group: 'dns', groupLabel: 'DNS и домены', weight: 3,
      term: 'Where the administrator email address for a domain is found', definition: 'The administrator email address can be easily found via the WHOIS record for the domain, which is of public record.',
      cloze: 'The administrator email address can be found via the ___ record for the domain.', clozeAnswer: 'WHOIS',
      decoys: ['MX', 'TXT', 'CNAME'], ru: 'В публичной записи WHOIS.' },
    { id: '1.3-n6', lesson: '1.3.6', kind: 'term', group: 'dns', groupLabel: 'DNS и домены', weight: 2,
      term: 'URL', definition: 'A uniform resource locator: a unique identifier for finding a specific resource on the Internet. Attackers exploit legitimate URL redirection to send users to a malicious site instead.',
      aliases: ['uniform resource locator'], ru: 'Уникальный идентификатор ресурса в интернете.' },
    { id: '1.3-n7', lesson: '1.3.6', kind: 'term', group: 'dns', groupLabel: 'DNS и домены', weight: 2,
      term: 'Domain reputation', definition: 'An organization needs to monitor its domain reputation, including its IP address, to help protect against malicious external domains.',
      ru: 'Репутация домена и IP, за которой надо следить.' },

    /* --- layer 2 --- */
    { id: '1.3-l1', lesson: '1.3.7', kind: 'term', group: 'layer2', groupLabel: 'Layer 2', weight: 3,
      term: 'Layer 2', definition: 'The data link layer in the OSI data communication model, used to move data across a linked physical network.',
      cloze: 'Layer 2 is the ___ layer in the OSI model.', clozeAnswer: 'data link',
      ru: 'Канальный уровень модели OSI.' },
    { id: '1.3-l2', lesson: '1.3.7', kind: 'term', group: 'layer2', groupLabel: 'Layer 2', weight: 3,
      term: 'ARP', definition: 'Address resolution protocol: the procedure that resolves IP addresses to MAC addresses for transmitting data.',
      aliases: ['address resolution protocol'], ru: 'Сопоставляет IP-адреса с MAC-адресами.' },
    { id: '1.3-l3', lesson: '1.3.7', kind: 'term', group: 'layer2', groupLabel: 'Layer 2', weight: 3,
      term: 'MAC address', definition: 'Media access control address: the physical device address that identifies the intended receiver of an IP address sent over the network.',
      aliases: ['media access control address'], ru: 'Физический адрес устройства, определяет получателя.' },
    { id: '1.3-l4', lesson: '1.3.7', kind: 'term', group: 'layer2', groupLabel: 'Layer 2', weight: 3,
      term: 'Spoofing', definition: 'Also called poisoning: a type of impersonation attack that takes advantage of a trusted relationship between two systems.',
      cloze: '___ , or poisoning, is an impersonation attack that takes advantage of a trusted relationship between two systems.',
      ru: 'Атака-подмена, эксплуатирует доверие между системами.' },
    { id: '1.3-l5', lesson: '1.3.7', kind: 'term', group: 'spoof-kinds', groupLabel: 'Виды спуфинга', weight: 3,
      term: 'MAC address spoofing', definition: 'Occurs when an attacker disguises their device as a valid one on the network and can therefore bypass the authentication process.',
      ru: 'Устройство атакующего выдаёт себя за валидное, обходит аутентификацию.' },
    { id: '1.3-l6', lesson: '1.3.7', kind: 'term', group: 'spoof-kinds', groupLabel: 'Виды спуфинга', weight: 3,
      term: 'ARP spoofing', definition: 'Sends spoofed ARP messages across a LAN, linking the attacker MAC address to the IP address of an authorized device on the network.',
      ru: 'Поддельные ARP-сообщения в LAN, MAC атакующего привязан к IP авторизованного устройства.' },
    { id: '1.3-l7', lesson: '1.3.7', kind: 'term', group: 'spoof-kinds', groupLabel: 'Виды спуфинга', weight: 3,
      term: 'IP spoofing', definition: 'Sends IP packets from a spoofed source address in order to disguise it.',
      ru: 'Пакеты с подделанным адресом источника.' },
    { id: '1.3-l8', lesson: '1.3.7', kind: 'term', group: 'spoof-kinds', groupLabel: 'Виды спуфинга', weight: 3,
      term: 'MAC flooding', definition: 'An attacker floods the network with fake MAC addresses, compromising the security of the network switch and the data transmitted to a device.',
      ru: 'Затопление фейковыми MAC, компрометирует коммутатор.' },

    /* --- прочие атаки --- */
    { id: '1.3-a1', lesson: '1.3.9', kind: 'term', group: 'other-attacks', groupLabel: 'Прочие атаки', weight: 3,
      term: 'Man-in-the-Middle (MitM)', definition: 'Happens when a cybercriminal takes control of a device without the user knowledge and can intercept, manipulate and relay false information between the sender and the intended destination.',
      aliases: ['mitm', 'man in the middle'], ru: 'Контроль над устройством без ведома пользователя, перехват и подмена.' },
    { id: '1.3-a2', lesson: '1.3.9', kind: 'term', group: 'other-attacks', groupLabel: 'Прочие атаки', weight: 3,
      term: 'Man-in-the-Mobile (MitMo)', definition: 'A variation of man-in-the-middle used to take control over a user mobile device; the infected device is instructed to exfiltrate user-sensitive information and send it to the attackers.',
      aliases: ['mitmo', 'man in the mobile'], ru: 'MitM для мобильного устройства.' },
    { id: '1.3-a3', lesson: '1.3.9', kind: 'fact', group: 'other-attacks', groupLabel: 'Прочие атаки', weight: 3,
      term: 'ZeuS', definition: 'An example of a malware package with MitMo capabilities: it allows attackers to quietly capture two-step verification SMS messages sent to users.',
      cloze: '___ is a malware package with MitMo capabilities that captures two-step verification SMS messages.', clozeAnswer: 'ZeuS',
      decoys: ['Melissa', 'Code Red', 'Netbus'], ru: 'ZeuS перехватывает SMS двухфакторной верификации.' },
    { id: '1.3-a4', lesson: '1.3.10', kind: 'term', group: 'other-attacks', groupLabel: 'Прочие атаки', weight: 3,
      term: 'Replay attack', definition: 'Occurs when an attacker captures communication between two hosts and then retransmits the message to the recipient to trick them into doing what the attacker wants, circumventing authentication mechanisms.',
      cloze: 'A ___ captures a message between two hosts and retransmits it to circumvent authentication.',
      ru: 'Перехват и повторная отправка сообщения.' },
    { id: '1.3-a5', lesson: '1.3.11', kind: 'term', group: 'other-attacks', groupLabel: 'Прочие атаки', weight: 3,
      term: 'Zero-day attack', definition: 'Exploits software vulnerabilities before they become known or before they are disclosed by the software vendor; the network is extremely vulnerable between zero hour and the release of a patch.',
      aliases: ['zero day threat', 'zero-day threat'], ru: 'Эксплуатация уязвимости до выхода патча.' },
    { id: '1.3-a6', lesson: '1.3.11', kind: 'fact', group: 'other-attacks', groupLabel: 'Прочие атаки', weight: 2,
      term: 'Zero hour', definition: 'The time an exploit is discovered; the network is extremely vulnerable between zero hour and the time the vendor develops and releases a patch.',
      cloze: 'The moment an exploit is discovered is called ___ .', clozeAnswer: 'zero hour',
      ru: 'Момент обнаружения эксплойта.' },
    { id: '1.3-a7', lesson: '1.3.12', kind: 'term', group: 'other-attacks', groupLabel: 'Прочие атаки', weight: 3,
      term: 'Keyboard logging', definition: 'Recording or logging every key struck on a computer keyboard, via software installed on the system or hardware devices physically attached to the computer; the log file can reveal usernames, passwords and websites visited.',
      aliases: ['keylogging', 'keylogger'], ru: 'Запись каждого нажатия клавиши.' },
    { id: '1.3-a8', lesson: '1.3.12', kind: 'fact', group: 'other-attacks', groupLabel: 'Прочие атаки', weight: 2,
      term: 'What removes unauthorized key loggers', definition: 'Many anti-spyware suites can detect and remove unauthorized key loggers.',
      cloze: 'Many ___ suites can detect and remove unauthorized key loggers.', clozeAnswer: 'anti-spyware',
      decoys: ['firewall', 'backup', 'DLP'], ru: 'Анти-шпионские пакеты.' },
    { id: '1.3-a9', lesson: '1.3.13', kind: 'fact', group: 'other-attacks', groupLabel: 'Прочие атаки', weight: 2,
      term: 'A legitimate use of keylogging software', definition: 'Keylogging software can be legitimate: many parents use it to keep an eye on their children internet behavior.',
      ru: 'Родительский контроль это легальное применение кейлоггера.' },
    { id: '1.3-a10', lesson: '1.3.14', kind: 'term', group: 'other-attacks', groupLabel: 'Прочие атаки', weight: 3,
      term: 'Impersonation', definition: 'The act of tricking someone into divulging their personal information by pretending to be someone else, for example with a spoofed email.',
      cloze: '___ is tricking someone into divulging personal information by pretending to be someone else.',
      ru: 'Выдача себя за другого ради выманивания личных данных.' },
    { id: '1.3-a11', lesson: '1.3.14', kind: 'enum', group: 'other-attacks', groupLabel: 'Прочие атаки', weight: 3,
      term: 'What to check so you do not get spoofed', definition: 'The sender email domain, the URL of the link, the language spelling and grammar, and the graphics.',
      items: ['The sender email domain', 'The URL of the link', 'The language, spelling and grammar', 'The graphics'],
      decoys: ['The time the email was sent', 'The size of the attachment', 'The number of recipients'],
      ru: 'Четыре признака подделки письма.' },

    /* --- вопросы курса --- */
    { id: '1.3-q1', lesson: '1.3.8', kind: 'quiz', group: '1.3', groupLabel: 'Вопросы раздела 1.3', weight: 3,
      term: 'DDoS attack', definition: 'Spot the Attack',
      quiz: { type: 'mcq',
        q: 'Several employees at @Apollo have reported performance issues on their computers, with applications running slow and notable popup ads appearing. A network monitoring tool also reveals abnormal traffic on the network. What type of attack might @Apollo be involved with?',
        options: ['DoS attack', 'DDoS attack', 'Layer 2 attack', 'DNS attack'],
        answers: ['DDoS attack'],
        why: 'Атакующий создавал botnet из zombies. Признаки заражения ботнетом: проблемы с производительностью, неправильно работающие приложения, всплывающая реклама.' } },
    { id: '1.3-q2', lesson: '1.3.14', kind: 'quiz', group: '1.3', groupLabel: 'Вопросы раздела 1.3', weight: 3,
      term: 'Impersonation', definition: 'Confirm Your Details',
      quiz: { type: 'mcq',
        q: 'An email that looks internal asks you to add your bank account details by clicking a link before the end of the day, but the sender email domain has a slight variation. You could be a victim of what type of attack?',
        options: ['Impersonation', 'Man-in-the-middle', 'Domain hijacking', 'Trojan horse'],
        answers: ['Impersonation'],
        why: 'Преступник использовал spoofed email, чтобы обманом заставить раскрыть личные данные.' } },
    { id: '1.3-q3', lesson: '1.3.1', kind: 'quiz', group: '1.3', groupLabel: 'Вопросы раздела 1.3', weight: 3,
      term: 'Worm', definition: 'Какой вредонос не требует host-программы',
      quiz: { type: 'mcq',
        q: 'Which type of malware can run by itself, does not require a host program, and replicates by independently exploiting vulnerabilities in networks?',
        options: ['Virus', 'Worm', 'Trojan horse', 'Logic bomb'],
        answers: ['Worm'],
        why: 'Именно червь работает самостоятельно и не требует участия пользователя после первичного заражения.' } },
  ],
}
