import type { Island } from '@/types'

export const island_1_4: Island = {
  id: '1.4',
  moduleId: 1,
  title: 'Wireless and Mobile Device Attacks',
  titleRu: 'Атаки на беспроводные и мобильные устройства',
  objective: 'Explain the attacks that target wireless networks and mobile devices, and how to defend against them.',
  icon: 'Smartphone',
  lessons: [
    {
      id: '1.4.1', title: 'Working on the Go', titleRu: 'Работа на ходу', kind: 'text',
      blocks: [
        { t: 'p', md: 'Широкое распространение интернета и мобильных устройств означает, что сейчас мы можем общаться и работать **на ходу, без кабелей и проводов**. Но это же создаёт больше возможностей для киберпреступников добраться до нужной им **sensitive information**.' },
        { t: 'note', variant: 'tip', md: 'Идея раздела в одной строке: рост мобильности = рост поверхности атаки.' },
      ],
    },
    {
      id: '1.4.2', title: 'Grayware and SMiShing', titleRu: 'Grayware и SMiShing', kind: 'text',
      blocks: [
        { t: 'def', term: 'Grayware', md: 'Any **unwanted application that behaves in an annoying or undesirable manner**. Grayware может не нести распознаваемого malware, но всё равно представляет риск: например, **tracking your location** или **delivering unwanted advertising**.' },
        { t: 'p', md: 'Авторы grayware обычно сохраняют легитимность, включая эти «серые» возможности **в мелкий шрифт (small print) лицензионного соглашения**. Это особенно опасно для мобильной безопасности: многие пользователи смартфонов ставят приложения, не читая этот мелкий шрифт.' },
        { t: 'def', term: 'SMiShing', md: '**Short message service phishing**. Поддельные текстовые сообщения побуждают вас зайти на **вредоносный сайт** или позвонить на **мошеннический номер**, что может привести к загрузке malware на устройство или к передаче личной информации.' },
        { t: 'note', variant: 'exam', title: 'Отличие', md: 'Grayware — это про **софт и лицензию**. SMiShing — это про **текстовые сообщения и социальную инженерию**.' },
      ],
    },
    {
      id: '1.4.3', title: 'Rogue Access Points', titleRu: 'Поддельные точки доступа', kind: 'text',
      blocks: [
        { t: 'def', term: 'Rogue access point', md: 'A wireless access point **installed on a secure network without explicit authorization**.' },
        { t: 'p', md: 'Её может поставить и **благонамеренный сотрудник**, которому нужен сигнал получше, но она же даёт возможность атакующему получить доступ к сети организации.' },
        { t: 'h', text: 'Как её ставит атакующий' },
        { t: 'p', md: 'Атакующий часто использует **social engineering**, чтобы получить **физический доступ** к сетевой инфраструктуре организации и установить rogue access point.' },
        { t: 'h', text: "Criminal's access point и deauthentication" },
        { t: 'p', md: 'Второе название rogue AP — **criminal access point**. Точка может быть настроена как **MitM device** для перехвата ваших login information.' },
        { t: 'p', md: 'Механика: отключение rogue access point заставляет сеть отправить **deauthentication frame**, чтобы разорвать связь с точкой. Этот процесс эксплуатируется через **спуфинг вашего MAC-адреса** и отправку **deauthentication data transmission** на беспроводную точку доступа.' },
        { t: 'figure', caption: 'Схема: Attacker (laptop) → Client (desktop) → Router; связь между client и router помечена как Deauthentication.' },
        { t: 'def', term: 'Evil twin attack', md: 'Ситуация, когда точка доступа атакующего настроена так, чтобы **выглядеть более выгодным вариантом подключения**. Как только вы подключились к злой точке, атакующий может анализировать ваш сетевой трафик и выполнять **MitM-атаки**.' },
        { t: 'figure', caption: 'Схема: Clueless user подключается к интернету двумя путями — через Real access point (weak signal) и через Rogue access point (strong signal).' },
        { t: 'note', variant: 'exam', md: '**Rogue AP** — общий термин: несанкционированная точка. **Evil twin** — частный случай: точка маскируется под более удачную альтернативу.' },
      ],
    },
    {
      id: '1.4.4', title: 'Radio Frequency Jamming', titleRu: 'Радиочастотное глушение', kind: 'text',
      blocks: [
        { t: 'p', md: 'Беспроводные сигналы подвержены **electromagnetic interference (EMI)**, **radio frequency interference (RFI)** и даже **ударам молнии** и **шуму от люминесцентных ламп**.' },
        { t: 'def', term: 'RF jamming', md: 'Атакующие пользуются этим, **умышленно глуша передачу радио- или спутниковой станции**, чтобы беспроводной сигнал не дошёл до принимающей станции.' },
        { t: 'note', variant: 'exam', title: 'Три параметра', md: 'Чтобы успешно заглушить сигнал, **frequency, modulation и power** у RF jammer должны быть **равны** параметрам устройства, которое атакующий хочет нарушить.' },
      ],
    },
    {
      id: '1.4.5', title: 'Bluetooth Basics', titleRu: 'Основы Bluetooth', kind: 'text',
      blocks: [
        { t: 'def', term: 'Bluetooth', md: 'A **short-range, low-power protocol** that transmits data in a **personal area network (PAN)** and uses **pairing** to establish a relationship between devices such as mobiles, laptops and printers.' },
        { t: 'p', md: 'Киберпреступники нашли способы эксплуатировать уязвимости именно **в этих соединениях**.' },
      ],
    },
    {
      id: '1.4.6', title: 'Bluejacking and Bluesnarfing', titleRu: 'Bluejacking и Bluesnarfing', kind: 'flip',
      blocks: [
        { t: 'p', md: 'Из-за ограниченного радиуса Bluetooth атакующий должен быть **within range** цели. Вот два способа эксплуатировать устройство жертвы **без её ведома**.' },
        {
          t: 'flip', title: 'Две Bluetooth-атаки',
          cards: [
            { front: 'Bluejacking', back: 'Uses wireless Bluetooth technology to send **unauthorized messages or shocking images** to another Bluetooth device.' },
            { front: 'Bluesnarfing', back: 'Occurs when an attacker **copies information, such as emails and contact lists, from a target device** using a Bluetooth connection.' },
          ],
        },
        { t: 'note', variant: 'tip', title: 'Мнемоника', md: '**Bluejacking** — данные идут **внутрь** устройства жертвы (отправка). **Bluesnarfing** — данные идут **наружу** (snarf = стащить).' },
      ],
    },
    {
      id: '1.4.7', title: 'Attacks Against Wi-Fi Protocols', titleRu: 'Атаки на протоколы Wi-Fi', kind: 'text',
      blocks: [
        { t: 'p', md: '**Wired equivalent privacy (WEP)** и **Wi-Fi protected access (WPA)** — протоколы безопасности, созданные для защиты уязвимых беспроводных сетей.' },
        { t: 'def', term: 'WEP', md: 'Разработан, чтобы дать данным, передаваемым по **WLAN**, уровень защиты, сопоставимый с тем, что обычно ожидается от традиционной **проводной** сети. Добавлял безопасность через **шифрование данных** и использовал **ключ** для шифрования.' },
        { t: 'h', text: 'Две проблемы WEP' },
        { t: 'list', ordered: true, items: [
          '**No provision for key management**: число людей, делящих один и тот же ключ, постоянно росло, что давало преступникам доступ к большому объёму трафика.',
          '**Initialization vector (IV)** — один из ключевых компонентов ключа шифрования — был **too small, readable and static**.',
        ] },
        { t: 'def', term: 'WPA и WPA2', md: 'Улучшенные протоколы безопасности, разработанные, чтобы заменить WEP. В отличие от WEP, атакующий **не может восстановить ключ шифрования WPA2, наблюдая за сетевым трафиком**. Однако он всё ещё может использовать **packet sniffer**, чтобы анализировать пакеты между точкой доступа и легитимным пользователем.' },
        { t: 'table', caption: 'Пьедестал надёжности (из схемы курса)', headers: ['Место', 'Протокол'], rows: [
          ['1', '**WPA2**'],
          ['2', '**WPA**'],
          ['3', '**WEP**'],
        ] },
      ],
    },
    {
      id: '1.4.8', title: 'Risky Business (activity)', titleRu: 'Рискованное дело', kind: 'activity',
      blocks: [
        { t: 'p', md: '**Сценарий.** Вы в кафе, решили проверить почту. Wi-Fi кафе подключается очень слабо, зато рядом есть **вторая сеть с похожим именем**, и вы подключаетесь к ней. Неподалёку сидит атакующий: он создал Wi-Fi hotspot на своём телефоне, спаренном с ноутбуком, и мониторит активность всех, кто подключился.' },
        {
          t: 'activity', title: 'What type of attack is this?',
          prompt: 'Выбери тип атаки',
          options: ['Evil twin', 'Bluesnarfing', 'Bluejacking', 'Radio frequency jamming'],
          items: [{ q: 'Вторая сеть с похожим именем и сильным сигналом, трафик всех подключившихся мониторится', a: 'Evil twin', why: 'Атакующий настроил hotspot так, чтобы он выглядел лучшим вариантом подключения к Wi-Fi кафе.' }],
          feedback: 'Всегда используйте VPN в публичных сетях, особенно при доступе к личным данным или конфиденциальной информации организации.',
        },
        { t: 'table', caption: 'Разбор неверных вариантов', headers: ['Вариант', 'Почему не он'], rows: [
          ['Bluejacking / Bluesnarfing', 'Это **Bluetooth**, а не Wi-Fi.'],
          ['Radio frequency jamming', 'Это **блокировка передачи**, а не подмена точки доступа.'],
        ] },
      ],
    },
    {
      id: '1.4.9', title: 'Wi-Fi and Mobile Defense', titleRu: 'Защита Wi-Fi и мобильных', kind: 'text',
      blocks: [
        { t: 'h', text: 'Пять мер из курса' },
        { t: 'list', ordered: true, items: [
          'Воспользоваться базовыми функциями безопасности беспроводной сети — **authentication** и **encryption** — **изменив настройки по умолчанию**.',
          'Ограничить размещение точек доступа: ставить их **за пределами firewall** или **внутри demilitarized zone (DMZ)** — периметровой сети, защищающей LAN организации от недоверенных устройств.',
          'Использовать **WLAN-инструменты, например NetStumbler**, чтобы обнаруживать rogue access points или неавторизованные рабочие станции.',
          'Разработать **политику гостевого доступа** к Wi-Fi организации.',
          'Сотрудникам использовать **remote access VPN** для доступа к WLAN.',
        ] },
        { t: 'note', variant: 'exam', md: 'Единственный названный по имени инструмент в разделе — **NetStumbler**.' },
      ],
    },
    {
      id: '1.4.S', title: 'Summary table', titleRu: 'Итоговая таблица 1.4', kind: 'summary',
      blocks: [
        { t: 'table', headers: ['Атака или понятие', 'Технология', 'Суть', 'Ключевая деталь'], rows: [
          ['Grayware', 'Мобильные приложения', 'Нежелательное приложение с раздражающим поведением', 'Не malware; легитимность через small print; tracking location, unwanted advertising'],
          ['SMiShing', 'SMS', 'Фишинг через поддельные текстовые сообщения', 'Ведёт на malicious website или fraudulent phone number'],
          ['Rogue access point', 'Wi-Fi', 'Точка доступа в защищённой сети без авторизации', 'Ставится через social engineering плюс физический доступ, работает как MitM device'],
          ['Deauthentication attack', 'Wi-Fi', 'Эксплуатация deauthentication frame', 'Spoofing MAC-адреса жертвы плюс deauthentication data transmission'],
          ['Evil twin', 'Wi-Fi', 'Точка атакующего маскируется под лучший вариант подключения', 'Затем анализ трафика и MitM, защита это VPN'],
          ['Radio frequency jamming', 'Радио и спутник', 'Умышленное глушение передачи', 'Jammer совпадает по frequency, modulation, power'],
          ['Bluejacking', 'Bluetooth', 'Отправка несанкционированных сообщений или шокирующих изображений', 'Данные идут НА устройство жертвы'],
          ['Bluesnarfing', 'Bluetooth', 'Копирование emails и contact lists с устройства жертвы', 'Данные идут С устройства жертвы'],
          ['WEP', 'Wi-Fi протокол', 'Первый протокол защиты WLAN, шифрование данных', 'Нет key management, IV too small, readable, static'],
          ['WPA / WPA2', 'Wi-Fi протокол', 'Улучшенная замена WEP', 'Ключ WPA2 нельзя восстановить наблюдением за трафиком, packet sniffer всё ещё применим'],
        ] },
        { t: 'table', caption: 'Ключи к вопросам раздела', headers: ['Вопрос', 'Ответ'], rows: [
          ['1.4.8 Risky Business', '**Evil twin**'],
        ] },
      ],
    },
  ],
  atoms: [
    { id: '1.4-w1', lesson: '1.4.2', kind: 'term', group: 'mobile', groupLabel: 'Мобильные угрозы', weight: 3,
      term: 'Grayware', definition: 'Any unwanted application that behaves in an annoying or undesirable manner; it may carry no recognizable malware but can still track your location or deliver unwanted advertising.',
      cloze: '___ is any unwanted application that behaves in an annoying or undesirable manner.',
      ru: 'Нежелательное приложение, ведущее себя раздражающе. Не malware, но следит и показывает рекламу.' },
    { id: '1.4-w2', lesson: '1.4.2', kind: 'fact', group: 'mobile', groupLabel: 'Мобильные угрозы', weight: 3,
      term: 'How grayware authors maintain legitimacy', definition: 'They include these gray capabilities in the small print of the software license agreement, which many smartphone users never read.',
      cloze: 'Grayware authors keep legitimacy by hiding the gray capabilities in the ___ of the software license agreement.', clozeAnswer: 'small print',
      decoys: ['privacy policy', 'app store listing', 'release notes'], ru: 'Мелкий шрифт лицензионного соглашения.' },
    { id: '1.4-w3', lesson: '1.4.2', kind: 'term', group: 'mobile', groupLabel: 'Мобильные угрозы', weight: 3,
      term: 'SMiShing', definition: 'Short message service phishing: fake text messages prompt you to visit a malicious website or call a fraudulent phone number, which may result in malware being downloaded or personal information being shared.',
      aliases: ['short message service phishing', 'smishing'],
      cloze: '___ uses fake text messages to send you to a malicious website or a fraudulent phone number.',
      ru: 'Фишинг через поддельные SMS.' },

    { id: '1.4-r1', lesson: '1.4.3', kind: 'term', group: 'wifi-attacks', groupLabel: 'Атаки на Wi-Fi', weight: 3,
      term: 'Rogue access point', definition: 'A wireless access point installed on a secure network without explicit authorization; also called a criminal access point, it can be set up as a MitM device to capture login information.',
      cloze: 'A ___ is a wireless access point installed on a secure network without explicit authorization.',
      ru: 'Точка доступа в защищённой сети без явной авторизации.' },
    { id: '1.4-r2', lesson: '1.4.3', kind: 'fact', group: 'wifi-attacks', groupLabel: 'Атаки на Wi-Fi', weight: 2,
      term: 'How an attacker installs a rogue access point', definition: 'An attacker will often use social engineering tactics to gain physical access to the organization network infrastructure and install the rogue access point.',
      cloze: 'An attacker uses ___ tactics to gain physical access and install a rogue access point.', clozeAnswer: 'social engineering',
      ru: 'Через социальную инженерию и физический доступ.' },
    { id: '1.4-r3', lesson: '1.4.3', kind: 'term', group: 'wifi-attacks', groupLabel: 'Атаки на Wi-Fi', weight: 3,
      term: 'Deauthentication frame', definition: 'Disconnecting the rogue access point triggers the network to send a deauthentication frame to disassociate the access point; the attacker exploits this by spoofing your MAC address and sending a deauthentication data transmission to the wireless access point.',
      ru: 'Кадр разрыва связи, который эксплуатируют спуфингом MAC-адреса жертвы.' },
    { id: '1.4-r4', lesson: '1.4.3', kind: 'term', group: 'wifi-attacks', groupLabel: 'Атаки на Wi-Fi', weight: 3,
      term: 'Evil twin attack', definition: 'A situation where the attacker access point is set up to look like a better connection option; once you connect to the evil access point, the attacker can analyze your network traffic and execute MitM attacks.',
      cloze: 'An ___ attack sets up the attacker access point to look like a better connection option.', clozeAnswer: 'evil twin',
      ru: 'Точка атакующего маскируется под более выгодное подключение.' },
    { id: '1.4-r5', lesson: '1.4.4', kind: 'term', group: 'wifi-attacks', groupLabel: 'Атаки на Wi-Fi', weight: 3,
      term: 'Radio frequency jamming', definition: 'Deliberately jamming the transmission of a radio or satellite station to prevent a wireless signal from reaching the receiving station.',
      aliases: ['rf jamming'], ru: 'Умышленное глушение передачи, чтобы сигнал не дошёл до приёмника.' },
    { id: '1.4-r6', lesson: '1.4.4', kind: 'enum', group: 'wifi-attacks', groupLabel: 'Атаки на Wi-Fi', weight: 3,
      term: 'What an RF jammer must match to jam a signal', definition: 'The frequency, modulation and power of the RF jammer needs to be equal to that of the device the attacker is seeking to disrupt.',
      items: ['Frequency', 'Modulation', 'Power'],
      decoys: ['MAC address', 'SSID', 'Channel width'], ru: 'Частота, модуляция, мощность.' },
    { id: '1.4-r7', lesson: '1.4.4', kind: 'enum', group: 'wifi-attacks', groupLabel: 'Атаки на Wi-Fi', weight: 2,
      term: 'Sources of interference for wireless signals', definition: 'Electromagnetic interference (EMI), radio frequency interference (RFI), lightning strikes and noise from fluorescent lights.',
      items: ['Electromagnetic interference (EMI)', 'Radio frequency interference (RFI)', 'Lightning strikes', 'Noise from fluorescent lights'],
      decoys: ['DNS cache poisoning', 'MAC flooding', 'Packet sniffers'], ru: 'EMI, RFI, молнии, люминесцентные лампы.' },

    { id: '1.4-b1', lesson: '1.4.5', kind: 'term', group: 'bluetooth', groupLabel: 'Bluetooth', weight: 3,
      term: 'Bluetooth', definition: 'A short-range, low-power protocol that transmits data in a personal area network (PAN) and uses pairing to establish a relationship between devices such as mobiles, laptops and printers.',
      cloze: 'Bluetooth transmits data in a ___ and uses pairing to establish a relationship between devices.', clozeAnswer: 'personal area network (PAN)',
      ru: 'Короткодистанционный маломощный протокол, работает в PAN, использует pairing.' },
    { id: '1.4-b2', lesson: '1.4.6', kind: 'term', group: 'bluetooth', groupLabel: 'Bluetooth', weight: 3,
      term: 'Bluejacking', definition: 'Uses wireless Bluetooth technology to send unauthorized messages or shocking images to another Bluetooth device.',
      cloze: '___ sends unauthorized messages or shocking images to another Bluetooth device.',
      ru: 'Отправка непрошеных сообщений или шокирующих картинок на чужое устройство.' },
    { id: '1.4-b3', lesson: '1.4.6', kind: 'term', group: 'bluetooth', groupLabel: 'Bluetooth', weight: 3,
      term: 'Bluesnarfing', definition: 'Occurs when an attacker copies information, such as emails and contact lists, from a target device using a Bluetooth connection.',
      cloze: '___ copies emails and contact lists from a target device over Bluetooth.',
      ru: 'Копирование почты и контактов с устройства жертвы.' },
    { id: '1.4-b4', lesson: '1.4.6', kind: 'bucket', group: 'bt-direction', groupLabel: 'Направление данных', weight: 3,
      term: 'Sending unauthorized messages or shocking images to a device', definition: 'This is bluejacking: data goes into the victim device.', bucket: 'Bluejacking',
      ru: 'Данные идут на устройство жертвы.' },
    { id: '1.4-b5', lesson: '1.4.6', kind: 'bucket', group: 'bt-direction', groupLabel: 'Направление данных', weight: 3,
      term: 'Copying emails and contact lists from a device', definition: 'This is bluesnarfing: data goes out of the victim device.', bucket: 'Bluesnarfing',
      ru: 'Данные идут с устройства жертвы.' },

    { id: '1.4-p1', lesson: '1.4.7', kind: 'term', group: 'wifi-protocols', groupLabel: 'Протоколы Wi-Fi', weight: 3,
      term: 'WEP', definition: 'Wired equivalent privacy: developed to give data transmitted over a WLAN a level of protection comparable to a traditional wired network, by encrypting the data with a key.',
      aliases: ['wired equivalent privacy'], ru: 'Первый протокол защиты WLAN.' },
    { id: '1.4-p2', lesson: '1.4.7', kind: 'enum', group: 'wifi-protocols', groupLabel: 'Протоколы Wi-Fi', weight: 3,
      term: 'The two weaknesses of WEP', definition: 'WEP had no provision for key management, so the number of people sharing the same key continually grew; and its initialization vector (IV) was too small, readable and static.',
      items: ['No provision for key management', 'The initialization vector (IV) was too small, readable and static'],
      decoys: ['It used no encryption at all', 'It required a RADIUS server', 'It blocked packet sniffers'],
      ru: 'Нет управления ключами; IV маленький, читаемый и статичный.' },
    { id: '1.4-p3', lesson: '1.4.7', kind: 'term', group: 'wifi-protocols', groupLabel: 'Протоколы Wi-Fi', weight: 3,
      term: 'WPA2', definition: 'An improved security protocol developed to replace WEP; unlike WEP, an attacker cannot recover the WPA2 encryption key by observing network traffic, though a packet sniffer can still analyze the packets between an access point and a legitimate user.',
      aliases: ['wi-fi protected access 2', 'wpa'], ru: 'Ключ нельзя восстановить наблюдением за трафиком, но sniffer работает.' },
    { id: '1.4-p4', lesson: '1.4.7', kind: 'fact', group: 'wifi-protocols', groupLabel: 'Протоколы Wi-Fi', weight: 3,
      term: 'What an attacker can still do against WPA2', definition: 'They can still use a packet sniffer to analyze the packets going between an access point and a legitimate user.',
      cloze: 'Against WPA2 an attacker can still use a ___ to analyze packets between an access point and a legitimate user.', clozeAnswer: 'packet sniffer',
      decoys: ['deauthentication frame', 'RF jammer', 'WHOIS record'], ru: 'Packet sniffer всё ещё применим.' },
    { id: '1.4-p5', lesson: '1.4.7', kind: 'fact', group: 'wifi-protocols', groupLabel: 'Протоколы Wi-Fi', weight: 2,
      term: 'The order of Wi-Fi protocol strength', definition: 'WPA2 is the strongest, then WPA, then WEP.',
      cloze: 'From strongest to weakest the Wi-Fi protocols are ___ .', clozeAnswer: 'WPA2, WPA, WEP',
      ru: 'WPA2 сильнее WPA, WPA сильнее WEP.' },

    { id: '1.4-f1', lesson: '1.4.9', kind: 'enum', group: 'wifi-defense', groupLabel: 'Защита Wi-Fi и мобильных', weight: 3,
      term: 'The five Wi-Fi and mobile defense steps', definition: 'Take advantage of basic wireless security features such as authentication and encryption by changing the default configuration settings; restrict access point placement outside the firewall or within a demilitarized zone; use WLAN tools such as NetStumbler to detect rogue access points or unauthorized workstations; develop a policy for guest access; have employees use a remote access VPN for WLAN access.',
      items: ['Change default settings and turn on authentication and encryption', 'Place access points outside the firewall or in a DMZ', 'Use WLAN tools such as NetStumbler to detect rogue access points', 'Develop a policy for guest access to the Wi-Fi network', 'Employees should use a remote access VPN for WLAN access'],
      decoys: ['Broadcast the SSID everywhere', 'Use WEP for compatibility', 'Disable the firewall for guests'],
      ru: 'Пять мер защиты из 1.4.9.' },
    { id: '1.4-f2', lesson: '1.4.9', kind: 'term', group: 'wifi-defense', groupLabel: 'Защита Wi-Fi и мобильных', weight: 3,
      term: 'Demilitarized zone (DMZ)', definition: 'A perimeter network that protects an organization LAN from untrusted devices; access points should be placed outside the firewall or within it.',
      aliases: ['dmz'], ru: 'Периметровая сеть, защищающая LAN от недоверенных устройств.' },
    { id: '1.4-f3', lesson: '1.4.9', kind: 'fact', group: 'wifi-defense', groupLabel: 'Защита Wi-Fi и мобильных', weight: 3,
      term: 'The WLAN tool named in the course', definition: 'NetStumbler: a WLAN tool used to detect rogue access points or unauthorized workstations.',
      cloze: 'WLAN tools such as ___ detect rogue access points or unauthorized workstations.', clozeAnswer: 'NetStumbler',
      decoys: ['NetBus', 'Wireshark', 'InMAP'], ru: 'NetStumbler.' },
    { id: '1.4-f4', lesson: '1.4.8', kind: 'fact', group: 'wifi-defense', groupLabel: 'Защита Wi-Fi и мобильных', weight: 3,
      term: 'How to stay secure on public networks', definition: 'Always use a virtual private network (VPN) to stay secure on public networks, especially when accessing personal data or confidential organizational information.',
      cloze: 'Always use a ___ to stay secure on public networks.', clozeAnswer: 'VPN',
      ru: 'VPN на публичных сетях.' },

    { id: '1.4-q1', lesson: '1.4.8', kind: 'quiz', group: '1.4', groupLabel: 'Вопросы раздела 1.4', weight: 3,
      term: 'Evil twin', definition: 'Risky Business',
      quiz: { type: 'mcq',
        q: 'In a cafe the real Wi-Fi connection looks very weak, so you log on to a second Wi-Fi with a similar name. An attacker sitting nearby created that hotspot on their mobile, paired it with their laptop and is monitoring everyone who connects. What type of attack is this?',
        options: ['Evil twin', 'Bluesnarfing', 'Bluejacking', 'Radio frequency jamming'],
        answers: ['Evil twin'],
        why: 'Точка доступа атакующего настроена так, чтобы выглядеть лучшим вариантом подключения. После подключения он анализирует трафик и выполняет MitM.' } },
    { id: '1.4-q2', lesson: '1.4.6', kind: 'quiz', group: '1.4', groupLabel: 'Вопросы раздела 1.4', weight: 3,
      term: 'Bluesnarfing', definition: 'Копирование данных по Bluetooth',
      quiz: { type: 'mcq',
        q: 'An attacker within range copies emails and contact lists from a target device over a Bluetooth connection. What is this attack called?',
        options: ['Bluesnarfing', 'Bluejacking', 'SMiShing', 'Evil twin'],
        answers: ['Bluesnarfing'],
        why: 'Bluesnarfing это копирование информации С устройства жертвы. Bluejacking наоборот отправляет сообщения НА устройство.' } },
  ],
}
