import type { Island } from '@/types'

export const island_1_5: Island = {
  id: '1.5',
  moduleId: 1,
  title: 'Application Attacks',
  titleRu: 'Атаки на приложения',
  objective: 'Explain application, email and browser attacks and how to defend against them.',
  icon: 'Wrench',
  lessons: [
    {
      id: '1.5.1', title: 'Introduction to application attacks', titleRu: 'Введение', kind: 'text',
      blocks: [
        { t: 'p', md: 'Атаки через веб-приложения становятся всё более распространёнными. Киберпреступники **эксплуатируют уязвимости в коде** веб-приложения, чтобы получить доступ **к базе данных или серверу**.' },
        { t: 'note', variant: 'tip', md: 'Отличие от сетевых атак: мишень не канал и не протокол, а **само приложение и то, как оно обрабатывает ввод**.' },
      ],
    },
    {
      id: '1.5.2', title: 'Cross-Site Scripting', titleRu: 'Межсайтовый скриптинг', kind: 'text',
      blocks: [
        { t: 'def', term: 'Cross-site scripting (XSS)', md: 'A common vulnerability found in many web applications.' },
        { t: 'h', text: 'Как это работает (4 шага)' },
        { t: 'list', ordered: true, items: [
          'Cybercriminals exploit the XSS vulnerability by **injecting scripts containing malicious code into a web page**.',
          'The web page is accessed by the victim, and the malicious scripts **unknowingly pass to their browser**.',
          'The malicious script can access any **cookies, session tokens or other sensitive information** about the user, which is sent back to the cybercriminal.',
          'Armed with this information, the cybercriminal can **impersonate the user**.',
        ] },
        { t: 'note', variant: 'exam', md: 'XSS бьёт по **браузеру другого пользователя**. Injection-атаки (1.5.3) бьют по **базе данных или серверу**.' },
      ],
    },
    {
      id: '1.5.3', title: 'Code Injection', titleRu: 'Инъекции кода', kind: 'accordion',
      blocks: [
        { t: 'p', md: 'Большинство современных сайтов используют базу данных — **SQL (Structured Query Language)** или **XML (Extensible Markup Language)** — чтобы хранить данные и управлять ими. Injection-атаки нацелены на слабости этих баз.' },
        {
          t: 'accordion', title: 'Четыре типа инъекций',
          items: [
            { title: 'XML injection attack', md: 'Может **повредить данные в XML-базе** и поставить под угрозу безопасность сайта.\n\nРаботает через **вмешательство в обработку приложением XML-данных или запроса**, введённого пользователем. Преступники могут запрограммировать запрос под свои нужды, что даёт им доступ ко **всей чувствительной информации** в базе и позволяет вносить **любое количество изменений в сайт**.' },
            { title: 'SQL injection attack', md: 'Выполняется **вставкой вредоносного SQL-выражения в поле ввода**.\n\nАтака использует уязвимость, при которой приложение **некорректно фильтрует данные, введённые пользователем**, на предмет символов SQL-выражения.\n\nРезультат: неавторизованный доступ к данным, откуда можно **spoof an identity, modify existing data, destroy data** или даже **стать администратором самого сервера базы данных**.' },
            { title: 'DLL injection attack', md: '**DLL (dynamic link library)** — библиотека, содержащая набор кода и данных для выполнения определённой задачи **в Windows**. Приложения используют такие файлы, чтобы добавить функциональность, которой у них нет встроенно.\n\nDLL injection позволяет преступнику **обманом заставить приложение вызвать вредоносный DLL-файл**, который выполняется **как часть целевого процесса**.' },
            { title: 'LDAP injection attack', md: '**LDAP (Lightweight Directory Access Protocol)** — открытый протокол для **аутентификации доступа пользователей к directory services**.\n\nАтака эксплуатирует **уязвимости валидации ввода**, внедряя и выполняя запросы к LDAP-серверам, что даёт возможность **извлечь чувствительную информацию из LDAP-каталога организации**.' },
          ],
        },
        { t: 'table', caption: 'Расшифровки', headers: ['Аббревиатура', 'Расшифровка'], rows: [
          ['SQL', 'Structured Query Language'],
          ['XML', 'Extensible Markup Language'],
          ['DLL', 'Dynamic link library'],
          ['LDAP', 'Lightweight Directory Access Protocol'],
        ] },
      ],
    },
    {
      id: '1.5.4', title: 'Buffer Overflow', titleRu: 'Переполнение буфера', kind: 'text',
      blocks: [
        { t: 'def', term: 'Buffer', md: 'Memory areas **allocated to an application**.' },
        { t: 'def', term: 'Buffer overflow', md: 'Occurs when **data is written beyond the limits of a buffer**. Меняя данные за границами буфера, приложение может получить доступ **к памяти, выделенной другим процессам**.' },
        { t: 'h', text: 'Три исхода' },
        { t: 'list', items: ['**System crash**', '**Data compromise**', '**Escalation of privileges**'] },
        { t: 'note', variant: 'warn', title: 'Максимальный сценарий', md: 'Такие дефекты памяти могут дать атакующим **полный контроль над устройством цели**: атакующий меняет инструкции уязвимого приложения **в момент, когда программа загружается в память**, и в результате может установить malware и выйти во внутреннюю сеть с заражённого устройства.' },
      ],
    },
    {
      id: '1.5.5', title: 'Buffer overflow statistics', titleRu: 'Статистика', kind: 'text',
      blocks: [
        { t: 'note', variant: 'exam', title: 'Цифра для зачёта', md: 'Исследование **Carnegie Mellon University** оценивает, что **почти половина (nearly half)** всех эксплойтов компьютерных программ происходит от той или иной формы **buffer overflow**.' },
      ],
    },
    {
      id: '1.5.6', title: 'Remote Code Executions', titleRu: 'Удалённое выполнение кода', kind: 'flip',
      blocks: [
        { t: 'def', term: 'Remote code execution', md: 'Allows a cybercriminal to take advantage of application vulnerabilities to **execute any command with the privileges of the user running the application** on the target device.' },
        { t: 'def', term: 'Privilege escalation', md: 'Exploits a **bug, design flaw or misconfiguration** in an operating system or software application to gain access to resources that are **normally restricted**.' },
        { t: 'note', variant: 'tip', md: 'Это два **разных** понятия, а не синонимы.' },
        {
          t: 'flip', title: 'The Metasploit Project',
          cards: [
            { front: 'Metasploit Project', back: 'A computer security project that provides information about security vulnerabilities and **aids in penetration testing**.' },
            { front: 'Metasploit Framework', back: 'A tool for **developing and executing exploit code against a remote target**.' },
            { front: 'Meterpreter', back: 'A **payload within Metasploit** that lets users take control of a target device by writing their own extensions and uploading these files into a running process. The files are **loaded and executed from memory**, never touching the hard drive, so they **fly under the radar of antivirus detection**. Meterpreter also has a module for **controlling a remote system webcam**.' },
          ],
        },
      ],
    },
    {
      id: '1.5.7', title: 'Other Application Attacks', titleRu: 'Прочие атаки на приложения', kind: 'accordion',
      blocks: [
        { t: 'p', md: 'Каждый кусочек информации, который атакующий получает о целевой системе или приложении, может стать ценным оружием для запуска опасной атаки.' },
        {
          t: 'accordion', title: 'Восемь атак',
          items: [
            { title: 'Cross-site request forgery (CSRF)', md: 'Malicious exploit of a website where **unauthorized commands are submitted from a user browser to a trusted web application**.\n\nВредоносный сайт может передавать такие команды через специально созданные **image tags, hidden forms или JavaScript requests** — всё это работает **без ведома пользователя**.' },
            { title: 'Race condition attack', md: 'Also known as a **time of check (TOC)** or **time of use (TOU)** attack. Происходит, когда вычислительная система, рассчитанная на выполнение задач **в определённой последовательности**, вынуждена выполнить **две или более операции одновременно**.\n\nОперационные системы состоят из **threads** — наименьших последовательностей инструкций программы, нужных для выполнения процесса. Когда два или более потока обращаются к общим данным и пытаются изменить их **в один и тот же момент**, возникает race condition.' },
            { title: 'Improper input handling attack', md: 'Данные, введённые пользователем и **не прошедшие должной валидации**, могут повлиять на поток данных программы и вызвать критические уязвимости, которые приводят к **buffer overflow или SQL injection**.' },
            { title: 'Error handling attack', md: 'Атакующие используют **сообщения об ошибках**, чтобы извлечь конкретную информацию: **hostnames внутренних систем**, каталоги и файлы на веб-сервере, а также **имена базы, таблиц и полей**, которые потом используются для построения SQL-инъекций.' },
            { title: 'API attack', md: 'An **API (application programming interface)** delivers a user response to a system and sends the system response back to the user. An API attack occurs when a cybercriminal **abuses an API endpoint**.' },
            { title: 'Replay attack', md: 'Ситуация, когда **валидная передача данных** злонамеренно или мошеннически **повторяется или задерживается** атакующим, который **перехватывает, изменяет и заново отправляет** данные, чтобы заставить получателя сделать то, что ему нужно.' },
            { title: 'Directory traversal attack', md: 'Происходит, когда атакующий может **читать файлы на веб-сервере вне каталога сайта**. Далее он может скачать конфигурационные файлы сервера с чувствительной информацией, найти новые уязвимости сервера или даже **захватить контроль над сервером**.' },
            { title: 'Resource exhaustion attacks', md: 'Эксплойты, которые **крашат, подвешивают или иначе мешают** целевой программе или системе. В отличие от DoS, который забивает **пропускную способность сети**, resource exhaustion забивает **аппаратные ресурсы сервера цели**.' },
          ],
        },
        { t: 'note', variant: 'exam', title: 'Главное различие раздела', md: '**DoS** забивает **network bandwidth**. **Resource exhaustion** забивает **hardware resources сервера**.' },
      ],
    },
    {
      id: '1.5.8', title: 'What Do You Think? (activity)', titleRu: 'Как ты думаешь?', kind: 'activity',
      blocks: [
        { t: 'p', md: '**Сценарий.** Атакующий нашёл уязвимость в сервисе онлайн-сообщений @Apollo, через который общаются сотрудники разных площадок. Когда сотрудник совершает голосовой вызов, это **переполняет память приложения** и фактически даёт атакующему контроль над устройством сотрудника.' },
        {
          t: 'activity', title: 'What type of attack is this?',
          prompt: 'Выбери тип атаки',
          options: ['Buffer overflow', 'Remote code execution', 'Cross-site scripting', 'Resource exhaustion attack'],
          items: [{ q: 'Голосовой вызов переполняет память приложения и даёт контроль над устройством', a: 'Buffer overflow', why: 'Записывая данные за пределы буфера сервиса сообщений, атакующий получает доступ к устройствам сотрудников при каждом голосовом вызове.' }],
          feedback: 'Ловушка: слово flood тянет к resource exhaustion, но там забиваются аппаратные ресурсы сервера, а не память конкретного приложения.',
        },
        { t: 'table', caption: 'Компактный конспект четырёх вариантов', headers: ['Атака', 'Что именно происходит'], rows: [
          ['**Buffer overflow**', 'Данные записываются за пределы буфера, приложение получает доступ к памяти других процессов: crash, компрометация данных, escalation of privileges.'],
          ['Remote code execution', 'Атакующий выполняет любую команду **с правами пользователя**, запустившего приложение.'],
          ['Cross-site scripting', 'Скрипт с вредоносным кодом внедряется в веб-страницу и попадает в браузер жертвы.'],
          ['Resource exhaustion', 'Перегружаются **аппаратные ресурсы сервера** цели.'],
        ] },
      ],
    },
    {
      id: '1.5.9', title: 'Defending Against Application Attacks', titleRu: 'Защита от атак на приложения', kind: 'text',
      blocks: [
        { t: 'note', variant: 'exam', title: 'Первая линия защиты', md: 'The **first line of defense** against an application attack is to **write solid code**. Эта формулировка часто спрашивается дословно.' },
        { t: 'list', items: [
          'Prudent programming practice: **treating and validating all input from outside of a function as if it is hostile**.',
          'Keep all software, including operating systems and applications, **up to date** and do not ignore update prompts.',
          'Remember that **not all programs update automatically**.',
        ] },
      ],
    },
    {
      id: '1.5.10', title: 'Email and browser attacks', titleRu: 'Почта и браузер', kind: 'text',
      blocks: [
        { t: 'p', md: 'Почтой пользуются **миллиарды людей по всему миру**, и именно поэтому email стал крупной уязвимостью для пользователей и организаций.' },
      ],
    },
    {
      id: '1.5.11', title: 'Spam', titleRu: 'Спам', kind: 'text',
      blocks: [
        { t: 'def', term: 'Spam (junk mail)', md: 'Simply **unsolicited email**. В большинстве случаев это способ рекламы. Однако много спама рассылается массово **компьютерами, заражёнными вирусами или червями**, и часто содержит вредоносные ссылки, malware или обманное содержимое, цель которого — выманить чувствительную информацию, например **social security number** или **bank account information**.' },
        { t: 'p', md: 'Почти все почтовые провайдеры фильтруют спам, но он **всё равно потребляет bandwidth**. И даже при включённых средствах безопасности часть спама до вас доходит.' },
        { t: 'h', text: 'Шесть индикаторов спама' },
        { t: 'list', ordered: true, items: [
          'The email has **no subject line**.',
          'The email asks you to **update your account details**.',
          'The email text contains **misspelled words or strange punctuation**.',
          'Links within the email are **long and/or cryptic**.',
          'The email looks like correspondence from a legitimate business, but there are **tiny differences**, or it contains information that **does not seem relevant** to you.',
          'The email asks you to **open an attachment, often urgently**.',
        ] },
        { t: 'note', variant: 'warn', md: 'Если видите хотя бы один индикатор, **не открывайте письмо и вложения**. Во многих организациях политика требует сообщать о таких письмах в cybersecurity team. **If in doubt, always report.**' },
      ],
    },
    {
      id: '1.5.12', title: 'Phishing', titleRu: 'Фишинг', kind: 'flip',
      blocks: [
        { t: 'p', md: 'Phishing — форма мошеннической деятельности, которую часто используют, чтобы украсть личную информацию.' },
        {
          t: 'flip',
          cards: [
            { front: 'Phishing', back: 'Occurs when a user is contacted **by email or instant message, or in any other way, by someone masquerading as a legitimate person or organization**. Цель: заставить установить malware или поделиться личной информацией, такой как **login credentials** или **financial information**.\n\nПример: письмо о выигрыше приза якобы от известного магазина со ссылкой «забрать приз», которая ведёт на поддельный сайт или ставит вирус.' },
            { front: 'Spear phishing', back: 'A **highly targeted** attack: отправка **персонализированных писем конкретному человеку** на основе того, что атакующий о нём знает — интересы, предпочтения, активность, рабочие проекты.\n\nПример: преступник узнал, что вы ищете конкретную модель авто, вступил на форум, где вы состоите, подделал объявление о продаже и прислал письмо со ссылкой «посмотреть фото машины». По клику ставится malware.' },
          ],
        },
        { t: 'note', variant: 'exam', md: '**Phishing** — массово. **Spear phishing** — адресно, с предварительной разведкой. **Whaling** — адресно по высокопоставленным лицам.' },
      ],
    },
    {
      id: '1.5.13', title: 'Vishing, Pharming and Whaling', titleRu: 'Vishing, Pharming, Whaling', kind: 'accordion',
      blocks: [
        {
          t: 'accordion',
          items: [
            { title: 'Vishing', md: 'Often referred to as **voice phishing**: преступники используют **голосовые технологии связи**, чтобы побудить пользователей раскрыть информацию, например **credit card details**.\n\nОни могут подделывать звонки через **VoIP (voice over internet protocol)** или оставлять **записанные сообщения**, чтобы создать впечатление легитимных звонящих.' },
            { title: 'Pharming', md: 'This type of attack **deliberately misdirects users to a fake version of an official website**. Обманутые пользователи, считая, что подключены к легитимному сайту, вводят свои учётные данные на мошенническом сайте.' },
            { title: 'Whaling', md: 'A phishing attack that targets **high profile individuals**, such as **senior executives** within an organization, **politicians** and **celebrities**.' },
          ],
        },
        { t: 'table', caption: 'Быстрый разделитель по каналу', headers: ['Атака', 'Канал'], rows: [
          ['Phishing', 'Email или instant message'],
          ['Vishing', '**Голос** (звонок, VoIP, записанное сообщение)'],
          ['Smishing', '**SMS**, текстовые сообщения'],
          ['Pharming', '**Подменённый сайт**'],
          ['Whaling', 'Крупная цель: руководители, политики, знаменитости'],
        ] },
      ],
    },
    {
      id: '1.5.14', title: 'Gone Phishing (activity)', titleRu: 'Определи канал атаки', kind: 'activity',
      blocks: [
        { t: 'p', md: '**Постановка.** В @Apollo есть политики, требующие сообщать о подозрительной активности в cybersecurity team. Определите тип атаки для каждого сценария.' },
        {
          t: 'activity', title: 'Сопоставь сценарий и тип атаки',
          prompt: 'Варианты в каждом списке: Smishing / Phishing / Vishing',
          options: ['Smishing', 'Phishing', 'Vishing'],
          items: [
            { q: 'Сотрудник получил письмо, похожее на письмо от поставщика @Apollo, с просьбой перейти по ссылке и забрать скидку', a: 'Phishing', why: 'Канал доставки — email.' },
            { q: 'Сотруднику позвонил автоматический голос от лица банка: счёт @Apollo скомпрометирован, надо позвонить на указанный номер и сбросить пароль', a: 'Vishing', why: 'Канал доставки — голосовая связь.' },
            { q: 'Сотрудник получил SMS о том, что подписка @Apollo на ПО истекает и данные надо срочно обновить', a: 'Smishing', why: 'Канал доставки — текстовое сообщение.' },
          ],
          feedback: 'У vishing, smishing и phishing цель одна: доступ к личной и финансовой информации. Различается только способ сбора: vishing использует голосовую связь, smishing текстовые сообщения, phishing email или instant messaging.',
        },
      ],
    },
    {
      id: '1.5.15', title: 'Defending Against Email and Browser Attacks', titleRu: 'Защита почты и браузера', kind: 'text',
      blocks: [
        { t: 'p', md: 'Спам полностью остановить трудно, но его эффект можно снизить.' },
        { t: 'list', ordered: true, items: [
          'Most **Internet service providers (ISPs)** filter spam before it reaches the user inbox.',
          'Many **antivirus and email software programs** automatically detect and remove dangerous spam from an inbox.',
          'Organizations should **educate employees** about the dangers of unsolicited emails and of opening attachments.',
          '**Never assume that email attachments are safe, even when they come from a trusted contact.** Always **scan** attachments before opening them.',
        ] },
        { t: 'def', term: 'APWG (Anti-Phishing Working Group)', md: 'An **international association of companies** focused on **eliminating identity theft and fraud resulting from phishing and email spoofing**. Курс рекомендует стать её членом.' },
        { t: 'p', md: 'Всё ПО должно быть обновлено, с применёнными последними **security patches** против известных уязвимостей.' },
      ],
    },
    {
      id: '1.5.16', title: 'Interim recap', titleRu: 'Промежуточный итог', kind: 'text',
      blocks: [
        { t: 'p', md: 'Переходный экран без нового материала: киберпреступники применяют широкий набор тактик, и дальше идёт ещё одна группа атак.' },
      ],
    },
    {
      id: '1.5.17', title: "There's More...", titleRu: 'И это ещё не всё', kind: 'accordion',
      blocks: [
        {
          t: 'accordion', title: 'Четыре категории',
          items: [
            { title: 'Physical attacks', md: '**Intentional, offensive actions used to destroy, expose, alter, disable, steal or gain unauthorized access to an organization infrastructure or hardware.**\n\nПримеры:\n- Загрузка malware на **USB flash drive**, который заражает устройство при подключении.\n- Оснащение кабелей и разъёмов (обычные USB-кабели, зарядные кабели, настенные и сетевые адаптеры) продвинутыми технологиями, например **wireless chip**, чтобы атакующий мог управлять устройством или отдавать ему команды.\n- Копирование или **skimming** данных с кредитной или дебетовой карты специализированным терминалом для создания **клона карты**.' },
            { title: 'Adversarial artificial intelligence attacks', md: '**Machine learning** — метод автоматизации, позволяющий устройствам проводить анализ и выполнять задачи **без явного программирования**. Он лежит в основе web searching, photo tagging, spam detection, video surveillance, fraud detection и security automation.\n\nМодели предсказывают результат на основе данных. Если данные **tainted (испорчены)**, это негативно влияет на предсказание. Пример: **tainted data обманывает беспилотный автомобиль, и он неверно распознаёт дорожные знаки**.' },
            { title: 'Supply chain attacks', md: 'Многие организации взаимодействуют с третьими сторонами для управления системами или закупки компонентов и ПО, иногда полагаются на зарубежные источники.\n\nАтакующие находят способы **перехватить цепочку поставок**. Пример курса: ПО может зависеть от конкретных соглашений о поддержке и иметь **end-of-life (EOL) date**. Изменение этой даты может означать, что организация **больше не имеет права на сервис и поддержку**.' },
            { title: 'Cloud-based attacks', md: 'Всё больше организаций переходят к облачным вычислениям. Преимущество в том, что оборудование обслуживает провайдер, но это открывает организацию для множества угроз: атакующие постоянно ищут способы эксплуатировать чувствительные данные в облаке, а также приложения, платформы и инфраструктуру — **SaaS, PaaS, IaaS**.' },
          ],
        },
      ],
    },
    {
      id: '1.5.S', title: 'Summary table', titleRu: 'Итоговая таблица 1.5', kind: 'summary',
      blocks: [
        { t: 'table', headers: ['Атака', 'Мишень или вектор', 'Механизм', 'Ключевой результат'], rows: [
          ['Cross-site scripting (XSS)', 'Веб-страница, браузер жертвы', 'Инъекция вредоносного скрипта в страницу', 'Кража cookies и session tokens, имперсонация пользователя'],
          ['XML injection', 'XML-база данных', 'Вмешательство в обработку XML-запроса', 'Порча данных, доступ ко всей информации, изменение сайта'],
          ['SQL injection', 'SQL-база данных', 'Вредоносный SQL в поле ввода, нет фильтрации символов', 'Spoof identity, изменение и удаление данных, права админа БД'],
          ['DLL injection', 'Windows-приложение', 'Приложение обманом вызывает вредоносный DLL', 'Код выполняется как часть целевого процесса'],
          ['LDAP injection', 'LDAP-сервер (directory services)', 'Инъекция запросов через слабую валидацию ввода', 'Извлечение данных из LDAP-каталога'],
          ['Buffer overflow', 'Память приложения', 'Запись за пределы буфера', 'Crash, компрометация данных, escalation of privileges, полный контроль'],
          ['Remote code execution', 'Уязвимое приложение', 'Выполнение произвольной команды', 'Права пользователя, запустившего приложение'],
          ['Privilege escalation', 'ОС или приложение', 'Bug, design flaw, misconfiguration', 'Доступ к обычно закрытым ресурсам'],
          ['CSRF', 'Доверенное веб-приложение', 'Команды из браузера пользователя: image tags, hidden forms, JS', 'Неавторизованные действия без ведома пользователя'],
          ['Race condition (TOC/TOU)', 'Последовательность операций, threads', 'Две и более операции одновременно над общими данными', 'Нарушение логики выполнения'],
          ['Improper input handling', 'Поток данных программы', 'Невалидированный ввод', 'Приводит к buffer overflow или SQL injection'],
          ['Error handling', 'Сообщения об ошибках', 'Сбор hostnames, каталогов, имён БД, таблиц, полей', 'Подготовка SQL-инъекции'],
          ['API attack', 'API endpoint', 'Злоупотребление точкой доступа', 'Компрометация обмена запрос-ответ'],
          ['Replay attack', 'Валидная передача данных', 'Перехват, изменение, повторная отправка', 'Получатель выполняет действие в интересах атакующего'],
          ['Directory traversal', 'Файловая система веб-сервера', 'Чтение файлов вне каталога сайта', 'Конфиги, новые уязвимости, контроль над сервером'],
          ['Resource exhaustion', 'Аппаратные ресурсы сервера', 'Перегрузка ресурсов, а не bandwidth', 'Crash, зависание, помехи работе'],
          ['Spam', 'Почтовый ящик', 'Массовая нежелательная рассылка с заражённых машин', 'Вредоносные ссылки, malware, выманивание данных'],
          ['Phishing', 'Email или instant message', 'Маскировка под легитимное лицо или организацию', 'Установка malware, выдача credentials'],
          ['Spear phishing', 'Конкретный человек', 'Персонализация по интересам и проектам жертвы', 'То же, но с высокой вероятностью успеха'],
          ['Vishing', 'Голосовая связь, VoIP', 'Подменённые звонки, записанные сообщения', 'Выдача, например, credit card details'],
          ['Smishing', 'SMS', 'Сообщение с требованием срочных действий', 'Выдача личных и финансовых данных'],
          ['Pharming', 'Веб-сайт', 'Перенаправление на поддельную копию официального сайта', 'Ввод учётных данных на фальшивом сайте'],
          ['Whaling', 'High profile individuals', 'Целевой фишинг по руководителям, политикам, знаменитостям', 'Доступ к особо ценным аккаунтам'],
          ['Physical attack', 'Инфраструктура и оборудование', 'USB с malware, кабели с чипом, skimming карт', 'Порча, кража, неавторизованный доступ'],
          ['Adversarial AI', 'Модели machine learning', 'Tainted data на входе модели', 'Неверный предсказанный результат'],
          ['Supply chain', 'Третьи стороны, компоненты', 'Перехват цепочки поставок, подмена EOL-даты', 'Потеря поддержки, компрометация ПО и оборудования'],
          ['Cloud-based', 'SaaS, PaaS, IaaS', 'Эксплуатация данных и сервисов в облаке', 'Утечка чувствительных данных'],
        ] },
        { t: 'table', caption: 'Ключи к вопросам раздела', headers: ['Вопрос', 'Ответ'], rows: [
          ['1.5.8 What Do You Think?', '**Buffer overflow**'],
          ['1.5.14 письмо от поставщика со ссылкой на скидку', '**Phishing**'],
          ['1.5.14 автоматический звонок из банка', '**Vishing**'],
          ['1.5.14 SMS об истечении подписки', '**Smishing**'],
        ] },
      ],
    },
  ],
  atoms: [
    /* --- web / injection --- */
    { id: '1.5-x1', lesson: '1.5.2', kind: 'term', group: 'web-attacks', groupLabel: 'Атаки на веб-приложения', weight: 3,
      term: 'Cross-site scripting (XSS)', definition: 'A common web application vulnerability: cybercriminals inject scripts containing malicious code into a web page; when the victim opens it the script passes to their browser, accesses cookies, session tokens or other sensitive information and sends it back, letting the criminal impersonate the user.',
      aliases: ['xss', 'cross site scripting'],
      cloze: '___ injects malicious scripts into a web page so they run in the victim browser and steal cookies and session tokens.',
      ru: 'Скрипт внедряется в страницу и крадёт cookies и session tokens из браузера жертвы.' },
    { id: '1.5-x2', lesson: '1.5.2', kind: 'enum', group: 'web-attacks', groupLabel: 'Атаки на веб-приложения', weight: 3,
      term: 'What an XSS script steals', definition: 'Any cookies, session tokens or other sensitive information about the user, which is sent back to the cybercriminal so they can impersonate the user.',
      items: ['Cookies', 'Session tokens', 'Other sensitive information about the user'],
      decoys: ['The server configuration files', 'The LDAP directory', 'The DNS resolver cache'],
      ru: 'Cookies, session tokens и прочие чувствительные данные пользователя.' },
    { id: '1.5-x3', lesson: '1.5.3', kind: 'term', group: 'injection', groupLabel: 'Инъекции', weight: 3,
      term: 'XML injection attack', definition: 'Corrupts the data on the XML database by interfering with an application processing of XML data or a query entered by a user; criminals manipulate the query to gain access to all the sensitive information stored and to change the website.',
      ru: 'Вмешательство в обработку XML-запроса, портит данные XML-базы.' },
    { id: '1.5-x4', lesson: '1.5.3', kind: 'term', group: 'injection', groupLabel: 'Инъекции', weight: 3,
      term: 'SQL injection attack', definition: 'Inserting a malicious SQL statement in an entry field, taking advantage of an application that does not correctly filter user data for characters in an SQL statement; the criminal can spoof an identity, modify or destroy data, or become an administrator of the database server itself.',
      cloze: 'An ___ inserts a malicious SQL statement in an entry field because the application does not filter user input.',
      ru: 'Вредоносный SQL в поле ввода, приложение не фильтрует символы SQL.' },
    { id: '1.5-x5', lesson: '1.5.3', kind: 'term', group: 'injection', groupLabel: 'Инъекции', weight: 3,
      term: 'DLL injection attack', definition: 'A dynamic link library file contains code and data for a particular activity in Windows; DLL injection tricks an application into calling a malicious DLL file, which executes as part of the target process.',
      ru: 'Приложение обманом вызывает вредоносный DLL, он выполняется в целевом процессе. Только Windows.' },
    { id: '1.5-x6', lesson: '1.5.3', kind: 'term', group: 'injection', groupLabel: 'Инъекции', weight: 3,
      term: 'LDAP injection attack', definition: 'LDAP is an open protocol for authenticating user access to directory services; the attack exploits input validation vulnerabilities by injecting and executing queries to LDAP servers to extract sensitive information from the organization LDAP directory.',
      ru: 'Извлечение данных из LDAP-каталога через слабую валидацию ввода.' },
    { id: '1.5-x7', lesson: '1.5.3', kind: 'fact', group: 'injection', groupLabel: 'Инъекции', weight: 3,
      term: 'What LDAP stands for', definition: 'Lightweight Directory Access Protocol: an open protocol for authenticating user access to directory services.',
      cloze: 'LDAP stands for ___ .', clozeAnswer: 'Lightweight Directory Access Protocol',
      aliases: ['lightweight directory access protocol'], ru: 'Lightweight Directory Access Protocol.' },
    { id: '1.5-x8', lesson: '1.5.3', kind: 'fact', group: 'injection', groupLabel: 'Инъекции', weight: 2,
      term: 'What DLL stands for', definition: 'Dynamic link library: a library that contains a set of code and data for carrying out a particular activity in Windows.',
      cloze: 'DLL stands for ___ .', clozeAnswer: 'dynamic link library',
      aliases: ['dynamic link library'], ru: 'Dynamic link library.' },

    /* --- память и выполнение --- */
    { id: '1.5-b1', lesson: '1.5.4', kind: 'term', group: 'memory', groupLabel: 'Память и выполнение кода', weight: 3,
      term: 'Buffer overflow', definition: 'Occurs when data is written beyond the limits of a buffer, so the application can access memory allocated to other processes; this can lead to a system crash or data compromise, or provide escalation of privileges.',
      cloze: 'A ___ occurs when data is written beyond the limits of a buffer.',
      ru: 'Запись данных за пределы буфера.' },
    { id: '1.5-b2', lesson: '1.5.4', kind: 'enum', group: 'memory', groupLabel: 'Память и выполнение кода', weight: 3,
      term: 'The three outcomes of a buffer overflow', definition: 'A system crash, data compromise, or escalation of privileges.',
      items: ['System crash', 'Data compromise', 'Escalation of privileges'],
      decoys: ['Loss of network bandwidth', 'DNS cache poisoning', 'Domain hijacking'],
      ru: 'Crash, компрометация данных, повышение привилегий.' },
    { id: '1.5-b3', lesson: '1.5.5', kind: 'fact', group: 'memory', groupLabel: 'Память и выполнение кода', weight: 3,
      term: 'The Carnegie Mellon buffer overflow statistic', definition: 'Research by Carnegie Mellon University estimates that nearly half of all exploits of computer programs stem from some form of buffer overflow.',
      cloze: 'Carnegie Mellon research estimates that ___ of all exploits of computer programs stem from buffer overflow.', clozeAnswer: 'nearly half',
      decoys: ['nearly a quarter', 'about 10 percent', 'nearly all'], ru: 'Почти половина эксплойтов, исследование Carnegie Mellon.' },
    { id: '1.5-b4', lesson: '1.5.6', kind: 'term', group: 'memory', groupLabel: 'Память и выполнение кода', weight: 3,
      term: 'Remote code execution', definition: 'Allows a cybercriminal to take advantage of application vulnerabilities to execute any command with the privileges of the user running the application on the target device.',
      aliases: ['rce'], ru: 'Выполнение любой команды с правами запустившего приложение.' },
    { id: '1.5-b5', lesson: '1.5.6', kind: 'term', group: 'memory', groupLabel: 'Память и выполнение кода', weight: 3,
      term: 'Privilege escalation', definition: 'Exploits a bug, design flaw or misconfiguration in an operating system or software application to gain access to resources that are normally restricted.',
      cloze: '___ exploits a bug, design flaw or misconfiguration to reach resources that are normally restricted.',
      ru: 'Доступ к обычно закрытым ресурсам через баг или ошибку конфигурации.' },
    { id: '1.5-b6', lesson: '1.5.6', kind: 'term', group: 'metasploit', groupLabel: 'Metasploit', weight: 3,
      term: 'Metasploit Project', definition: 'A computer security project that provides information about security vulnerabilities and aids in penetration testing.',
      ru: 'Проект по безопасности, помогает в penetration testing.' },
    { id: '1.5-b7', lesson: '1.5.6', kind: 'term', group: 'metasploit', groupLabel: 'Metasploit', weight: 3,
      term: 'Metasploit Framework', definition: 'A tool developed by the Metasploit Project, used for developing and executing exploit code against a remote target.',
      ru: 'Разработка и запуск эксплойтов против удалённой цели.' },
    { id: '1.5-b8', lesson: '1.5.6', kind: 'term', group: 'metasploit', groupLabel: 'Metasploit', weight: 3,
      term: 'Meterpreter', definition: 'A payload within Metasploit that allows users to take control of a target device by uploading their own extensions into a running process; the files are loaded and executed from memory, never involving the hard drive, so they fly under the radar of antivirus detection. It also has a module for controlling a remote system webcam.',
      cloze: '___ is a Metasploit payload whose files are loaded and executed from memory, never touching the hard drive.',
      ru: 'Payload внутри Metasploit, работает из памяти, антивирус его не видит.' },

    /* --- other application attacks --- */
    { id: '1.5-o1', lesson: '1.5.7', kind: 'term', group: 'other-app', groupLabel: 'Прочие атаки на приложения', weight: 3,
      term: 'Cross-site request forgery (CSRF)', definition: 'A malicious exploit of a website where unauthorized commands are submitted from a user browser to a trusted web application, transmitted through specially crafted image tags, hidden forms or JavaScript requests, all without the user knowledge.',
      aliases: ['csrf'], ru: 'Неавторизованные команды из браузера пользователя в доверенное приложение.' },
    { id: '1.5-o2', lesson: '1.5.7', kind: 'enum', group: 'other-app', groupLabel: 'Прочие атаки на приложения', weight: 2,
      term: 'How a malicious site transmits CSRF commands', definition: 'Through specially-crafted image tags, hidden forms or JavaScript requests, all of which work without the user knowledge.',
      items: ['Specially-crafted image tags', 'Hidden forms', 'JavaScript requests'],
      decoys: ['ARP messages', 'DNS zone transfers', 'ICMP packets'], ru: 'Image tags, hidden forms, JavaScript requests.' },
    { id: '1.5-o3', lesson: '1.5.7', kind: 'term', group: 'other-app', groupLabel: 'Прочие атаки на приложения', weight: 3,
      term: 'Race condition attack', definition: 'Also known as a time of check (TOC) or time of use (TOU) attack: a system designed to handle tasks in a specific sequence is forced to perform two or more operations simultaneously, for example when two threads access shared data and try to change it at the exact same time.',
      aliases: ['toc', 'tou', 'time of check attack'],
      cloze: 'A ___ attack, also called TOC or TOU, forces a system to perform two or more operations simultaneously.',
      ru: 'TOC/TOU: две операции выполняются одновременно вместо строгой последовательности.' },
    { id: '1.5-o4', lesson: '1.5.7', kind: 'term', group: 'other-app', groupLabel: 'Прочие атаки на приложения', weight: 2,
      term: 'Thread', definition: 'The smallest sequence of program instructions required to carry out a process; operating systems are made up of threads.',
      ru: 'Наименьшая последовательность инструкций для выполнения процесса.' },
    { id: '1.5-o5', lesson: '1.5.7', kind: 'term', group: 'other-app', groupLabel: 'Прочие атаки на приложения', weight: 3,
      term: 'Improper input handling attack', definition: 'Data inputted by a user that is not properly validated can affect the data flow of a program and cause critical vulnerabilities that result in buffer overflow or SQL injection attacks.',
      ru: 'Невалидированный ввод ведёт к buffer overflow или SQL injection.' },
    { id: '1.5-o6', lesson: '1.5.7', kind: 'term', group: 'other-app', groupLabel: 'Прочие атаки на приложения', weight: 3,
      term: 'Error handling attack', definition: 'Attackers use error messages to extract information such as hostnames of internal systems, directories or files on a web server, and database, table and field names that can be used to craft SQL injection attacks.',
      ru: 'Из сообщений об ошибках достают имена систем, каталогов, баз, таблиц и полей.' },
    { id: '1.5-o7', lesson: '1.5.7', kind: 'term', group: 'other-app', groupLabel: 'Прочие атаки на приложения', weight: 3,
      term: 'API attack', definition: 'An API delivers a user response to a system and sends the system response back to the user; an API attack occurs when a cybercriminal abuses an API endpoint.',
      ru: 'Злоупотребление API endpoint.' },
    { id: '1.5-o8', lesson: '1.5.7', kind: 'term', group: 'other-app', groupLabel: 'Прочие атаки на приложения', weight: 3,
      term: 'Directory traversal attack', definition: 'Occurs when an attacker is able to read files on the webserver outside of the directory of the website, then download server configuration files containing sensitive information, expose more server vulnerabilities or even take control of the server.',
      cloze: 'A ___ attack reads files on the webserver outside of the directory of the website.',
      ru: 'Чтение файлов вне каталога сайта.' },
    { id: '1.5-o9', lesson: '1.5.7', kind: 'term', group: 'other-app', groupLabel: 'Прочие атаки на приложения', weight: 3,
      term: 'Resource exhaustion attack', definition: 'Computer security exploits that crash, hang or otherwise interfere with a targeted program or system; rather than overwhelming network bandwidth like a DoS attack, they overwhelm the hardware resources available on the target server.',
      cloze: 'Unlike a DoS attack that overwhelms network bandwidth, a ___ attack overwhelms the hardware resources of the target server.',
      ru: 'Забивает аппаратные ресурсы сервера, а не пропускную способность сети.' },
    { id: '1.5-o10', lesson: '1.5.7', kind: 'fact', group: 'other-app', groupLabel: 'Прочие атаки на приложения', weight: 3,
      term: 'DoS versus resource exhaustion', definition: 'A DoS attack overwhelms network bandwidth; a resource exhaustion attack overwhelms the hardware resources available on the target server.',
      cloze: 'A DoS attack overwhelms network ___ , a resource exhaustion attack overwhelms hardware resources.', clozeAnswer: 'bandwidth',
      ru: 'Главное различие раздела.' },
    { id: '1.5-o11', lesson: '1.5.9', kind: 'fact', group: 'app-defense', groupLabel: 'Защита приложений', weight: 3,
      term: 'The first line of defense against an application attack', definition: 'The first line of defense against an application attack is to write solid code.',
      cloze: 'The first line of defense against an application attack is to ___ .', clozeAnswer: 'write solid code',
      decoys: ['install a firewall', 'block ICMP packets', 'buy a threat intelligence feed'],
      ru: 'Писать надёжный код.' },
    { id: '1.5-o12', lesson: '1.5.9', kind: 'enum', group: 'app-defense', groupLabel: 'Защита приложений', weight: 3,
      term: 'How to defend against application attacks', definition: 'Write solid code; treat and validate all input from outside of a function as if it is hostile; keep all software including operating systems and applications up to date and remember that not all programs update automatically.',
      items: ['Write solid code', 'Treat and validate all input from outside a function as hostile', 'Keep all software up to date and do not ignore update prompts'],
      decoys: ['Disable input fields', 'Trust input from trusted contacts', 'Run applications as administrator'],
      ru: 'Три меры из 1.5.9.' },

    /* --- email / browser --- */
    { id: '1.5-e1', lesson: '1.5.11', kind: 'term', group: 'email', groupLabel: 'Почта и браузер', weight: 3,
      term: 'Spam', definition: 'Also known as junk mail: unsolicited email, usually advertising; much of it is sent in bulk by computers infected by viruses or worms and contains malicious links, malware or deceptive content aimed at obtaining a social security number or bank account information.',
      aliases: ['junk mail'], ru: 'Нежелательная массовая почта, рассылается заражёнными машинами.' },
    { id: '1.5-e2', lesson: '1.5.11', kind: 'enum', group: 'email', groupLabel: 'Почта и браузер', weight: 3,
      term: 'The six indicators of spam', definition: 'No subject line; asks you to update your account details; misspelled words or strange punctuation; long or cryptic links; looks like a legitimate business but has tiny differences or irrelevant information; asks you to open an attachment, often urgently.',
      items: ['The email has no subject line', 'It asks you to update your account details', 'Misspelled words or strange punctuation', 'Links are long and/or cryptic', 'Looks legitimate but has tiny differences or irrelevant information', 'Asks you to open an attachment, often urgently'],
      decoys: ['The email has an attachment signed by the sender', 'The email arrived during working hours', 'The email has a short subject line'],
      ru: 'Шесть признаков спама.' },
    { id: '1.5-e3', lesson: '1.5.12', kind: 'term', group: 'email', groupLabel: 'Почта и браузер', weight: 3,
      term: 'Phishing', definition: 'Occurs when a user is contacted by email or instant message, or in any other way, by someone masquerading as a legitimate person or organization, with the intent of tricking the recipient into installing malware or sharing personal information such as login credentials or financial information.',
      cloze: '___ is contact by someone masquerading as a legitimate person or organization to get malware installed or credentials shared.',
      ru: 'Маскировка под легитимное лицо ради malware или учётных данных.' },
    { id: '1.5-e4', lesson: '1.5.12', kind: 'term', group: 'email', groupLabel: 'Почта и браузер', weight: 3,
      term: 'Spear phishing', definition: 'A highly targeted attack that sends customized emails to a specific person based on information the attacker knows about them: their interests, preferences, activities and work projects.',
      cloze: '___ sends customized emails to a specific person based on their interests, activities and work projects.',
      ru: 'Адресный фишинг с предварительной разведкой.' },
    { id: '1.5-e5', lesson: '1.5.13', kind: 'term', group: 'phish-kinds', groupLabel: 'Разновидности фишинга', weight: 3,
      term: 'Vishing', definition: 'Voice phishing: criminals use voice communication technology to encourage users to divulge information such as credit card details; they can spoof phone calls using VoIP or leave recorded messages to appear legitimate.',
      aliases: ['voice phishing'], ru: 'Фишинг по голосовой связи.' },
    { id: '1.5-e6', lesson: '1.5.13', kind: 'term', group: 'phish-kinds', groupLabel: 'Разновидности фишинга', weight: 3,
      term: 'Pharming', definition: 'An attack that deliberately misdirects users to a fake version of an official website; tricked into believing they are on a legitimate site, users enter their credentials into the fraudulent website.',
      cloze: '___ deliberately misdirects users to a fake version of an official website.',
      ru: 'Перенаправление на поддельную копию официального сайта.' },
    { id: '1.5-e7', lesson: '1.5.13', kind: 'term', group: 'phish-kinds', groupLabel: 'Разновидности фишинга', weight: 3,
      term: 'Whaling', definition: 'A phishing attack that targets high profile individuals, such as senior executives within an organization, politicians and celebrities.',
      cloze: '___ is a phishing attack that targets high profile individuals such as senior executives, politicians and celebrities.',
      ru: 'Фишинг по высокопоставленным лицам.' },
    { id: '1.5-e8', lesson: '1.5.14', kind: 'bucket', group: 'phish-channel', groupLabel: 'Канал доставки', weight: 3,
      term: 'Uses voice communication technology', definition: 'Vishing uses voice communication technology.', bucket: 'Vishing', ru: 'Голос.' },
    { id: '1.5-e9', lesson: '1.5.14', kind: 'bucket', group: 'phish-channel', groupLabel: 'Канал доставки', weight: 3,
      term: 'Uses text messages', definition: 'Smishing uses text messages.', bucket: 'Smishing', ru: 'SMS.' },
    { id: '1.5-e10', lesson: '1.5.14', kind: 'bucket', group: 'phish-channel', groupLabel: 'Канал доставки', weight: 3,
      term: 'Uses email or instant messaging', definition: 'Phishing uses email or instant messaging.', bucket: 'Phishing', ru: 'Email или IM.' },
    { id: '1.5-e11', lesson: '1.5.15', kind: 'term', group: 'email-defense', groupLabel: 'Защита почты', weight: 3,
      term: 'APWG', definition: 'The Anti-Phishing Working Group: an international association of companies focused on eliminating identity theft and fraud resulting from phishing and email spoofing.',
      aliases: ['anti-phishing working group'],
      cloze: 'APWG stands for ___ .', clozeAnswer: 'Anti-Phishing Working Group',
      ru: 'Международная ассоциация против фишинга и email spoofing.' },
    { id: '1.5-e12', lesson: '1.5.15', kind: 'enum', group: 'email-defense', groupLabel: 'Защита почты', weight: 3,
      term: 'Ways to reduce the effects of spam', definition: 'Most ISPs filter spam before it reaches the inbox; many antivirus and email programs automatically detect and remove dangerous spam; organizations should educate employees about unsolicited emails and attachments; never assume attachments are safe even from a trusted contact and always scan them.',
      items: ['ISPs filter spam before it reaches the inbox', 'Antivirus and email software detect and remove dangerous spam', 'Educate employees about unsolicited emails and attachments', 'Never assume attachments are safe, always scan them'],
      decoys: ['Reply to the sender asking to unsubscribe', 'Forward the email to colleagues', 'Open attachments from trusted contacts without scanning'],
      ru: 'Четыре меры против спама.' },

    /* --- there is more --- */
    { id: '1.5-t1', lesson: '1.5.17', kind: 'term', group: 'more-attacks', groupLabel: 'Ещё четыре категории', weight: 3,
      term: 'Physical attacks', definition: 'Intentional, offensive actions used to destroy, expose, alter, disable, steal or gain unauthorized access to an organization infrastructure or hardware.',
      ru: 'Умышленные действия против инфраструктуры или оборудования.' },
    { id: '1.5-t2', lesson: '1.5.17', kind: 'enum', group: 'more-attacks', groupLabel: 'Ещё четыре категории', weight: 3,
      term: 'Examples of physical attacks', definition: 'Loading malware onto a USB flash drive that infects a device when plugged in; fitting cables, charging cables and power adapters with advanced technologies such as a wireless chip to control a device; copying or skimming data from a credit or debit card with a specialized terminal to create a cloned card.',
      items: ['Malware on a USB flash drive', 'Cables and adapters fitted with a wireless chip', 'Skimming a card to create a cloned card'],
      decoys: ['Injecting a script into a web page', 'Flooding a server with ICMP packets', 'Poisoning a DNS resolver cache'],
      ru: 'USB, кабели с чипом, скимминг карт.' },
    { id: '1.5-t3', lesson: '1.5.17', kind: 'term', group: 'more-attacks', groupLabel: 'Ещё четыре категории', weight: 3,
      term: 'Adversarial artificial intelligence attack', definition: 'Machine learning models are dependent on the data inputted; if the data is tainted it has a negative impact on the predicted outcome. Attackers use tainted data against machine learning algorithms, for example to trick an autonomous vehicle into misinterpreting street signs.',
      cloze: 'Adversarial AI attacks feed ___ data to a machine learning model to distort its predicted outcome.', clozeAnswer: 'tainted',
      ru: 'Испорченные данные ломают предсказание модели.' },
    { id: '1.5-t4', lesson: '1.5.17', kind: 'term', group: 'more-attacks', groupLabel: 'Ещё четыре категории', weight: 3,
      term: 'Supply chain attack', definition: 'Attackers intercept the supply chains organizations use for systems management, components and software; for example, changing an end-of-life (EOL) date could mean an organization is no longer eligible for service and maintenance support.',
      ru: 'Перехват цепочки поставок, пример с подменой EOL-даты.' },
    { id: '1.5-t5', lesson: '1.5.17', kind: 'term', group: 'more-attacks', groupLabel: 'Ещё четыре категории', weight: 2,
      term: 'Cloud-based attacks', definition: 'The cloud provider maintains the equipment, but this opens the organization to threats: attackers constantly leverage ways to exploit sensitive data stored on the cloud as well as cloud-based applications, platforms and infrastructure (SaaS, PaaS, IaaS).',
      ru: 'Эксплуатация данных и сервисов в облаке.' },
    { id: '1.5-t6', lesson: '1.5.17', kind: 'term', group: 'more-attacks', groupLabel: 'Ещё четыре категории', weight: 2,
      term: 'Machine learning', definition: 'A method of automation that allows devices to carry out analysis and perform tasks without specifically being programmed to do so; it powers web searching, photo tagging, spam detection, video surveillance, fraud detection and security automation.',
      ru: 'Автоматизация без явного программирования.' },

    /* --- вопросы курса --- */
    { id: '1.5-q1', lesson: '1.5.8', kind: 'quiz', group: '1.5', groupLabel: 'Вопросы раздела 1.5', weight: 3,
      term: 'Buffer overflow', definition: 'What Do You Think?',
      quiz: { type: 'mcq',
        q: 'An attacker has targeted a vulnerability in @Apollo online messaging service. When an employee makes a voice call, it floods the memory of the application, effectively giving the attacker control over the employee device. What type of attack is this?',
        options: ['Buffer overflow', 'Remote code execution', 'Cross-site scripting', 'Resource exhaustion attack'],
        answers: ['Buffer overflow'],
        why: 'Данные записываются за пределы буфера сервиса сообщений, поэтому приложение получает доступ к памяти других процессов и атакующий получает контроль над устройством.' } },
    { id: '1.5-q2', lesson: '1.5.14', kind: 'quiz', group: '1.5', groupLabel: 'Вопросы раздела 1.5', weight: 3,
      term: 'Phishing · Vishing · Smishing', definition: 'Gone Phishing',
      quiz: { type: 'match',
        q: 'Определи тип атаки для каждого сценария в @Apollo',
        pairs: [
          { item: 'Email, похожий на письмо от поставщика @Apollo, со ссылкой на скидку', match: 'Phishing' },
          { item: 'Автоматический звонок из банка с требованием позвонить по номеру и сбросить пароль', match: 'Vishing' },
          { item: 'SMS об истекающей подписке на ПО с требованием срочно обновить данные', match: 'Smishing' },
        ],
        pool: ['Phishing', 'Vishing', 'Smishing'],
        why: 'Цель у всех трёх одна, различается канал: email или IM это phishing, голос это vishing, текстовые сообщения это smishing.' } },
    { id: '1.5-q3', lesson: '1.5.7', kind: 'quiz', group: '1.5', groupLabel: 'Вопросы раздела 1.5', weight: 3,
      term: 'Resource exhaustion attack', definition: 'DoS против resource exhaustion',
      quiz: { type: 'mcq',
        q: 'Which attack overwhelms the hardware resources available on the target server rather than the network bandwidth?',
        options: ['Resource exhaustion attack', 'DoS attack', 'Directory traversal attack', 'Race condition attack'],
        answers: ['Resource exhaustion attack'],
        why: 'DoS забивает пропускную способность сети, resource exhaustion забивает аппаратные ресурсы сервера.' } },
  ],
}
