import type { Island } from '@/types'

export const island_1_6: Island = {
  id: '1.6',
  moduleId: 1,
  title: 'Cybersecurity Threats, Vulnerabilities, and Attacks Summary',
  titleRu: 'Итоги модуля 1 и квиз',
  objective: 'Recap the whole module and pass the module quiz.',
  icon: 'ShieldAlert',
  lessons: [
    {
      id: '1.6.1', title: 'What Did I Learn in this Module?', titleRu: 'Что я узнал в этом модуле', kind: 'accordion',
      blocks: [
        {
          t: 'accordion', title: 'Пять итоговых блоков курса',
          items: [
            { title: 'Threat Domains', md: 'A **threat domain** is an area of control, authority, or protection that attackers can exploit to gain access to a system. Категории киберугроз: **software attacks and errors, sabotage, human error, theft, hardware failures, utility interruption, natural disasters**.\n\n**Internal threats** обычно исходят от нынешних или бывших сотрудников и контрактных партнёров. **External threats** — от любителей или умелых атакующих, которые эксплуатируют уязвимости сетевых устройств или используют social engineering.\n\n**User domain** включает **любого, у кого есть доступ к информационной системе организации**. Частые угрозы пользователя: плохо соблюдаемые политики безопасности, кража данных, несанкционированные загрузки и носители, несанкционированные VPN и сайты, разрушение систем, приложений или данных. Отдельные устройства, LAN, частные и публичные облака тоже уязвимы. Есть сложные угрозы: **APT** и **algorithm attack**.\n\n**Backdoor** даёт неавторизованный доступ в обход обычных процедур аутентификации и **сохраняет доступ даже после того, как организация починила исходную уязвимость**. **Rootkit** эксплуатирует software vulnerabilities, модифицирует системные файлы и даже **system forensics and monitoring tools**, поэтому его очень трудно обнаружить.\n\n**Dark web** — зашифрованный контент, не индексируемый обычными поисковиками, требует специального ПО, авторизации или конфигурации. **IOC** (malware signatures, domain names) дают доказательства взлома. **AIS** обеспечивает обмен индикаторами угроз в реальном времени с помощью языков **STIX** и **TAXII**.' },
            { title: 'Deception', md: '**Social engineering** — нетехническая стратегия, которая пытается манипулировать людьми, чтобы они выполнили определённые действия или выдали конфиденциальную информацию.\n\n- **Pretexting** — человек лжёт, чтобы получить доступ к привилегированным данным.\n- **Quid pro quo** — запрос личной информации **в обмен на что-то**.\n- **Identity fraud** — использование украденной личности для получения товаров или услуг обманом.\n\nТактики: **impersonating an authority figure, intimidation, consensus («все так делают»), scarcity, urgency, familiarity and trust**.\n\n- **Shoulder surfing** — подсматривание через плечо ради PIN, кодов доступа или данных карты. Преступник не обязан быть рядом: можно использовать **бинокль или камеры наблюдения**.\n- **Dumpster diving** — поиск в мусоре цели.\n- **Piggybacking / tailgating** — проход следом за авторизованным человеком в защищённую зону.\n\nПрочие методы обмана: **invoice scams, watering hole attacks, typosquatting, prepending, influence campaigns**.' },
            { title: 'Cyber Attacks', md: '**Malware** — любой код для кражи данных, обхода access controls, нанесения вреда системе. **Virus** вставляет свой код в другие файлы. **Worm** реплицируется сам, эксплуатируя уязвимости сети. **Trojan horse** маскирует истинное намерение. **Logic bomb** ждёт триггера. **Ransomware** держит систему или данные в заложниках до оплаты.\n\n**DoS** работает через огромный объём трафика или через maliciously formatted packets, которые приложение не может опознать. **DDoS** — то же из множества скоординированных источников. Атаки на DNS включают **spoofing и hijacking**.\n\n**Layer 2 attacks**: MAC address, ARP и IP spoofing, MAC flooding, man-in-the-middle, man-in-the-mobile. **Zero-Day** эксплуатирует уязвимости до того, как о них узнали. **Keylogging** логирует нажатия и отправляет лог-файл преступнику, раскрывая логины, пароли и посещённые сайты.\n\n**Защита:** firewalls, актуальные upgrades и patches, распределение нагрузки между серверами, блокировка внешних ICMP-пакетов на firewall.' },
            { title: 'Wireless and Mobile Device Attacks', md: '**Grayware** — нежелательное приложение с раздражающим поведением. **SMiShing** — поддельные SMS, ведущие на вредоносный сайт или мошеннический номер. **Rogue access point** — беспроводная точка в защищённой сети без авторизации. **Evil twin** — точка атакующего выглядит как более выгодное подключение. **RF jamming** — умышленное глушение передачи.\n\n**Bluejacking** отправляет несанкционированные сообщения или шокирующие изображения на другое Bluetooth-устройство. **Bluesnarfing** копирует информацию с устройства жертвы по Bluetooth. **WEP** и **WPA** — протоколы защиты беспроводных сетей, **WPA2** улучшенный: в отличие от WEP, ключ шифрования **нельзя восстановить наблюдением за трафиком**.\n\n**Защита:** сменить default configurations; размещать AP за firewall или в DMZ; использовать WLAN-инструменты для поиска rogue AP; иметь политику гостевого доступа; сотрудникам использовать remote access VPN.' },
            { title: 'Application and Other Attacks', md: '**XSS** — уязвимость многих веб-приложений. Типы **code injection**: XML, SQL, DLL, LDAP. **Buffer overflow** — запись данных за пределы буфера. **Remote code execution** — выполнение любой команды **с привилегиями авторизованного пользователя**. Прочие: CSRF, race condition, improper input handling, error handling, API, replay, directory traversal, resource exhaustion.\n\n**Защита приложений:** писать solid code, считать любой ввод извне функции враждебным и валидировать, держать ПО обновлённым.\n\n**Spam** — нежелательная почта, обычно реклама, часть рассылается массово компьютерами, заражёнными вирусами или червями. **Phishing** — контакт от лица, выдающего себя за легитимное. **Spear phishing** — персонализированные письма конкретному человеку. Прочие схемы: **vishing, pharming, whaling**. Другие типы атак: физические атаки на оборудование, adversarial AI, supply chain, cloud-based.\n\n**Защита почты и браузера:** антивирус, не считать вложения безопасными, всегда сканировать перед открытием, членство в **APWG**, обновлять всё ПО.' },
          ],
        },
      ],
    },
    {
      id: '1.6.2', title: 'Module 1 Quiz', titleRu: 'Квиз модуля 1', kind: 'activity',
      blocks: [
        { t: 'p', md: '12 вопросов. Ниже формулировки, варианты, правильные ответы и разбор. В этом квизе фидбэк при верном и неверном ответе одинаковый.' },
        { t: 'table', caption: 'Ключи ко всем 12 вопросам', headers: ['№', 'Вопрос кратко', 'Правильный ответ'], rows: [
          ['1', 'Данные выходят за выделенную приложению память', '**Buffer overflow**'],
          ['2', 'Что описывает DDoS', '**A botnet of zombies, coordinated by an attacker, overwhelms a server with DoS attacks**'],
          ['3', 'Медленная сеть после загрузки стороннего сканера для принтера', '**Worm**'],
          ['4', 'БД зашифрована, письмо с требованием оплаты', '**Ransomware**'],
          ['5', 'Pentest нашёл backdoor, что проверить', '**Look for unauthorized accounts**'],
          ['6', 'Non-technical метод сбора данных', '**Social engineering**'],
          ['7', 'Звонящий давит ответственностью и требует срочно выслать файл', '**Intimidation**'],
          ['8', 'Письмо всем: пароль истечёт, сбросьте за 5 минут', '**It is a hoax**'],
          ['9', 'Защита от social engineering (три ответа)', '**Educate employees regarding security policies + Do not provide password resets in a chat window + Resist the urge to click on enticing web links**'],
          ['10', 'Имперсонация через доверенные отношения двух систем', '**Spoofing**'],
          ['11', 'Maliciously formatted packets роняют сервер БД', '**DoS**'],
          ['12', 'Где смотреть детали конкретных уязвимостей', '**CVE national database**'],
        ] },
        { t: 'note', variant: 'exam', title: 'Ловушки квиза', md: '- **RAM injection** и **RAM spoofing** не существуют как термины курса, это дистракторы к buffer overflow.\n- **Packet injection** — дистрактор к DoS.\n- **NIST/NICE framework** — про рабочие роли, **ISO/IEC 27000** — модель управления ИБ, **Infragard** — партнёрство FBI. Детали конкретных уязвимостей только в **CVE**.\n- Во втором вопросе важно слово **botnet of zombies**: просто «огромный объём данных от одного атакующего» — это DoS, а не DDoS.' },
      ],
    },
    {
      id: '1.6.S', title: 'Summary table', titleRu: 'Итоговая таблица модуля 1', kind: 'summary',
      blocks: [
        { t: 'table', headers: ['Понятие', 'Категория', 'Суть', 'С чем путают'], rows: [
          ['Virus', 'Malware', 'Реплицируется, вставляя свой код в другие файлы, нужен запуск', 'Worm'],
          ['Worm', 'Malware', 'Реплицируется сам через уязвимости сети, без участия пользователя, замедляет сеть', 'Virus, Trojan'],
          ['Trojan horse', 'Malware', 'Вредоносные операции под маской истинного назначения', 'Worm'],
          ['Logic bomb', 'Malware', 'Ждёт триггера для срабатывания кода', 'Trojan'],
          ['Ransomware', 'Malware', 'Держит систему или данные в заложниках до оплаты', 'Trojan'],
          ['Backdoor', 'Access', 'Обход normal authentication, доступ сохраняется после фикса исходной уязвимости', 'Rootkit'],
          ['Rootkit', 'Access', 'Модифицирует system files и forensics tools, очень трудно обнаружить', 'Backdoor'],
          ['DoS', 'Availability', 'Один источник: объём трафика или maliciously formatted packets', 'DDoS'],
          ['DDoS', 'Availability', 'Botnet of zombies, множество скоординированных источников', 'DoS'],
          ['Spoofing', 'Impersonation', 'Valid address сети, обход аутентификации, MAC, IP, ARP', 'Sniffing, MITM'],
          ['Man-in-the-middle', 'Layer 2', 'Перехват между сторонами', 'Spoofing'],
          ['Keylogging', 'Spyware', 'Логирует нажатия, отправляет лог-файл атакующему', 'Spyware вообще'],
          ['Zero-Day', 'Exploit', 'Эксплуатация уязвимости до того, как о ней узнали', 'APT'],
          ['APT', 'Complex threat', 'Долгосрочная скрытая операция', 'Algorithm attack'],
          ['Social engineering', 'Non-technical', 'Манипуляция людьми ради действий или конфиденциальных данных', 'Все технические атаки'],
          ['Pretexting', 'Social engineering', 'Ложь ради доступа к привилегированным данным', 'Impersonation'],
          ['Quid pro quo', 'Social engineering', 'Личная информация в обмен на что-то', 'Pretexting'],
          ['Identity fraud', 'Social engineering', 'Использование украденной личности ради товаров или услуг', 'Impersonation'],
          ['Shoulder surfing', 'Physical', 'Подсматривание PIN и кодов, в том числе через бинокль или камеры', 'Dumpster diving'],
          ['Dumpster diving', 'Physical', 'Поиск информации в мусоре', 'Shoulder surfing'],
          ['Piggybacking / tailgating', 'Physical', 'Проход следом за авторизованным человеком', 'Impersonation'],
          ['Hoax', 'Deception', 'Ложное сообщение, вызывает disruption, лишнюю работу и страх', 'Phishing'],
          ['Phishing', 'Email', 'Маскировка под легитимное лицо через email или IM', 'Spam'],
          ['Spear phishing', 'Email', 'Персонализированное письмо конкретному человеку', 'Phishing'],
          ['Whaling, vishing, pharming', 'Email и голос', 'Топ-менеджеры, голосовой канал, подмена сайта', 'Phishing'],
          ['SMiShing', 'Mobile', 'Фальшивые SMS, ведут на вредоносный сайт или номер', 'Phishing'],
          ['Grayware', 'Mobile', 'Нежелательное приложение с раздражающим поведением', 'Malware'],
          ['Rogue access point', 'Wireless', 'Неавторизованная точка доступа в защищённой сети', 'Evil twin'],
          ['Evil twin', 'Wireless', 'Точка атакующего выглядит как лучший вариант подключения', 'Rogue AP'],
          ['RF jamming', 'Wireless', 'Глушение передачи радио или спутникового сигнала', 'DoS'],
          ['Bluejacking', 'Bluetooth', 'Отправка несанкционированных сообщений или изображений', 'Bluesnarfing'],
          ['Bluesnarfing', 'Bluetooth', 'Копирование информации с устройства жертвы', 'Bluejacking'],
          ['WEP, WPA, WPA2', 'Wireless security', 'WPA2 улучшенный, ключ нельзя восстановить наблюдением за трафиком', 'Между собой'],
          ['XSS', 'Application', 'Уязвимость многих веб-приложений', 'Code injection'],
          ['Code injection', 'Application', 'Типы XML, SQL, DLL, LDAP', 'XSS'],
          ['Buffer overflow', 'Application', 'Запись за границы буфера, доступ к чужой памяти', 'SQL injection'],
          ['Remote code execution', 'Application', 'Любая команда с правами авторизованного пользователя', 'Buffer overflow'],
          ['CVE', 'Ресурс', 'Словарь уязвимостей, US-CERT и DHS, ведёт MITRE Corporation', 'NIST/NICE, ISO/IEC 27000, Infragard'],
          ['IOC', 'Threat intel', 'Признаки взлома: malware signatures, domain names', 'AIS'],
          ['AIS, STIX, TAXII', 'Threat intel', 'Обмен индикаторами в реальном времени, STIX и TAXII это языки', 'IOC'],
          ['Dark web', 'Среда', 'Зашифрованный контент вне индексации, нужен спецсофт или авторизация', 'Deep web'],
        ] },
      ],
    },
  ],
  atoms: [
    { id: '1.6-s1', lesson: '1.6.1', kind: 'enum', group: 'module1-recap', groupLabel: 'Итоги модуля 1', weight: 3,
      term: 'The categories of cyber threats', definition: 'Software attacks and errors, sabotage, human error, theft, hardware failures, utility interruption, and natural disasters.',
      items: ['Software attacks and errors', 'Sabotage', 'Human error', 'Theft', 'Hardware failures', 'Utility interruption', 'Natural disasters'],
      decoys: ['Social engineering', 'Zero-day attacks', 'Cloud migration'],
      ru: 'Категории киберугроз из итогов модуля.' },
    { id: '1.6-s2', lesson: '1.6.1', kind: 'term', group: 'module1-recap', groupLabel: 'Итоги модуля 1', weight: 3,
      term: 'Hoax', definition: 'An act intended to deceive or trick someone; this type of email can cause unnecessary disruption, extra work and fear.',
      cloze: 'A ___ is an act intended to deceive or trick someone and causes disruption, extra work and fear.',
      ru: 'Ложное сообщение ради обмана, создаёт лишнюю работу и страх.' },
    { id: '1.6-s3', lesson: '1.6.1', kind: 'term', group: 'module1-recap', groupLabel: 'Итоги модуля 1', weight: 3,
      term: 'Intimidation', definition: 'A social engineering tactic cybercriminals use to bully a victim into taking an action that compromises security.',
      ru: 'Запугивание жертвы ради действия, компрометирующего безопасность.' },
    { id: '1.6-s4', lesson: '1.6.1', kind: 'term', group: 'module1-recap', groupLabel: 'Итоги модуля 1', weight: 3,
      term: 'Pretexting', definition: 'When an individual lies to gain access to privileged data.',
      ru: 'Ложь ради доступа к привилегированным данным.' },
    { id: '1.6-s5', lesson: '1.6.1', kind: 'term', group: 'module1-recap', groupLabel: 'Итоги модуля 1', weight: 3,
      term: 'Quid pro quo', definition: 'A request for personal information in exchange for something.',
      ru: 'Личная информация в обмен на что-то.' },
    { id: '1.6-s6', lesson: '1.6.1', kind: 'fact', group: 'module1-recap', groupLabel: 'Итоги модуля 1', weight: 3,
      term: 'What to check after a penetration test finds a backdoor', definition: 'The organization should check to locate vulnerabilities in the network and also check to see if there are new unauthorized accounts.',
      cloze: 'After a pentest finds a backdoor, look for new ___ .', clozeAnswer: 'unauthorized accounts',
      decoys: ['viruses', 'usernames without passwords', 'policy changes in Event Viewer'],
      ru: 'Искать новые неавторизованные учётные записи.' },
    { id: '1.6-s7', lesson: '1.6.1', kind: 'enum', group: 'module1-recap', groupLabel: 'Итоги модуля 1', weight: 3,
      term: 'Best practices against social engineering attacks', definition: 'Educate employees regarding security policies; do not provide password resets in a chat window; resist the urge to click on enticing web links.',
      items: ['Educate employees regarding security policies', 'Do not provide password resets in a chat window', 'Resist the urge to click on enticing web links'],
      decoys: ['Deploy well-designed firewall appliances', 'Add more security guards', 'Let IT give information over the phone to managers only'],
      ru: 'Три верных пункта из вопроса 9 квиза.' },

    { id: '1.6-q1', lesson: '1.6.2', kind: 'quiz', group: '1.6', groupLabel: 'Квиз модуля 1', weight: 3,
      term: 'Buffer overflow', definition: 'Вопрос 1',
      quiz: { type: 'mcq', q: 'What type of attack occurs when data goes beyond the memory areas allocated to an application?',
        options: ['SQL injection', 'RAM injection', 'RAM spoofing', 'Buffer overflow'], answers: ['Buffer overflow'],
        why: 'Buffer overflow происходит, когда данные записываются за пределы буфера, и приложение получает доступ к памяти других процессов. Итог: crash, компрометация данных или escalation of privileges.' } },
    { id: '1.6-q2', lesson: '1.6.2', kind: 'quiz', group: '1.6', groupLabel: 'Квиз модуля 1', weight: 3,
      term: 'A botnet of zombies overwhelms a server', definition: 'Вопрос 2',
      quiz: { type: 'mcq', q: 'Which of the following statements describes a distributed denial of service (DDoS) attack?',
        options: ['An attacker sends an enormous quantity of data that a server cannot handle', 'An attacker monitors network traffic to learn authentication credentials', 'One computer accepts data packets based on the MAC address of another computer', 'A botnet of zombies, coordinated by an attacker, overwhelms a server with DoS attacks'],
        answers: ['A botnet of zombies, coordinated by an attacker, overwhelms a server with DoS attacks'],
        why: 'В DDoS атакующий использует множество скомпрометированных систем (zombies). Цель перегружена и не может обслуживать запросы других хостов.' } },
    { id: '1.6-q3', lesson: '1.6.2', kind: 'quiz', group: '1.6', groupLabel: 'Квиз модуля 1', weight: 3,
      term: 'Worm', definition: 'Вопрос 3',
      quiz: { type: 'mcq', q: 'Employees report that network access is slow. Investigation reveals that one employee downloaded a third-party scanning program for the printer. What type of malware may have been introduced?',
        options: ['Worm', 'Trojan horse', 'Spam', 'Phishing'], answers: ['Worm'],
        why: 'Червь распространяется по сети и работает без участия пользователя. Типичный симптом это замедление сети.' } },
    { id: '1.6-q4', lesson: '1.6.2', kind: 'quiz', group: '1.6', groupLabel: 'Квиз модуля 1', weight: 3,
      term: 'Ransomware', definition: 'Вопрос 4',
      quiz: { type: 'mcq', q: 'Employees cannot access the customer database; the database file is now encrypted. Shortly afterward the organization receives a threatening email demanding payment for decryption. What type of attack has the organization experienced?',
        options: ['DoS attack', 'Man-in-the-middle attack', 'Ransomware', 'Trojan horse'], answers: ['Ransomware'],
        why: 'Атакующий шифрует диск, данные недоступны, затем требует оплату за расшифровку.' } },
    { id: '1.6-q5', lesson: '1.6.2', kind: 'quiz', group: '1.6', groupLabel: 'Квиз модуля 1', weight: 3,
      term: 'Look for unauthorized accounts', definition: 'Вопрос 5',
      quiz: { type: 'mcq', q: 'A penetration test identified a backdoor on the network. What action should the organization take to find out if their systems have been compromised?',
        options: ['Scan the systems for viruses', 'Look for policy changes in Event Viewer', 'Look for unauthorized accounts', 'Look for usernames that do not have passwords'],
        answers: ['Look for unauthorized accounts'],
        why: 'Надо найти уязвимости в сети и проверить, не появились ли новые неавторизованные учётные записи.' } },
    { id: '1.6-q6', lesson: '1.6.2', kind: 'quiz', group: '1.6', groupLabel: 'Квиз модуля 1', weight: 3,
      term: 'Social engineering', definition: 'Вопрос 6',
      quiz: { type: 'mcq', q: 'What non-technical method could a cybercriminal use to gather sensitive information from an organization?',
        options: ['Man-in-the-middle', 'Ransomware', 'Social engineering', 'Pharming'], answers: ['Social engineering'],
        why: 'Это единственный нетехнический метод из списка: преступник выстраивает доверие или знакомство и получает нужную информацию.' } },
    { id: '1.6-q7', lesson: '1.6.2', kind: 'quiz', group: '1.6', groupLabel: 'Квиз модуля 1', weight: 3,
      term: 'Intimidation', definition: 'Вопрос 7',
      quiz: { type: 'mcq', q: 'A caller claims a manager presentation is corrupted, sternly demands the secretary email the presentation to a personal address, and states the secretary is personally responsible for its success. What social engineering tactic is the caller using?',
        options: ['Trusted partners', 'Familiarity', 'Intimidation', 'Urgency'], answers: ['Intimidation'],
        why: 'Запугивание: жертву давлением заставляют совершить действие, компрометирующее безопасность. Urgency это давление сроком, familiarity это выстроенное доверие.' } },
    { id: '1.6-q8', lesson: '1.6.2', kind: 'quiz', group: '1.6', groupLabel: 'Квиз модуля 1', weight: 3,
      term: 'It is a hoax', definition: 'Вопрос 8',
      quiz: { type: 'mcq', q: 'All employees receive an email stating that their account password will expire immediately and that they should reset it within five minutes. Which statement best describes this email?',
        options: ['It is an impersonation attack', 'It is a piggyback attack', 'It is a hoax', 'It is a DDoS attack'], answers: ['It is a hoax'],
        why: 'Hoax это действие, призванное обмануть. Такое письмо вызывает ненужный переполох, лишнюю работу и страх.' } },
    { id: '1.6-q9', lesson: '1.6.2', kind: 'quiz', group: '1.6', groupLabel: 'Квиз модуля 1', weight: 3,
      term: 'Educate employees · No chat password resets · Do not click enticing links', definition: 'Вопрос 9',
      quiz: { type: 'multi', q: 'Which best practices can help defend against social engineering attacks? Select three correct answers.',
        options: ['Deploy well-designed firewall appliances', 'Add more security guards', 'Educate employees regarding security policies', 'Enable a policy that states that the IT department should supply information over the phone only to managers', 'Do not provide password resets in a chat window', 'Resist the urge to click on enticing web links'],
        answers: ['Educate employees regarding security policies', 'Do not provide password resets in a chat window', 'Resist the urge to click on enticing web links'],
        why: 'Сотрудников надо учить: не кликать ссылки из писем от незнакомых источников, никогда не делиться паролем и не отправлять конфиденциальную информацию под давлением на неизвестный адрес.' } },
    { id: '1.6-q10', lesson: '1.6.2', kind: 'quiz', group: '1.6', groupLabel: 'Квиз модуля 1', weight: 3,
      term: 'Spoofing', definition: 'Вопрос 10',
      quiz: { type: 'mcq', q: 'What do you call an impersonation attack that takes advantage of a trusted relationship between two systems?',
        options: ['Sniffing', 'Spamming', 'Spoofing', 'Man-in-the-middle'], answers: ['Spoofing'],
        why: 'При спуфинге хакеры маскируют свои устройства валидным адресом сети и обходят аутентификацию. Подделывают MAC, IP, а также ARP-связи.' } },
    { id: '1.6-q11', lesson: '1.6.2', kind: 'quiz', group: '1.6', groupLabel: 'Квиз модуля 1', weight: 3,
      term: 'DoS', definition: 'Вопрос 11',
      quiz: { type: 'mcq', q: 'A cybercriminal sends a series of maliciously formatted packets to a database server, which causes the server to crash. What do you call this type of attack?',
        options: ['Packet injection', 'SQL injection', 'DoS', 'Man-in-the-middle'], answers: ['DoS'],
        why: 'При DoS атакующий пытается сделать сервер или другой сетевой ресурс недоступным для легитимных пользователей.' } },
    { id: '1.6-q12', lesson: '1.6.2', kind: 'quiz', group: '1.6', groupLabel: 'Квиз модуля 1', weight: 3,
      term: 'CVE national database', definition: 'Вопрос 12',
      quiz: { type: 'mcq', q: 'Which resource can a cybersecurity specialist use to identify specific details about vulnerabilities?',
        options: ['NIST/NICE framework', 'ISO/IEC 27000 model', 'CVE national database', 'Infragard'], answers: ['CVE national database'],
        why: 'US-CERT и Министерство внутренней безопасности США спонсируют словарь CVE. Каждая запись содержит стандартный идентификатор, краткое описание уязвимости и ссылки на отчёты. Список ведёт некоммерческая MITRE Corporation.' } },
  ],
}
