import type { Island } from '@/types'

export const island_2_1: Island = {
  id: '2.1',
  moduleId: 2,
  title: 'Current State of Affairs',
  titleRu: 'Текущее положение дел',
  objective: 'Explain why networks are targets, what attack vectors exist and how data is lost.',
  icon: 'Radar',
  lessons: [
    {
      id: '2.1.1', title: 'Video — Anatomy of an Attack', titleRu: 'Видео: анатомия атаки', kind: 'video',
      blocks: [
        { t: 'p', md: 'Кейс: атака на **Aupticon**, разработчика беспилотных автомобилей. Исполнитель **Brian Page**, арестован ФБР.' },
        { t: 'h', text: 'Цепочка атаки по шагам' },
        { t: 'list', ordered: true, items: [
          '**OSINT в соцсетях**: имена инженеров исследовательского центра на полуострове, которые работают над optical tracking cameras.',
          'Найдена **боулинг-лига**, где команды техкомпаний играют каждую среду. У клуба очень старый сайт с информацией о лиге, названиями компаний и игроками.',
          'Взлом стороннего сайта боулинга и установка **iframe injection attack** (это watering hole): заражается любой посетитель сайта.',
          'Через неделю malware оказывается на ноутбуке сотрудника Aupticon. На следующий день ноутбук подключается к корпоративной сети, и атакующий внутри.',
          'Ноутбук обнаружили и очистили (wiped), сеть просканировали, но **термостат не сканировали**. Термостат (IoT) внутри периметра за firewall, подключён ко всей сети. Стандартная конфигурация и пароль есть на сайте производителя, находится за 30 секунд.',
          'Сеть оказалась **totally flat network, без подсетей**, поэтому видно всё: HR files, legal documents, R&D и чертежи (blueprints).',
          'Эксфильтрация чертежей и продажа за **75 Bitcoins**.',
          'Заметание следов: wiped everything, encrypted drives, deleted backups. Восстановление невозможно, бэкапы зашифрованы.',
        ] },
        { t: 'note', variant: 'exam', title: 'Итог', md: 'Конкурент **QCAR** вышел на рынок первым с седаном **QX**, акции Aupticon упали на **11 процентов**.' },
        { t: 'note', variant: 'tip', title: 'Ключевые уязвимости кейса', md: 'Слабое звено у третьей стороны, IoT с дефолтными учётными данными, отсутствие сегментации сети, неполный охват при сканировании после инцидента.' },
        {
          t: 'transcript', title: 'Транскрипт видео (фрагменты)',
          lines: [
            { text: '**[Male Reporter]** The race is on to get a fully self-driving car to market.' },
            { text: '**[Man]** He’s destroyed data and deleted the backups, we can recover most of it, but some of the research may be gone for good. According to forensics, they may have had access to the blueprints.' },
            { text: '**[Detective]** So, walk me through it, step by step.' },
            { text: '**[Brian]** Well, I took over the website to a bowling alley. They have this research facility down in the peninsula, and they’re working on optical tracking cameras for driverless cars. So, just searching through social media I get the names of a whole bunch of engineers who are working there.' },
            { text: '**[Brian]** It’s called an iframe injection attack, it’s this old exploit that hits anyone that visits the website. So, a week later, this guy from Aupticon suddenly has my malware on his laptop.' },
            { text: '**[Brian]** They didn’t scan the whole network. The thermostat’s part of the network. It’s inside the firewall, it’s connected to Aupticon’s entire network. You can get the whole standard configuration and password online in 30 seconds.' },
            { text: '**[Brian]** Then I just went exploring. It was a totally flat network, no subnets or anything. I could see everything: HR files, legal documents, R&D. When I found the blueprints, I realized I could make some money off these files.' },
            { text: '**[Brian]** Well, then I burned everything down. I wiped everything I could find, I encrypted drives, and deleted backups.' },
            { text: '**[Detective]** And somebody paid you how much exactly? **[Brian]** 75 Bitcoins.' },
            { text: '**[News Reporter]** European automaker QCAR has beaten Aupticon to market with their QX sedan, the world’s first self-driving car. Aupticon shares tumbled 11 percent.' },
          ],
        },
      ],
    },
    {
      id: '2.1.2', title: 'Networks Are Targets', titleRu: 'Сети как цели', kind: 'text',
      blocks: [
        { t: 'p', md: 'Сети атакуют постоянно. Поиск по запросу network attacks выдаёт множество статей: скомпрометированные организации, новейшие угрозы сетевой безопасности, инструменты митигации и так далее.' },
        { t: 'def', term: 'Kapersky Cyberthreat Real-Time Map', md: 'Интерактивная карта сетевых атак в реальном времени. Данные поступают от продуктов сетевой безопасности Kapersky, развёрнутых по всему миру. (В оригинале курса написано именно «Kapersky».)' },
        { t: 'note', variant: 'info', md: 'Общее название класса таких инструментов — **cyberthreat maps**, их в интернете много.' },
        { t: 'figure', caption: 'Скриншот интерактивной карты Cyberthreat Real-Time Map с атаками в реальном времени.' },
      ],
    },
    {
      id: '2.1.3', title: 'Reasons for Network Security', titleRu: 'Зачем нужна сетевая безопасность', kind: 'text',
      blocks: [
        { t: 'p', md: 'Сетевая безопасность напрямую связана с **business continuity** организации.' },
        { t: 'h', text: 'Последствия breaches' },
        { t: 'list', items: [
          'Disrupt e-commerce.', 'Loss of business data.', 'Threaten people’s privacy.', 'Compromise the integrity of information.',
        ] },
        { t: 'h', text: 'Результаты для организации' },
        { t: 'list', items: ['Lost revenue.', 'Theft of intellectual property.', 'Lawsuits.', 'Threat to public safety.'] },
        { t: 'p', md: 'Безопасная сеть защищает и пользователей, и коммерческие интересы. Она требует постоянной бдительности специалистов, знания новых угроз, атак и уязвимостей устройств и приложений.' },
        { t: 'table', caption: 'Две организации Cisco, которые надо различать', headers: ['Организация', 'Чем занимается'], rows: [
          ['**Cisco Talos Intelligence Group**', 'Сайт с комплексной security and threat intelligence, помогает защищать клиентов и их активы. Это про угрозы в целом.'],
          ['**Cisco PSIRT (Product Security Incident Response Team)**', 'Расследует и устраняет потенциальные уязвимости **в продуктах Cisco**. Публикует страницу Cisco Security Advisories со списком уязвимостей в реальном времени и информацией для митигации.'],
        ] },
      ],
    },
    {
      id: '2.1.4', title: 'Vectors of Network Attacks', titleRu: 'Векторы сетевых атак', kind: 'text',
      blocks: [
        { t: 'def', term: 'Attack vector', md: 'A path by which a threat actor can gain access to a server, host, or network. Attack vectors originate from **inside or outside** the corporate network.' },
        { t: 'note', variant: 'info', title: 'Note из курса', md: 'A **DoS attack** occurs when a network device or application is **incapacitated** and no longer capable of supporting requests from legitimate users.' },
        { t: 'figure', caption: 'Схема External and Internal Threats с подписями: Internet, External Threat, Compromised Host, Internal Threat.' },
        { t: 'h', text: 'Что может сделать внутренний пользователь, случайно или намеренно' },
        { t: 'list', ordered: true, items: [
          'Steal and copy confidential data to removable media, email, messaging software, and other media.',
          'Compromise internal servers or network infrastructure devices.',
          'Disconnect a critical network connection and cause a network outage.',
          'Connect an infected USB drive into a corporate computer system.',
        ] },
        { t: 'note', variant: 'exam', md: 'Внутренние угрозы потенциально наносят **больший** ущерб, чем внешние, потому что у внутренних пользователей есть прямой доступ к зданию и инфраструктурным устройствам, плюс знание корпоративной сети, её ресурсов и конфиденциальных данных. Специалист обязан митигировать **обе** категории.' },
      ],
    },
    {
      id: '2.1.5', title: 'Data Loss', titleRu: 'Потеря данных', kind: 'accordion',
      blocks: [
        { t: 'p', md: 'Данные — вероятно самый ценный актив организации: research and development, sales, financial, human resource and legal, employee, contractor и customer data.' },
        { t: 'def', term: 'Data loss (data exfiltration)', md: 'When data is intentionally or unintentionally lost, stolen, or leaked to the outside world.' },
        { t: 'h', text: '6 последствий data loss' },
        { t: 'list', items: [
          'Brand damage and loss of reputation.',
          'Loss of competitive advantage.',
          'Loss of customers.',
          'Loss of revenue.',
          'Litigation or legal action that results in fines and civil penalties.',
          'Significant cost and effort to notify affected parties and recover from the breach.',
        ] },
        { t: 'p', md: 'Специалисты обязаны защищать данные организации. Внедряются разные **Data Loss Prevention (DLP) controls**, сочетающие **strategic, operational и tactical** меры.' },
        {
          t: 'accordion', title: '6 векторов потери данных',
          items: [
            { title: 'Email / Social Networking', md: '**Самый распространённый** вектор потери данных, включает instant messaging software и соцсети. Перехваченные email или IM могут раскрыть конфиденциальную информацию.' },
            { title: 'Unencrypted Devices', md: 'Украденный корпоративный ноутбук обычно содержит конфиденциальные данные. Если данные не зашифрованы алгоритмом шифрования, вор получит их.' },
            { title: 'Cloud Storage Devices', md: 'Сохранение данных в облаке даёт много выгод, но чувствительные данные могут быть потеряны, если доступ к облаку скомпрометирован из-за **weak security settings**.' },
            { title: 'Removable Media', md: 'Один риск: сотрудник выполняет несанкционированный перенос данных на USB. Другой риск: USB с ценными корпоративными данными потерян.' },
            { title: 'Hard Copy', md: 'Корпоративные данные нужно уничтожать тщательно. Конфиденциальные документы следует **shred**, иначе вор достанет выброшенные отчёты.' },
            { title: 'Improper Access Control', md: 'Пароли это **первая линия обороны**. Украденные или слабые скомпрометированные пароли дают атакующему лёгкий доступ к корпоративным данным.' },
          ],
        },
        { t: 'note', variant: 'exam', title: 'Ловушка на зачёте', md: '«Most common vector» = **Email / Social Networking**. «First line of defense» = **passwords**.' },
      ],
    },
    {
      id: '2.1.6', title: 'PT Video — Investigate a Threat Landscape', titleRu: 'Видео Packet Tracer', kind: 'video',
      blocks: [
        { t: 'def', term: 'Threat landscape', md: 'Consists of all the vulnerabilities that can be exploited by threat actors. Every cybersecurity incident involves the exploitation of vulnerabilities.' },
        { t: 'p', md: '**Мотивы threat actors:** деньги, слава, разрушение информации и инфраструктуры.' },
        { t: 'p', md: '**Топология:** город Greenville. Data center и ISP заблокированы для этой активности. Используются Branch Office, Cafe, Home.' },
        { t: 'h', text: 'Part 1 — network configuration vulnerability' },
        { t: 'list', items: [
          'Персонажи: **Mary** (знакома с penetration testing, smartphone 3, снаружи дома) и **Bob** (владелец дома).',
          'Инструмент сканирования в Packet Tracer: **InMAP**, находит активные устройства.',
          'Webcam в домашней сети: **192.168.100.101**, её пингуют командой `ping 192.168.100.101`.',
          'Default gateway (домашний роутер): **192.168.100.1**, узнаётся через `ipconfig` на home office PC.',
          'Учётные данные роутера по умолчанию: **admin / admin**, найдены по модели в интернете.',
          'У роутера **три радио**, все активны: два SSID **HomeNet** и один SSID **Guest**.',
          'Security включена только на двух HomeNet. Guest активна, разрешает доступ к другим устройствам сети и **без security**.',
        ] },
        { t: 'note', variant: 'tip', title: 'Решение Part 1', md: 'Guest network отключить либо настроить базовую безопасность: **strong authentication, SSID broadcast disabled, access to local network devices disabled**.' },
        { t: 'h', text: 'Part 2 — phishing malware vulnerability' },
        { t: 'list', items: [
          '**Phishing** — вид social engineering: злоумышленник выдаёт себя за легитимный доверенный источник, чтобы заставить установить malware или выдать личные и финансовые данные. Каналы: email и телефонные звонки.',
          '**Главная уязвимость в phishing это сами пользователи**, поэтому главная защита это обучение (training).',
          'Ссылка-приманка: **pix.example.com**. Письмо от «PIX Security Team», отправляется трём людям в branch office, открывается на **laptop BR2**.',
          'Результат: сообщение о зашифрованном жёстком диске и требование **$600**, то есть **ransomware attack**.',
          'Меры защиты: обучение сотрудников; firewalls, intrusion prevention systems и другие устройства для блокировки фишинговых писем; подписка на сервисы со списками вредоносных сайтов для автоматического обновления фильтров.',
        ] },
        { t: 'note', variant: 'warn', md: 'Курс подчёркивает: это демонстрация в симулированной среде. Написание и отправка фишинговых сообщений неэтичны и в большинстве юрисдикций считаются преступлением.' },
        { t: 'h', text: 'Part 3 — wireless and DNS vulnerability' },
        { t: 'list', items: [
          'Threat actor настраивает ноутбук с WiFi-интерфейсом, который работает **и как access point, и как client**, и вещает убедительный SSID. Это **rogue access point**, используется для **man in the middle attack**: перехват и чтение всего беспроводного трафика, кража username, password и другой конфиденциальной информации.',
          'В рюкзаке хакера: **wireless router** и **network sniffer**.',
          'Открытые сети-приманки: **Cafe WiFi Fast** (три штуки, без security). Легитимная сеть **Cafe WiFi** с security.',
          'Сайт-приманка: **friends.example.com**, выдаёт то же сообщение ransomware.',
          'DNS на VPN laptop (легитимный): **10.2.0.125**, сеть 0. DNS на cafe customer: **192.168.10.199**, сеть 10, это IP-адрес cafe hacker laptop.',
          'Вредоносный сервер: **10.6.0.250**, тот же, что и для pix.example.com.',
        ] },
        { t: 'note', variant: 'exam', title: 'Механизм DNS hijacking', md: 'Подключение к rogue AP → DHCP хакера выдаёт свой адрес как DNS server → DNS хакера резолвит friends.example.com в 10.6.0.250 → трафик уходит на вредоносный сервер → устанавливается ransomware, файлы шифруются.' },
      ],
    },
    {
      id: '2.1.7', title: 'Packet Tracer — Investigate a Threat Landscape', titleRu: 'Активность Packet Tracer', kind: 'lab',
      blocks: [
        { t: 'h', text: 'Objectives' },
        { t: 'list', items: ['Part 1: Investigate a Network Configuration Vulnerability', 'Part 2: Investigate a Phishing Malware Vulnerability', 'Part 3: Investigate a Wireless Network and DNS Vulnerability'] },
        { t: 'p', md: 'Файл активности: `Investigate a Threat Landscape.pka`. Отдельного текстового файла с инструкциями курс не отдаёт: пошаговые инструкции встроены внутрь Packet Tracer, а полный разбор есть в транскрипте видео 2.1.6.' },
        { t: 'h', text: 'Топология в текстовом виде' },
        { t: 'list', items: [
          'Город **Greenville**. Заблокированы: **Data Center**, **ISP**. Используются: **Branch Office**, **Cafe**, **Home**.',
          '**Home**: home wireless router (192.168.100.1), home office PC, webcam (192.168.100.101); снаружи smartphone 3 (Mary). Роутер: 3 радио, SSID HomeNet x2 (с security), SSID Guest x1 (без security).',
          '**Branch Office**: три устройства-получателя фишингового письма, среди них laptop BR2.',
          '**Cafe**: hacker laptop (192.168.10.199, роли DHCP + DNS + rogue AP, SSID Cafe WiFi Fast x3 без security), cafe customer laptop, VPN laptop, легитимная сеть Cafe WiFi с security. В рюкзаке хакера: wireless router, network sniffer.',
          '**Malicious server**: 10.6.0.250, за ним стоят и pix.example.com, и friends.example.com.',
        ] },
        { t: 'table', caption: 'Таблица адресации', headers: ['Устройство или параметр', 'Адрес'], rows: [
          ['Home wireless router (default gateway)', '`192.168.100.1`'],
          ['Webcam в домашней сети', '`192.168.100.101`'],
          ['Cafe hacker laptop (он же rogue DNS для жертвы)', '`192.168.10.199`'],
          ['DNS server на cafe customer laptop', '`192.168.10.199`'],
          ['DNS server на VPN laptop (легитимный)', '`10.2.0.125`'],
          ['Malicious server (pix.example.com и friends.example.com)', '`10.6.0.250`'],
        ] },
        { t: 'h', text: 'Вопросы для размышления' },
        { t: 'p', md: 'Курс предлагает подумать, какими способами подобные уязвимости можно обнаружить и митигировать до того, как произойдёт кибератака.' },
        { t: 'list', ordered: true, items: [
          'Сегментация и отключение или защита гостевой сети, смена дефолтных учётных данных, инвентаризация и сканирование всех устройств включая IoT.',
          'Обучение пользователей, фильтрация почты, IPS, списки вредоносных сайтов.',
          'Отказ от доверия открытым WiFi, использование VPN, проверка выданного по DHCP DNS-сервера, контроль rogue access points.',
        ] },
        { t: 'note', variant: 'info', title: 'Про оценивание', md: 'В разделе 2.1 нет оценочных вопросов: в боковом меню он засчитывается как 7 / 7, все семь пунктов это контентные подразделы. Компонентов типа mcq, matching, drag-and-drop и hotspot здесь нет. Вопросы по этому материалу появляются в **2.3 Securing Networks Summary** и в **Checkpoint Exam: Network Security**.' },
      ],
    },
    {
      id: '2.1.S', title: 'Summary table', titleRu: 'Итоговая таблица 2.1', kind: 'summary',
      blocks: [
        { t: 'table', headers: ['Понятие', 'Определение из курса', 'Что запомнить'], rows: [
          ['Attack vector', 'Путь, по которому threat actor получает доступ к server, host или network', 'Бывает external и internal'],
          ['External threat', 'Атака извне корпоративной сети, например через интернет', 'Типичный пример: DoS'],
          ['Internal threat', 'Действия внутреннего пользователя, случайные или намеренные', 'Потенциально опаснее внешних: прямой физический доступ плюс знание сети и данных'],
          ['DoS attack', 'Устройство или приложение выведено из строя и не обслуживает запросы легитимных пользователей', 'Это следствие вектора, а не сам вектор'],
          ['Data loss / data exfiltration', 'Данные намеренно или ненамеренно потеряны, украдены или утекли наружу', 'Два названия одного явления'],
          ['DLP controls', 'Меры защиты данных', 'Сочетают strategic, operational, tactical'],
          ['Email / Social Networking', 'Вектор потери данных через IM и соцсети', '**Самый распространённый** вектор data loss'],
          ['Unencrypted Devices', 'Украденный ноутбук без шифрования', 'Решается encryption algorithm'],
          ['Cloud Storage Devices', 'Утечка из облака', 'Причина: weak security settings'],
          ['Removable Media', 'Несанкционированный перенос на USB или потеря USB', 'Два разных риска в одном векторе'],
          ['Hard Copy', 'Выброшенные бумажные документы', 'Решение: shredding'],
          ['Improper Access Control', 'Украденные или слабые пароли', 'Пароли = **first line of defense**'],
          ['Cisco Talos Intelligence Group', 'Security and threat intelligence для защиты клиентов', 'Про угрозы в целом'],
          ['Cisco PSIRT', 'Расследует и устраняет уязвимости в продуктах Cisco', 'Публикует Cisco Security Advisories'],
          ['Kapersky Cyberthreat Real-Time Map', 'Интерактивная карта атак в реальном времени', 'Данные от продуктов Kapersky по всему миру'],
          ['Phishing', 'Social engineering, злоумышленник маскируется под доверенный источник', 'Основная уязвимость это пользователь'],
          ['Ransomware', 'Шифрование диска с требованием выкупа', 'В активности выкуп $600'],
          ['Rogue access point', 'Ноутбук хакера как AP и client одновременно, вещает убедительный SSID', 'Инструмент для man in the middle'],
          ['DNS hijacking', 'Подмена DNS через свой DHCP и свою DNS-запись', 'Трафик уводится на malicious server'],
          ['iframe injection attack', 'Эксплойт на взломанном стороннем сайте, заражает всех посетителей', 'Из кейса 2.1.1, watering hole'],
          ['Flat network', 'Сеть без подсетей и сегментации', 'Позволила увидеть HR, legal, R&D и чертежи'],
        ] },
      ],
    },
  ],
  atoms: [
    { id: '2.1-v1', lesson: '2.1.4', kind: 'term', group: 'net-core', groupLabel: 'Базовые понятия 2.1', weight: 3,
      term: 'Attack vector', definition: 'A path by which a threat actor can gain access to a server, host, or network; vectors originate from inside or outside the corporate network.',
      cloze: 'An ___ is a path by which a threat actor can gain access to a server, host, or network.',
      ru: 'Путь доступа threat actor к серверу, хосту или сети.' },
    { id: '2.1-v2', lesson: '2.1.4', kind: 'term', group: 'net-core', groupLabel: 'Базовые понятия 2.1', weight: 3,
      term: 'DoS attack', definition: 'Occurs when a network device or application is incapacitated and no longer capable of supporting requests from legitimate users.',
      cloze: 'A ___ occurs when a device or application can no longer support requests from legitimate users.', aliases: ['denial of service attack', 'DoS'],
      ru: 'Устройство или приложение выведено из строя и не обслуживает легитимных пользователей.' },
    { id: '2.1-v3', lesson: '2.1.5', kind: 'term', group: 'net-core', groupLabel: 'Базовые понятия 2.1', weight: 3,
      term: 'Data loss', definition: 'Also called data exfiltration: when data is intentionally or unintentionally lost, stolen, or leaked to the outside world.',
      cloze: '___ , also called data exfiltration, is when data is lost, stolen or leaked to the outside world.', aliases: ['data exfiltration', 'data loss'],
      ru: 'Данные потеряны, украдены или утекли наружу. Второе имя: data exfiltration.' },
    { id: '2.1-v4', lesson: '2.1.5', kind: 'term', group: 'net-core', groupLabel: 'Базовые понятия 2.1', weight: 3,
      term: 'DLP controls', definition: 'Data Loss Prevention controls that combine strategic, operational and tactical measures to protect the organization’s data.',
      cloze: 'DLP controls combine strategic, operational and ___ measures.', clozeAnswer: 'tactical',
      ru: 'Меры защиты данных: стратегические, операционные и тактические.' },
    { id: '2.1-v5', lesson: '2.1.6', kind: 'term', group: 'net-core', groupLabel: 'Базовые понятия 2.1', weight: 3,
      term: 'Threat landscape', definition: 'All the vulnerabilities that can be exploited by threat actors; every cybersecurity incident involves the exploitation of vulnerabilities.',
      cloze: 'The ___ consists of all the vulnerabilities that can be exploited by threat actors.',
      ru: 'Совокупность всех эксплуатируемых уязвимостей.' },
    { id: '2.1-v6', lesson: '2.1.3', kind: 'term', group: 'net-core', groupLabel: 'Базовые понятия 2.1', weight: 2,
      term: 'Business continuity', definition: 'Network security relates directly to an organization’s business continuity; breaches can disrupt e-commerce, cause loss of business data, threaten privacy and compromise the integrity of information.',
      ru: 'Непрерывность бизнеса, с которой напрямую связана сетевая безопасность.' },

    { id: '2.1-l1', lesson: '2.1.5', kind: 'term', group: 'data-loss-vectors', groupLabel: '6 векторов потери данных', weight: 3,
      term: 'Email / Social Networking', definition: 'The most common vector for data loss; includes instant messaging software and social media sites, where intercepted email or IM messages could reveal confidential information.',
      ru: 'Самый распространённый вектор потери данных.' },
    { id: '2.1-l2', lesson: '2.1.5', kind: 'term', group: 'data-loss-vectors', groupLabel: '6 векторов потери данных', weight: 3,
      term: 'Unencrypted Devices', definition: 'A stolen corporate laptop typically contains confidential data; if the data is not stored using an encryption algorithm, the thief can retrieve it.',
      ru: 'Украденный ноутбук без шифрования.' },
    { id: '2.1-l3', lesson: '2.1.5', kind: 'term', group: 'data-loss-vectors', groupLabel: '6 векторов потери данных', weight: 3,
      term: 'Cloud Storage Devices', definition: 'Sensitive data can be lost if access to the cloud is compromised due to weak security settings.',
      ru: 'Утечка из облака из-за слабых настроек безопасности.' },
    { id: '2.1-l4', lesson: '2.1.5', kind: 'term', group: 'data-loss-vectors', groupLabel: '6 векторов потери данных', weight: 3,
      term: 'Removable Media', definition: 'An employee could perform an unauthorized transfer of data to a USB drive, or a USB drive containing valuable corporate data could be lost.',
      ru: 'Два риска: несанкционированный перенос и потеря флешки.' },
    { id: '2.1-l5', lesson: '2.1.5', kind: 'term', group: 'data-loss-vectors', groupLabel: '6 векторов потери данных', weight: 3,
      term: 'Hard Copy', definition: 'Corporate data should be disposed of thoroughly and confidential data should be shredded when no longer required, otherwise a thief could retrieve discarded reports.',
      ru: 'Бумажные документы, решение — шредер.' },
    { id: '2.1-l6', lesson: '2.1.5', kind: 'term', group: 'data-loss-vectors', groupLabel: '6 векторов потери данных', weight: 3,
      term: 'Improper Access Control', definition: 'Passwords are the first line of defense; stolen or weak passwords which have been compromised can provide an attacker easy access to corporate data.',
      ru: 'Пароли это первая линия обороны.' },
    { id: '2.1-l7', lesson: '2.1.5', kind: 'fact', group: 'data-loss-facts', groupLabel: 'Ловушки 2.1.5', weight: 3,
      term: 'The first line of defense', definition: 'Passwords are the first line of defense.',
      cloze: '___ are the first line of defense.', clozeAnswer: 'Passwords', aliases: ['passwords'],
      decoys: ['Firewalls', 'Antivirus software', 'Encryption'], ru: 'Первая линия обороны это пароли.' },
    { id: '2.1-l8', lesson: '2.1.5', kind: 'enum', group: 'data-loss-facts', groupLabel: 'Ловушки 2.1.5', weight: 3,
      term: 'The 6 consequences of data loss', definition: 'Brand damage and loss of reputation; loss of competitive advantage; loss of customers; loss of revenue; litigation or legal action resulting in fines and civil penalties; significant cost and effort to notify affected parties and recover from the breach.',
      items: ['Brand damage and loss of reputation', 'Loss of competitive advantage', 'Loss of customers', 'Loss of revenue', 'Litigation resulting in fines and civil penalties', 'Cost and effort to notify affected parties and recover'],
      decoys: ['Hard drive crashes', 'Power outages', 'Compliance certification'],
      ru: 'Шесть последствий потери данных.' },
    { id: '2.1-o1', lesson: '2.1.3', kind: 'term', group: 'cisco-orgs', groupLabel: 'Организации и инструменты', weight: 3,
      term: 'Cisco Talos Intelligence Group', definition: 'Provides comprehensive security and threat intelligence to defend customers and protect their assets; it is about threats in general.',
      ru: 'Про угрозы в целом.' },
    { id: '2.1-o2', lesson: '2.1.3', kind: 'term', group: 'cisco-orgs', groupLabel: 'Организации и инструменты', weight: 3,
      term: 'Cisco PSIRT', definition: 'Product Security Incident Response Team: responsible for investigating and mitigating potential vulnerabilities in Cisco products, and publishes the Cisco Security Advisories page.',
      aliases: ['product security incident response team'], ru: 'Уязвимости именно в продуктах Cisco, публикует Security Advisories.' },
    { id: '2.1-o3', lesson: '2.1.2', kind: 'term', group: 'cisco-orgs', groupLabel: 'Организации и инструменты', weight: 2,
      term: 'Cyberthreat Real-Time Map', definition: 'An interactive display of current network attacks maintained by Kapersky; the attack data is submitted from Kapersky network security products deployed worldwide. Such tools are generally called cyberthreat maps.',
      ru: 'Карта атак в реальном времени, данные от продуктов Kapersky.' },

    { id: '2.1-p1', lesson: '2.1.6', kind: 'term', group: 'pt-attacks', groupLabel: 'Атаки из Packet Tracer', weight: 3,
      term: 'Rogue access point', definition: 'A laptop configured with a WiFi interface acting as both a WiFi access point and a WiFi client, broadcasting a convincing SSID to create man in the middle attacks.',
      cloze: 'A ___ acts as both an access point and a client and is used to create man in the middle attacks.',
      ru: 'Ноутбук как AP и клиент одновременно, инструмент для MITM.' },
    { id: '2.1-p2', lesson: '2.1.6', kind: 'term', group: 'pt-attacks', groupLabel: 'Атаки из Packet Tracer', weight: 3,
      term: 'DNS hijacking', definition: 'The victim connects to a rogue AP, the attacker’s DHCP server hands out the attacker’s address as the DNS server, and the attacker’s DNS resolves a popular site to a malicious server.',
      ru: 'Rogue AP плюс свой DHCP и своя DNS-запись уводят трафик на вредоносный сервер.' },
    { id: '2.1-p3', lesson: '2.1.1', kind: 'term', group: 'pt-attacks', groupLabel: 'Атаки из Packet Tracer', weight: 3,
      term: 'iframe injection attack', definition: 'An old exploit placed on a compromised third-party website that hits anyone who visits it; in the Aupticon case it was used as a watering hole.',
      ru: 'Эксплойт на взломанном стороннем сайте, заражает всех посетителей.' },
    { id: '2.1-p4', lesson: '2.1.1', kind: 'term', group: 'pt-attacks', groupLabel: 'Атаки из Packet Tracer', weight: 3,
      term: 'Flat network', definition: 'A network with no subnets or segmentation, which let the attacker see HR files, legal documents, R&D and the blueprints.',
      cloze: 'A totally ___ has no subnets, so the attacker could see everything.', clozeAnswer: 'flat network',
      ru: 'Сеть без подсетей и сегментации.' },
    { id: '2.1-p5', lesson: '2.1.6', kind: 'fact', group: 'pt-facts', groupLabel: 'Факты активности', weight: 3,
      term: 'The primary vulnerability in phishing attacks', definition: 'Unlike other network vulnerabilities, the primary vulnerability in phishing attacks is the users of the network, so the important defense is training.',
      cloze: 'The primary vulnerability in phishing attacks is the ___ of the network.', clozeAnswer: 'users',
      ru: 'Главная уязвимость это пользователи, главная защита это обучение.' },
    { id: '2.1-p6', lesson: '2.1.6', kind: 'fact', group: 'pt-facts', groupLabel: 'Факты активности', weight: 2,
      term: 'The ransom demanded in the Packet Tracer activity', definition: 'The ransomware message demands $600 to recover the encrypted files.',
      cloze: 'The ransomware message in the activity demands ___ to recover the files.', clozeAnswer: '$600',
      decoys: ['$174.99', '$6,000', '75 Bitcoins'], ru: 'Выкуп в активности: $600.' },
    { id: '2.1-p7', lesson: '2.1.1', kind: 'fact', group: 'pt-facts', groupLabel: 'Факты активности', weight: 2,
      term: 'The price paid for the Aupticon blueprints', definition: 'Brian Page was paid 75 Bitcoins for the stolen blueprints.',
      cloze: 'Brian Page was paid ___ for the stolen blueprints.', clozeAnswer: '75 Bitcoins',
      decoys: ['$600', '11 Bitcoins', '$174.99'], ru: '75 биткоинов.' },
    { id: '2.1-p8', lesson: '2.1.1', kind: 'fact', group: 'pt-facts', groupLabel: 'Факты активности', weight: 2,
      term: 'The device Aupticon forgot to scan', definition: 'The thermostat: an IoT device inside the firewall, connected to the entire network, whose standard configuration and password are available on the manufacturer’s website.',
      cloze: 'Aupticon scanned most of the network but not the ___.', clozeAnswer: 'thermostat',
      decoys: ['webcam', 'printer', 'router'], ru: 'Термостат, IoT с дефолтным паролем.' },
    { id: '2.1-p9', lesson: '2.1.6', kind: 'enum', group: 'pt-fix', groupLabel: 'Меры защиты', weight: 3,
      term: 'How to secure the guest network (Part 1 solution)', definition: 'The guest network should be deactivated or configured with basic security such as strong authentication, SSID broadcast disabled and access to local network devices disabled.',
      items: ['Deactivate the guest network', 'Configure strong authentication', 'Disable SSID broadcast', 'Disable access to local network devices'],
      decoys: ['Add a third radio', 'Keep the default admin password', 'Open more ports on the firewall'],
      ru: 'Решение первой части активности.' },
    { id: '2.1-p10', lesson: '2.1.4', kind: 'enum', group: 'insider-actions', groupLabel: 'Действия инсайдера', weight: 3,
      term: 'What an internal user can do, accidentally or intentionally', definition: 'Steal and copy confidential data to removable media, email, messaging software and other media; compromise internal servers or network infrastructure devices; disconnect a critical network connection and cause a network outage; connect an infected USB drive into a corporate computer system.',
      items: ['Steal and copy confidential data to removable media or email', 'Compromise internal servers or network infrastructure devices', 'Disconnect a critical network connection and cause an outage', 'Connect an infected USB drive into a corporate computer'],
      decoys: ['Launch a DDoS from the internet', 'Register a typosquatted domain', 'Run a watering hole attack'],
      ru: 'Четыре пункта курса.' },
  ],
}
