import type { Island } from '@/types'

export const island_2_2: Island = {
  id: '2.2',
  moduleId: 2,
  title: 'Who is Attacking Our Network?',
  titleRu: 'Кто атакует нашу сеть',
  objective: 'Explain threat, vulnerability and risk, the types of threat actors, and how threat information is shared.',
  icon: 'VenetianMask',
  lessons: [
    {
      id: '2.2.1', title: 'Threat, Vulnerability, and Risk', titleRu: 'Угроза, уязвимость, риск', kind: 'accordion',
      blocks: [
        { t: 'p', md: 'Мы под атакой, и атакующие хотят доступ к нашим **assets**. Assets — это всё, что ценно для организации: данные и другая интеллектуальная собственность, серверы, компьютеры, смартфоны, планшеты и так далее.' },
        { t: 'figure', caption: 'Три пересекающихся круга: Threat, Vulnerability, Asset. Область их пересечения подписана Risk.' },
        {
          t: 'accordion', title: 'Пять базовых терминов',
          items: [
            { title: 'Threat', md: 'A **potential danger** to an asset such as data or the network itself.' },
            { title: 'Vulnerability', md: 'A **weakness in a system or its design** that could be exploited by a threat.' },
            { title: 'Attack surface', md: 'The **total sum of the vulnerabilities in a given system that are accessible to an attacker**. Описывает разные точки, через которые атакующий может **войти** в систему и **вывести** из неё данные.\n\nПример: вашей операционной системе и браузеру обоим могут быть нужны security patches. Каждый уязвим и выставлен в сеть или интернет. Вместе они создают attack surface.' },
            { title: 'Exploit', md: 'The **mechanism that is used to leverage a vulnerability to compromise an asset**. Эксплойты бывают **remote** и **local**.\n\n- **Remote exploit** работает **по сети без какого-либо предварительного доступа** к целевой системе. Атакующему **не нужна учётная запись** в конечной системе.\n- **Local exploit**: у threat actor уже есть **пользовательский или административный доступ** к конечной системе. Это **не означает физического доступа**.' },
            { title: 'Risk', md: 'The **likelihood that a particular threat will exploit a particular vulnerability of an asset and result in an undesirable consequence**.' },
          ],
        },
        { t: 'h', text: 'Risk management: четыре способа управления риском' },
        { t: 'p', md: '**Risk management** — процесс, который балансирует операционные затраты на защитные меры с выгодой от защиты актива.' },
        {
          t: 'accordion',
          items: [
            { title: 'Risk acceptance', md: 'Когда **стоимость мер управления риском превышает стоимость самого риска**. Риск принимается, действий не предпринимается.' },
            { title: 'Risk avoidance', md: 'Избегание любого воздействия риска путём **устранения деятельности или устройства**, которое этот риск создаёт. Минус: вместе с деятельностью теряются и **все её выгоды**.' },
            { title: 'Risk reduction', md: 'Снижение подверженности риску или снижение его влияния через действия, уменьшающие риск. **Самая часто используемая стратегия митигации.** Требует тщательной оценки стоимости потерь, стоимости стратегии и выгод от операции.' },
            { title: 'Risk transfer', md: 'Часть или весь риск **передаётся согласной третьей стороне**, например **страховой компании**.' },
          ],
        },
        { t: 'table', caption: 'Ещё два термина', headers: ['Термин', 'Определение'], rows: [
          ['**Countermeasure**', 'The actions that are taken to protect assets by **mitigating a threat or reducing risk**.'],
          ['**Impact**', 'The **potential damage** to the organization that is caused by the threat.'],
        ] },
        { t: 'note', variant: 'exam', title: 'Note из курса', md: 'A **local exploit** requires inside network access, such as a user with an account on the network. A **remote exploit** does **not** require an account on the network to exploit that network vulnerability.' },
        { t: 'note', variant: 'tip', title: 'Формула', md: '**Threat + Vulnerability + Asset = Risk.**' },
      ],
    },
    {
      id: '2.2.2', title: 'Hacker vs Threat Actor', titleRu: 'Хакер и threat actor', kind: 'text',
      blocks: [
        { t: 'p', md: 'Слово **hacker** обычно используют для обозначения threat actor, но у термина есть несколько значений.' },
        { t: 'list', ordered: true, items: [
          'A **clever programmer** capable of developing new programs and coding changes to existing programs to make them more efficient.',
          'A **network professional** that uses sophisticated programming skills to ensure that networks are not vulnerable to attack.',
          'A person who tries to **gain unauthorized access** to devices on the internet.',
          'An individual who runs programs to **prevent or slow network access** to a large number of users, or **corrupt or wipe out data** on servers.',
        ] },
        { t: 'def', term: 'Attack vector', md: 'A **path by which a threat actor can gain access to a server, host, or network**. Attack vectors originate from **inside or outside** the corporate network. Например, threat actors могут атаковать сеть через интернет, чтобы нарушить работу сети и устроить **DoS**.' },
        { t: 'h', text: 'Три цвета шляп' },
        { t: 'table', headers: ['Тип', 'Законность', 'Авторизация', 'Мотив', 'Что делает с уязвимостью'], rows: [
          ['**White hat**', 'легально, этично', 'есть', 'добро, работа, bug bounty', 'сообщает разработчикам до того, как её проэксплуатируют'],
          ['**Gray hat**', 'незаконно, спорно этично', 'нет', '**не** личная выгода и **не** ущерб', 'может раскрыть публично или сообщить организации после взлома'],
          ['**Black hat**', 'незаконно, неэтично', 'нет', 'личная выгода или злой умысел', 'эксплуатирует для компрометации систем'],
        ] },
        { t: 'p', md: '**White hat hackers** — этичные хакеры, применяющие навыки программирования в добрых, этичных и законных целях. Они могут проводить **network penetration tests**, пытаясь скомпрометировать сети и системы, чтобы обнаружить уязвимости. Уязвимости сообщаются разработчикам и специалистам по безопасности. Некоторые организации выдают **призы или bounties**.' },
        { t: 'p', md: '**Gray hat hackers** совершают преступления и спорные с точки зрения этики поступки, **но не ради личной выгоды и не чтобы причинить ущерб**. Пример: кто-то компрометирует сеть без разрешения, а затем публично раскрывает уязвимость. Gray hat может сообщить об уязвимости пострадавшей организации после взлома, чтобы та могла исправить проблему.' },
        { t: 'p', md: '**Black hat hackers** — неэтичные преступники, нарушающие безопасность компьютеров и сетей ради личной выгоды или по злому умыслу.' },
        { t: 'note', variant: 'exam', md: 'В этом курсе термин **threat actor** относится к тем, кого можно классифицировать как **gray или black hat**. White hat сюда **не входит**.' },
      ],
    },
    {
      id: '2.2.3', title: 'Evolution of Threat Actors', titleRu: 'Эволюция threat actors', kind: 'accordion',
      blocks: [
        { t: 'h', text: 'Хронология' },
        { t: 'list', items: [
          '**1960-е** — хакинг начался с **phone freaking (phreaking)**: использование различных звуковых частот для манипуляции телефонными системами. Телефонные коммутаторы использовали разные тоны (**tone dialing**) для разных функций. Имитируя тон **свистком**, ранние threat actors эксплуатировали коммутаторы, чтобы совершать бесплатные междугородние звонки.',
          '**Середина 1980-х** — dial-up модемы. Threat actors писали программы **war dialing**, которые обзванивали каждый телефонный номер в заданном районе в поисках компьютеров, bulletin board systems и факсов. Найдя номер, применяли программы подбора паролей.',
          '**1990-е** — появление **script kiddies**.',
        ] },
        {
          t: 'accordion', title: 'Пять типов threat actors',
          items: [
            { title: 'Script kiddies', md: 'Появились в **1990-х**. Подростки или неопытные threat actors, запускающие **существующие скрипты, инструменты и эксплойты**, чтобы навредить, но **обычно не ради прибыли**.' },
            { title: 'Vulnerability brokers', md: 'Обычно это **gray hat hackers**, которые пытаются найти эксплойты и **сообщить о них вендорам**, иногда за призы или вознаграждение.' },
            { title: 'Hacktivists', md: '**Gray hat hackers**, которые сплачиваются и протестуют против разных политических и социальных идей. Публично протестуют против организаций или правительств: публикуют статьи, видео, **сливают чувствительную информацию** и проводят **DDoS-атаки**.' },
            { title: 'Cybercriminals', md: '**Black hat hackers**, самозанятые или работающие на крупные киберпреступные организации. Каждый год ответственны за кражу **миллиардов долларов** у потребителей и бизнеса.' },
            { title: 'State-sponsored', md: 'Threat actors, которые крадут государственные секреты, собирают разведданные и саботируют сети иностранных правительств, террористических групп и корпораций. Большинство стран мира в той или иной степени участвуют в state-sponsored hacking. **В зависимости от точки зрения это либо white hat, либо black hat hackers.**' },
          ],
        },
        { t: 'note', variant: 'exam', title: 'Ловушки', md: 'Script kiddies — **не** ради денег. Vulnerability brokers и hacktivists — **серые**. State-sponsored — **единственный** тип с двойной трактовкой.' },
      ],
    },
    {
      id: '2.2.4', title: 'Cybercriminals', titleRu: 'Киберпреступники', kind: 'text',
      blocks: [
        { t: 'p', md: 'Cybercriminals — threat actors, мотивированные **зарабатывать деньги любыми необходимыми средствами**. Иногда работают независимо, но **чаще финансируются и спонсируются преступными организациями**. По оценкам, по всему миру они крадут **миллиарды долларов** у потребителей и бизнеса каждый год.' },
        { t: 'p', md: 'Они действуют в **underground economy**, где покупают, продают и обменивают **эксплойты и инструменты**. Также покупают и продают **персональные данные и интеллектуальную собственность**, украденные у жертв.' },
        { t: 'note', variant: 'tip', md: 'Cybercriminals атакуют **и малый бизнес с частными лицами, и крупные предприятия с целыми отраслями**. Они не выбирают только крупных.' },
      ],
    },
    {
      id: '2.2.5', title: 'Cybersecurity Tasks', titleRu: 'Задачи кибербезопасности', kind: 'text',
      blocks: [
        { t: 'p', md: '**Threat actors do not discriminate.** Они атакуют уязвимые конечные устройства домашних пользователей и малого и среднего бизнеса так же, как крупные государственные и частные организации.' },
        { t: 'note', variant: 'exam', md: '**Cybersecurity is a shared responsibility** — общая ответственность, которую должны практиковать все пользователи.' },
        { t: 'h', text: 'Что должен делать рядовой пользователь' },
        { t: 'list', ordered: true, items: [
          'Сообщать о киберпреступлениях соответствующим органам.',
          'Знать о потенциальных угрозах в email и вебе.',
          'Защищать важную информацию от кражи.',
        ] },
        { t: 'h', text: 'Девять cybersecurity tasks организации' },
        { t: 'list', ordered: true, items: [
          'Cybersecurity checklist',
          'Trustworthy IT vendor',
          'Security software up-to-date',
          'Regular penetration tests',
          'Backup to cloud and hard disk',
          'Periodically change WIFI password',
          'Security policy up-to-date',
          'Enforce use of strong passwords',
          'Two factor authentication',
        ] },
      ],
    },
    {
      id: '2.2.6', title: 'Cyber Threat Indicators', titleRu: 'Индикаторы киберугроз', kind: 'text',
      blocks: [
        { t: 'def', term: 'Indicators of compromise (IOC)', md: 'The **evidence that an attack has occurred**. У каждой атаки уникальные идентифицируемые атрибуты. IOC могут быть признаками, идентифицирующими файлы malware, IP-адресами серверов, используемых в атаках, именами файлов и характерными изменениями в ПО конечной системы. IOC помогают персоналу понять, **что произошло** в атаке, и выстроить защиту.' },
        { t: 'p', md: 'Многие сетевые атаки можно предотвратить, **обмениваясь информацией об IOC**.' },
        { t: 'table', caption: 'Пример сводки IOC для образца malware', headers: ['Тип', 'Значение'], rows: [
          ['Malware file', '`studiox-link-standalone-v20.03.8-stable.exe`'],
          ['sha256', '`6a6c28f5666b12beecd56a3d1d517e409b5d6866c03f9be44ddd9efffa90f1e0`'],
          ['sha1', '`eb019ad1c73ee69195c3fc84ebf44e95c147bef8`'],
          ['md5', '`3a104b73bb96dfed288097e9dc0a11a8`'],
          ['DNS requests', '`log.studiox.link`, `my.studiox.link`, `_sips._tcp.studiox.link`, `sip.studiox.link`'],
          ['Connections', '`198.51.100.248`, `203.0.113.82`'],
        ] },
        { t: 'p', md: 'Пример: пользователь получает письмо о крупном выигрыше. Клик по ссылке приводит к атаке. **IOC** здесь: факт, что пользователь не участвовал в конкурсе, IP-адрес отправителя, тема письма, URL для клика, вложение для скачивания.' },
        { t: 'def', term: 'Indicators of attack (IOA)', md: 'Фокусируются больше на **мотивации** атаки и на потенциальных **средствах**, которыми threat actors скомпрометируют уязвимости ради доступа к активам. IOA касаются **стратегий**, используемых атакующими. Поэтому вместо реакции на одну угрозу они помогают выстроить **проактивный** подход: стратегии переиспользуются в разных контекстах и атаках, и защита от стратегии предотвращает будущие атаки по той же или похожей схеме.' },
        { t: 'note', variant: 'exam', title: 'Почти гарантированный вопрос', md: '**IOC** — реактивные, про прошлое, «что случилось» (артефакты и признаки). **IOA** — проактивные, про будущее, «зачем и как» (мотивация и стратегия).' },
      ],
    },
    {
      id: '2.2.7', title: 'Threat Sharing and Awareness', titleRu: 'Обмен угрозами и осведомлённость', kind: 'text',
      blocks: [
        { t: 'table', caption: 'Аббревиатуры раздела', headers: ['Аббревиатура', 'Расшифровка и роль'], rows: [
          ['**CISA**', 'US **Cybersecurity Infrastructure and Security Agency**. Ведёт автоматизацию обмена информацией по кибербезопасности с государственными и частными организациями **бесплатно**. Помогает уменьшить размер attack surface США.'],
          ['**AIS**', '**Automated Indicator Sharing**. Система CISA: обмен индикаторами атак между правительством США и частным сектором **сразу после верификации угроз**.'],
          ['**NCSA**', '**National Cyber Security Alliance**. Вместе с CISA продвигает кибербезопасность среди всех пользователей.'],
          ['**NCSAM**', '**National Cybersecurity Awareness Month**. Ежегодная кампания, проходит **каждый октябрь**.'],
          ['**ENISA**', '**European Union Agency for Cybersecurity**. Советы и решения для стран-членов ЕС, **европейский аналог CISA**.'],
        ] },
        { t: 'p', md: 'Тема NCSAM **2019**: **«Own IT. Secure IT. Protect IT.»**, хештег **#BeCyberSmart**. Кампания призывала граждан быть безопаснее и более лично ответственными за применение лучших практик онлайн.' },
        { t: 'h', text: 'Семь тем кампании' },
        { t: 'list', items: [
          'Social media safety',
          'Updating privacy settings',
          'Awareness of device app security',
          'Keeping software up-to-date',
          'Safe online shopping',
          'Wi-Fi safety',
          'Protecting customer data',
        ] },
        { t: 'note', variant: 'tip', title: 'Связка для запоминания', md: 'CISA (США) = ENISA (ЕС). CISA + NCSA = NCSAM каждый октябрь.' },
      ],
    },
    {
      id: '2.2.8', title: 'What Color is my Hat? (activity)', titleRu: 'Какого цвета моя шляпа', kind: 'activity',
      blocks: [
        {
          t: 'activity', title: 'Click the appropriate response for each characteristic',
          prompt: 'Gray hat / Black hat / White hat',
          options: ['Gray hat', 'Black hat', 'White hat'],
          items: [
            { q: 'I hacked into ATM machines without the manufacturer authorization and discovered several vulnerabilities. I then contacted the ATM manufacturer to share my findings with them.', a: 'Gray hat', why: 'Взлом без разрешения, но сообщил сам, без корысти и ущерба.' },
            { q: 'I secretly installed a debit card skimmer device on an ATM machine, captured the account numbers and pins of over 1000 people, then transferred money from their accounts to an offshore bank account.', a: 'Black hat', why: 'Кража денег ради личной выгоды.' },
            { q: 'My job is to identify weaknesses in the computer system in my company.', a: 'White hat', why: 'Это его работа, есть авторизация.' },
            { q: 'I used malware to compromise several corporate systems to steal credit card information and sold that information to the highest bidder.', a: 'Black hat', why: 'Продажа краденого.' },
            { q: 'During my research for security exploits, I stumbled across a security vulnerability on a corporate network that I am authorized to access.', a: 'White hat', why: 'Ключевое слово authorized.' },
            { q: 'While I was searching for security vulnerabilities, I gained unauthorized access to a company network and left the message "Your security is flawed".', a: 'Gray hat', why: 'Без разрешения, но без ущерба и корысти.' },
            { q: 'I am working with technology companies to fix a flaw with DNS.', a: 'White hat', why: 'Работа совместно с вендорами.' },
          ],
          feedback: 'Логика разбора в три шага: есть ли авторизация или это его работа → White hat. Авторизации нет, но нет корысти и ущерба → Gray hat. Авторизации нет плюс корысть, кража или продажа данных → Black hat.',
        },
        { t: 'note', variant: 'tip', md: 'Итог по количеству: **White hat — 3** (вопросы 3, 5, 7), **Black hat — 2** (2, 4), **Gray hat — 2** (1, 6).' },
      ],
    },
    {
      id: '2.2.S', title: 'Summary table', titleRu: 'Итоговая таблица 2.2', kind: 'summary',
      blocks: [
        { t: 'table', headers: ['Понятие', 'Категория', 'Суть', 'Ключевое отличие или цифра'], rows: [
          ['Asset', 'базовый термин', 'всё ценное для организации', 'данные, IP, серверы, ПК, смартфоны, планшеты'],
          ['Threat', 'базовый термин', 'потенциальная опасность для актива', 'потенциальная, ещё не реализованная'],
          ['Vulnerability', 'базовый термин', 'слабость системы или её дизайна', 'может быть использована угрозой'],
          ['Attack surface', 'базовый термин', 'сумма всех доступных атакующему уязвимостей', 'точки входа И точки вывода данных'],
          ['Exploit', 'базовый термин', 'механизм использования уязвимости', 'бывает remote и local'],
          ['Risk', 'базовый термин', 'вероятность реализации угрозы через уязвимость', 'Threat плюс Vulnerability плюс Asset'],
          ['Countermeasure', 'базовый термин', 'действия по защите активов', 'смягчает угрозу или снижает риск'],
          ['Impact', 'базовый термин', 'потенциальный ущерб организации', 'последствие угрозы'],
          ['Remote exploit', 'тип эксплойта', 'работает по сети', 'учётная запись НЕ нужна'],
          ['Local exploit', 'тип эксплойта', 'нужен пользовательский или админ доступ', 'физический доступ НЕ обязателен'],
          ['Risk acceptance', 'управление риском', 'риск принимают, действий нет', 'стоимость мер выше стоимости риска'],
          ['Risk avoidance', 'управление риском', 'устранение деятельности или устройства', 'теряются и выгоды'],
          ['Risk reduction', 'управление риском', 'снижение риска или его влияния', 'САМАЯ используемая стратегия'],
          ['Risk transfer', 'управление риском', 'передача третьей стороне', 'пример: страховая компания'],
          ['White hat', 'тип хакера', 'этичный, легальный', 'есть авторизация, bug bounty'],
          ['Gray hat', 'тип хакера', 'незаконно, но без корысти и ущерба', 'раскрывает уязвимость публично или вендору'],
          ['Black hat', 'тип хакера', 'неэтичный преступник', 'личная выгода или злой умысел'],
          ['Threat actor', 'обобщение', 'в курсе это gray или black hat', 'white hat НЕ входит'],
          ['Attack vector', 'термин', 'путь доступа к серверу, хосту, сети', 'внутренний или внешний'],
          ['Phreaking', 'история', 'манипуляция телефонными системами через тоны', '1960-е, свисток вместо тона'],
          ['War dialing', 'история', 'обзвон всех номеров в поиске компьютеров и BBS', 'середина 1980-х, dial-up модемы'],
          ['Script kiddies', 'threat actor', 'запуск готовых скриптов и эксплойтов', '1990-е, обычно НЕ ради прибыли'],
          ['Vulnerability brokers', 'threat actor (gray)', 'ищут эксплойты, сообщают вендорам', 'иногда за призы и награды'],
          ['Hacktivists', 'threat actor (gray)', 'протест против политических и социальных идей', 'статьи, видео, слив данных, DDoS'],
          ['Cybercriminals', 'threat actor (black)', 'деньги любыми средствами', 'миллиарды долларов в год, underground economy'],
          ['State-sponsored', 'threat actor (white ИЛИ black)', 'гостайны, разведка, саботаж', 'трактовка зависит от точки зрения'],
          ['IOC', 'индикатор', 'доказательство, что атака произошла', 'реактивный: хеши, IP, домены, имена файлов'],
          ['IOA', 'индикатор', 'мотивация и стратегия атакующего', 'проактивный, защита от будущих атак'],
          ['CISA', 'организация, США', 'автоматизация обмена информацией, бесплатно', 'использует AIS'],
          ['AIS', 'система', 'Automated Indicator Sharing', 'обмен сразу после верификации угроз'],
          ['NCSA', 'организация, США', 'National Cyber Security Alliance', 'вместе с CISA продвигает NCSAM'],
          ['NCSAM', 'кампания', 'National Cybersecurity Awareness Month', 'каждый октябрь, 2019: Own IT. Secure IT. Protect IT.'],
          ['ENISA', 'организация, ЕС', 'советы и решения для стран ЕС', 'европейский аналог CISA'],
        ] },
      ],
    },
  ],
  atoms: [
    /* базовые термины */
    { id: '2.2-t1', lesson: '2.2.1', kind: 'term', group: 'risk-core', groupLabel: 'Угроза, уязвимость, риск', weight: 3,
      term: 'Asset', definition: 'Anything of value to an organization, such as data and other intellectual property, servers, computers, smart phones and tablets.',
      ru: 'Всё, что ценно для организации.' },
    { id: '2.2-t2', lesson: '2.2.1', kind: 'term', group: 'risk-core', groupLabel: 'Угроза, уязвимость, риск', weight: 3,
      term: 'Threat', definition: 'A potential danger to an asset such as data or the network itself.',
      cloze: 'A ___ is a potential danger to an asset such as data or the network itself.',
      ru: 'Потенциальная опасность для актива.' },
    { id: '2.2-t3', lesson: '2.2.1', kind: 'term', group: 'risk-core', groupLabel: 'Угроза, уязвимость, риск', weight: 3,
      term: 'Vulnerability', definition: 'A weakness in a system or its design that could be exploited by a threat.',
      cloze: 'A ___ is a weakness in a system or its design that could be exploited by a threat.',
      ru: 'Слабость системы или её дизайна.' },
    { id: '2.2-t4', lesson: '2.2.1', kind: 'term', group: 'risk-core', groupLabel: 'Угроза, уязвимость, риск', weight: 3,
      term: 'Attack surface', definition: 'The total sum of the vulnerabilities in a given system that are accessible to an attacker; it describes the different points where an attacker could get into a system and where they could get data out of it.',
      cloze: 'The ___ is the total sum of the vulnerabilities in a system that are accessible to an attacker.',
      ru: 'Сумма всех доступных атакующему уязвимостей, точки входа и вывода данных.' },
    { id: '2.2-t5', lesson: '2.2.1', kind: 'term', group: 'risk-core', groupLabel: 'Угроза, уязвимость, риск', weight: 3,
      term: 'Exploit', definition: 'The mechanism that is used to leverage a vulnerability to compromise an asset; exploits may be remote or local.',
      ru: 'Механизм использования уязвимости для компрометации актива.' },
    { id: '2.2-t6', lesson: '2.2.1', kind: 'term', group: 'risk-core', groupLabel: 'Угроза, уязвимость, риск', weight: 3,
      term: 'Risk', definition: 'The likelihood that a particular threat will exploit a particular vulnerability of an asset and result in an undesirable consequence.',
      cloze: '___ is the likelihood that a particular threat will exploit a particular vulnerability of an asset.',
      ru: 'Вероятность того, что угроза использует уязвимость и приведёт к нежелательным последствиям.' },
    { id: '2.2-t7', lesson: '2.2.1', kind: 'term', group: 'risk-core', groupLabel: 'Угроза, уязвимость, риск', weight: 3,
      term: 'Remote exploit', definition: 'An exploit that works over the network without any prior access to the target system; the attacker does not need an account in the end system.',
      ru: 'Работает по сети, учётная запись не нужна.' },
    { id: '2.2-t8', lesson: '2.2.1', kind: 'term', group: 'risk-core', groupLabel: 'Угроза, уязвимость, риск', weight: 3,
      term: 'Local exploit', definition: 'An exploit where the threat actor has some type of user or administrative access to the end system; it does not necessarily mean the attacker has physical access.',
      ru: 'Нужен пользовательский или админский доступ, физический доступ не обязателен.' },
    { id: '2.2-t9', lesson: '2.2.1', kind: 'term', group: 'risk-core', groupLabel: 'Угроза, уязвимость, риск', weight: 2,
      term: 'Countermeasure', definition: 'The actions that are taken to protect assets by mitigating a threat or reducing risk.',
      ru: 'Действия по защите активов.' },
    { id: '2.2-t10', lesson: '2.2.1', kind: 'term', group: 'risk-core', groupLabel: 'Угроза, уязвимость, риск', weight: 2,
      term: 'Impact', definition: 'The potential damage to the organization that is caused by the threat.',
      ru: 'Потенциальный ущерб организации от угрозы.' },

    /* risk management */
    { id: '2.2-r1', lesson: '2.2.1', kind: 'term', group: 'risk-mgmt', groupLabel: 'Управление риском', weight: 3,
      term: 'Risk acceptance', definition: 'When the cost of risk management options outweighs the cost of the risk itself; the risk is accepted and no action is taken.',
      ru: 'Меры дороже риска, риск принимают.' },
    { id: '2.2-r2', lesson: '2.2.1', kind: 'term', group: 'risk-mgmt', groupLabel: 'Управление риском', weight: 3,
      term: 'Risk avoidance', definition: 'Avoiding any exposure to the risk by eliminating the activity or device that presents the risk; any benefits possible from the activity are also lost.',
      ru: 'Устранить деятельность вместе с её выгодами.' },
    { id: '2.2-r3', lesson: '2.2.1', kind: 'term', group: 'risk-mgmt', groupLabel: 'Управление риском', weight: 3,
      term: 'Risk reduction', definition: 'Reducing exposure to risk or the impact of risk by taking action to decrease it; it is the most commonly used risk mitigation strategy and requires careful evaluation of the costs of loss, the mitigation strategy and the benefits gained.',
      cloze: '___ is the most commonly used risk mitigation strategy.',
      ru: 'Самая часто используемая стратегия митигации.' },
    { id: '2.2-r4', lesson: '2.2.1', kind: 'term', group: 'risk-mgmt', groupLabel: 'Управление риском', weight: 3,
      term: 'Risk transfer', definition: 'Some or all of the risk is transferred to a willing third party such as an insurance company.',
      ru: 'Передача риска третьей стороне, например страховой.' },
    { id: '2.2-r5', lesson: '2.2.1', kind: 'enum', group: 'risk-mgmt', groupLabel: 'Управление риском', weight: 3,
      term: 'The four common ways to manage risk', definition: 'Risk acceptance, risk avoidance, risk reduction and risk transfer.',
      items: ['Risk acceptance', 'Risk avoidance', 'Risk reduction', 'Risk transfer'],
      decoys: ['Risk duplication', 'Risk inversion', 'Risk escalation'],
      ru: 'Четыре способа управления риском.' },

    /* шляпы */
    { id: '2.2-h1', lesson: '2.2.2', kind: 'term', group: 'hats', groupLabel: 'Цвета шляп', weight: 3,
      term: 'White hat hacker', definition: 'An ethical hacker who uses programming skills for good, ethical and legal purposes, performing penetration tests to discover network vulnerabilities and reporting them to developers and security personnel, sometimes for prizes or bounties.',
      ru: 'Этичный хакер с авторизацией.' },
    { id: '2.2-h2', lesson: '2.2.2', kind: 'term', group: 'hats', groupLabel: 'Цвета шляп', weight: 3,
      term: 'Gray hat hacker', definition: 'An individual who commits crimes and does arguably unethical things, but not for personal gain or to cause damage; for example someone who compromises a network without permission and then discloses the vulnerability publicly or to the affected organization.',
      cloze: 'A ___ commits crimes and does arguably unethical things, but not for personal gain or to cause damage.',
      ru: 'Без разрешения, но без корысти и ущерба.' },
    { id: '2.2-h3', lesson: '2.2.2', kind: 'term', group: 'hats', groupLabel: 'Цвета шляп', weight: 3,
      term: 'Black hat hacker', definition: 'An unethical criminal who violates computer and network security for personal gain or for malicious reasons, exploiting vulnerabilities to compromise computer and network systems.',
      ru: 'Неэтичный преступник ради выгоды или вреда.' },
    { id: '2.2-h4', lesson: '2.2.2', kind: 'fact', group: 'hats', groupLabel: 'Цвета шляп', weight: 3,
      term: 'Who the course calls a threat actor', definition: 'In this course the term threat actor is used when referring to those individuals or groups that could be classified as gray or black hat hackers.',
      cloze: 'In this course a threat actor refers to ___ hat hackers.', clozeAnswer: 'gray or black',
      decoys: ['white or gray', 'only black', 'white only'],
      ru: 'Threat actor это серые и чёрные шляпы, белые не входят.' },
    { id: '2.2-h5', lesson: '2.2.8', kind: 'bucket', group: 'hat-cases', groupLabel: 'Разбор кейсов со шляпами', weight: 3,
      term: 'Hacked ATMs without authorization, then contacted the manufacturer to share the findings', definition: 'Gray hat: no permission, but no personal gain and no damage.', bucket: 'Gray hat', ru: 'Серая шляпа.' },
    { id: '2.2-h6', lesson: '2.2.8', kind: 'bucket', group: 'hat-cases', groupLabel: 'Разбор кейсов со шляпами', weight: 3,
      term: 'Installed a skimmer, captured 1000+ accounts and transferred money offshore', definition: 'Black hat: theft for personal gain.', bucket: 'Black hat', ru: 'Чёрная шляпа.' },
    { id: '2.2-h7', lesson: '2.2.8', kind: 'bucket', group: 'hat-cases', groupLabel: 'Разбор кейсов со шляпами', weight: 3,
      term: 'My job is to identify weaknesses in the computer system in my company', definition: 'White hat: it is authorized work.', bucket: 'White hat', ru: 'Белая шляпа.' },
    { id: '2.2-h8', lesson: '2.2.8', kind: 'bucket', group: 'hat-cases', groupLabel: 'Разбор кейсов со шляпами', weight: 3,
      term: 'Used malware to steal credit card information and sold it to the highest bidder', definition: 'Black hat: selling stolen data.', bucket: 'Black hat', ru: 'Чёрная шляпа.' },
    { id: '2.2-h9', lesson: '2.2.8', kind: 'bucket', group: 'hat-cases', groupLabel: 'Разбор кейсов со шляпами', weight: 3,
      term: 'Found a vulnerability on a corporate network that I am authorized to access', definition: 'White hat: the key word is authorized.', bucket: 'White hat', ru: 'Белая шляпа.' },
    { id: '2.2-h10', lesson: '2.2.8', kind: 'bucket', group: 'hat-cases', groupLabel: 'Разбор кейсов со шляпами', weight: 3,
      term: 'Gained unauthorized access and left the message "Your security is flawed"', definition: 'Gray hat: no permission, but no damage or gain.', bucket: 'Gray hat', ru: 'Серая шляпа.' },
    { id: '2.2-h11', lesson: '2.2.8', kind: 'bucket', group: 'hat-cases', groupLabel: 'Разбор кейсов со шляпами', weight: 3,
      term: 'Working with technology companies to fix a flaw with DNS', definition: 'White hat: working together with the vendors.', bucket: 'White hat', ru: 'Белая шляпа.' },

    /* threat actors */
    { id: '2.2-a1', lesson: '2.2.3', kind: 'term', group: 'actors', groupLabel: 'Типы threat actors', weight: 3,
      term: 'Script kiddies', definition: 'Emerged in the 1990s: teenagers or inexperienced threat actors running existing scripts, tools and exploits to cause harm, but typically not for profit.',
      cloze: '___ run existing scripts, tools and exploits to cause harm, but typically not for profit.',
      ru: 'Готовые скрипты, обычно не ради прибыли.' },
    { id: '2.2-a2', lesson: '2.2.3', kind: 'term', group: 'actors', groupLabel: 'Типы threat actors', weight: 3,
      term: 'Vulnerability brokers', definition: 'Typically grey hat hackers who attempt to discover exploits and report them to vendors, sometimes for prizes or rewards.',
      ru: 'Серые шляпы, находят эксплойты и сообщают вендорам.' },
    { id: '2.2-a3', lesson: '2.2.3', kind: 'term', group: 'actors', groupLabel: 'Типы threat actors', weight: 3,
      term: 'Hacktivists', definition: 'Grey hat hackers who rally and protest against different political and social ideas, publicly protesting by posting articles and videos, leaking sensitive information and performing DDoS attacks.',
      ru: 'Серые шляпы, политический и социальный протест, DDoS и сливы.' },
    { id: '2.2-a4', lesson: '2.2.3', kind: 'term', group: 'actors', groupLabel: 'Типы threat actors', weight: 3,
      term: 'Cybercriminals', definition: 'Black hat hackers who are either self-employed or working for large cybercrime organizations; they are motivated to make money by any means, operate in an underground economy buying and selling exploits, tools, personal information and intellectual property, and steal billions of dollars every year.',
      ru: 'Чёрные шляпы, деньги любыми средствами, underground economy.' },
    { id: '2.2-a5', lesson: '2.2.3', kind: 'term', group: 'actors', groupLabel: 'Типы threat actors', weight: 3,
      term: 'State-sponsored hackers', definition: 'Threat actors who steal government secrets, gather intelligence and sabotage networks of foreign governments, terrorist groups and corporations; depending on a person perspective, they are either white hat or black hat hackers.',
      cloze: 'Depending on a person perspective, state-sponsored hackers are either ___ hackers.', clozeAnswer: 'white hat or black hat',
      ru: 'Единственный тип с двойной трактовкой.' },
    { id: '2.2-a6', lesson: '2.2.3', kind: 'term', group: 'history', groupLabel: 'История хакинга', weight: 3,
      term: 'Phreaking', definition: 'Phone freaking: hacking started in the 1960s with using various audio frequencies to manipulate phone systems; by mimicking a tone with a whistle, early threat actors exploited phone switches to make free long-distance calls.',
      aliases: ['phone freaking'],
      cloze: 'Hacking started in the ___ with phone freaking, or phreaking.', clozeAnswer: '1960s',
      ru: '1960-е, манипуляция телефонной сетью через тоны.' },
    { id: '2.2-a7', lesson: '2.2.3', kind: 'term', group: 'history', groupLabel: 'История хакинга', weight: 3,
      term: 'War dialing', definition: 'In the mid-1980s threat actors wrote war dialing programs which dialed each telephone number in a given area in search of computers, bulletin board systems and fax machines; when a number was found, password-cracking programs were used to gain access.',
      cloze: 'War dialing programs appeared in the ___ with computer dial-up modems.', clozeAnswer: 'mid-1980s',
      ru: 'Середина 1980-х, обзвон номеров в поисках компьютеров.' },

    /* задачи и индикаторы */
    { id: '2.2-c1', lesson: '2.2.5', kind: 'fact', group: 'tasks', groupLabel: 'Задачи и ответственность', weight: 3,
      term: 'Whose responsibility cybersecurity is', definition: 'Cybersecurity is a shared responsibility which all users must practice; threat actors do not discriminate and target home users, small and medium businesses and large organizations alike.',
      cloze: 'Cybersecurity is a ___ which all users must practice.', clozeAnswer: 'shared responsibility',
      ru: 'Общая ответственность всех пользователей.' },
    { id: '2.2-c2', lesson: '2.2.5', kind: 'enum', group: 'tasks', groupLabel: 'Задачи и ответственность', weight: 3,
      term: 'The nine cybersecurity tasks', definition: 'Cybersecurity checklist; trustworthy IT vendor; security software up-to-date; regular penetration tests; backup to cloud and hard disk; periodically change WIFI password; security policy up-to-date; enforce use of strong passwords; two factor authentication.',
      items: ['Cybersecurity checklist', 'Trustworthy IT vendor', 'Security software up-to-date', 'Regular penetration tests', 'Backup to cloud and hard disk', 'Periodically change WIFI password', 'Security policy up-to-date', 'Enforce use of strong passwords', 'Two factor authentication'],
      decoys: ['Disable the firewall for guests', 'Share admin passwords by email', 'Keep default router credentials'],
      ru: 'Девять задач кибербезопасности организации.' },
    { id: '2.2-c3', lesson: '2.2.5', kind: 'enum', group: 'tasks', groupLabel: 'Задачи и ответственность', weight: 2,
      term: 'What every user must do', definition: 'Report cybercrime to the appropriate authorities, be aware of potential threats in email and the web, and guard important information from theft.',
      items: ['Report cybercrime to the appropriate authorities', 'Be aware of potential threats in email and the web', 'Guard important information from theft'],
      decoys: ['Run penetration tests personally', 'Publish incident reports', 'Maintain the corporate firewall'],
      ru: 'Три обязанности рядового пользователя.' },
    { id: '2.2-i1', lesson: '2.2.6', kind: 'term', group: 'indicators', groupLabel: 'Индикаторы', weight: 3,
      term: 'Indicators of compromise (IOC)', definition: 'The evidence that an attack has occurred: features that identify malware files, IP addresses of servers used in attacks, filenames and characteristic changes made to end system software; they help identify what has happened and develop defenses.',
      aliases: ['ioc'],
      cloze: '___ are the evidence that an attack has occurred.',
      ru: 'Доказательства того, что атака уже произошла.' },
    { id: '2.2-i2', lesson: '2.2.6', kind: 'term', group: 'indicators', groupLabel: 'Индикаторы', weight: 3,
      term: 'Indicators of attack (IOA)', definition: 'Focus on the motivation behind an attack and the potential means by which threat actors have, or will, compromise vulnerabilities; they are concerned with the strategies used by attackers and help generate a proactive security approach.',
      aliases: ['ioa'],
      cloze: '___ focus on the motivation behind an attack and the strategies used by attackers.',
      ru: 'Мотивация и стратегия, проактивный подход.' },
    { id: '2.2-i3', lesson: '2.2.6', kind: 'fact', group: 'indicators', groupLabel: 'Индикаторы', weight: 3,
      term: 'IOC versus IOA', definition: 'IOC are reactive and describe what already happened through artifacts; IOA are proactive and describe the motivation and strategy, so defending against a strategy prevents future attacks that use it.',
      ru: 'IOC про прошлое и артефакты, IOA про мотивацию и стратегию.' },

    /* организации */
    { id: '2.2-g1', lesson: '2.2.7', kind: 'term', group: 'orgs', groupLabel: 'Организации и кампании', weight: 3,
      term: 'CISA', definition: 'The US Cybersecurity Infrastructure and Security Agency, leading efforts to automate the sharing of cybersecurity information with public and private organizations at no cost, using the Automated Indicator Sharing system.',
      aliases: ['cybersecurity infrastructure and security agency'],
      ru: 'Американское агентство, бесплатный автоматизированный обмен информацией.' },
    { id: '2.2-g2', lesson: '2.2.7', kind: 'term', group: 'orgs', groupLabel: 'Организации и кампании', weight: 3,
      term: 'AIS', definition: 'Automated Indicator Sharing: a CISA system that enables the sharing of attack indicators between the US government and the private sector as soon as threats are verified.',
      aliases: ['automated indicator sharing'],
      ru: 'Обмен индикаторами сразу после верификации угроз.' },
    { id: '2.2-g3', lesson: '2.2.7', kind: 'term', group: 'orgs', groupLabel: 'Организации и кампании', weight: 3,
      term: 'ENISA', definition: 'The European Union Agency for Cybersecurity, which delivers advice and solutions for the cybersecurity challenges of EU member states; it fills a role in Europe similar to CISA in the US.',
      aliases: ['european union agency for cybersecurity'],
      cloze: '___ fills a role in Europe similar to the role of CISA in the US.', clozeAnswer: 'ENISA',
      ru: 'Европейский аналог CISA.' },
    { id: '2.2-g4', lesson: '2.2.7', kind: 'term', group: 'orgs', groupLabel: 'Организации и кампании', weight: 2,
      term: 'NCSA', definition: 'The National Cyber Security Alliance, which together with CISA promotes cybersecurity to all users and runs the annual National Cybersecurity Awareness Month.',
      aliases: ['national cyber security alliance'], ru: 'Вместе с CISA продвигает кибербезопасность.' },
    { id: '2.2-g5', lesson: '2.2.7', kind: 'fact', group: 'orgs', groupLabel: 'Организации и кампании', weight: 2,
      term: 'National Cybersecurity Awareness Month', definition: 'An annual campaign held every October by CISA and NCSA; the 2019 theme was "Own IT. Secure IT. Protect IT." with the hashtag #BeCyberSmart.',
      cloze: 'National Cybersecurity Awareness Month is held every ___ .', clozeAnswer: 'October',
      decoys: ['January', 'June', 'December'], ru: 'Каждый октябрь, тема 2019 Own IT. Secure IT. Protect IT.' },

    /* вопросы */
    { id: '2.2-q1', lesson: '2.2.8', kind: 'quiz', group: '2.2', groupLabel: 'Вопросы раздела 2.2', weight: 3,
      term: 'Gray hat · Black hat · White hat', definition: 'What Color is my Hat?',
      quiz: { type: 'match', q: 'Click the appropriate response for each characteristic to indicate the type of hacker it describes.',
        pairs: [
          { item: 'I hacked into ATM machines without the manufacturer authorization and then contacted the manufacturer to share my findings', match: 'Gray hat' },
          { item: 'I installed a skimmer on an ATM, captured over 1000 accounts and transferred money to an offshore bank account', match: 'Black hat' },
          { item: 'My job is to identify weaknesses in the computer system in my company', match: 'White hat' },
          { item: 'I used malware to steal credit card information and sold it to the highest bidder', match: 'Black hat' },
          { item: 'I found a security vulnerability on a corporate network that I am authorized to access', match: 'White hat' },
          { item: 'I gained unauthorized access to a company network and left the message "Your security is flawed"', match: 'Gray hat' },
          { item: 'I am working with technology companies to fix a flaw with DNS', match: 'White hat' },
        ],
        pool: ['Gray hat', 'Black hat', 'White hat'],
        why: 'Есть авторизация или это работа это White hat. Нет авторизации, но нет корысти и ущерба это Gray hat. Нет авторизации плюс корысть или кража это Black hat.' } },
    { id: '2.2-q2', lesson: '2.2.1', kind: 'quiz', group: '2.2', groupLabel: 'Вопросы раздела 2.2', weight: 3,
      term: 'Risk reduction', definition: 'Самая частая стратегия митигации',
      quiz: { type: 'mcq', q: 'Which risk management strategy is the most commonly used one?',
        options: ['Risk reduction', 'Risk acceptance', 'Risk avoidance', 'Risk transfer'], answers: ['Risk reduction'],
        why: 'Risk reduction снижает подверженность риску или его влияние и требует оценки стоимости потерь, стратегии и выгод.' } },
    { id: '2.2-q3', lesson: '2.2.1', kind: 'quiz', group: '2.2', groupLabel: 'Вопросы раздела 2.2', weight: 3,
      term: 'Remote exploit', definition: 'Эксплойт без учётной записи',
      quiz: { type: 'mcq', q: 'Which type of exploit works over the network without any prior access to the target system and does not require an account on it?',
        options: ['Remote exploit', 'Local exploit', 'Physical exploit', 'Privilege escalation'], answers: ['Remote exploit'],
        why: 'Local exploit требует пользовательского или административного доступа, remote не требует.' } },
  ],
}
