import type { Island } from '@/types'

export const island_2_3: Island = {
  id: '2.3',
  moduleId: 2,
  title: 'Securing Networks Summary',
  titleRu: 'Итоги модуля 2 и квиз',
  objective: 'Recap module 2 and pass the Securing Networks quiz.',
  icon: 'Network',
  lessons: [
    {
      id: '2.3.1', title: 'What Did I Learn in this Module?', titleRu: 'Что я узнал в этом модуле', kind: 'accordion',
      blocks: [
        {
          t: 'accordion', title: 'Два итоговых блока',
          items: [
            { title: 'Current State of Affairs', md: 'Network security напрямую связан с **business continuity** организации. Взломы могут нарушить e-commerce, вызвать потерю бизнес-данных, поставить под угрозу приватность людей и нарушить целостность информации. Итог для организации: потеря выручки, кража интеллектуальной собственности, судебные иски, угроза общественной безопасности.\n\nДоступно много инструментов для митигации угроз, в том числе **Cisco Talos Intelligence Group**.\n\n**Attack vector** — путь, по которому threat actor получает доступ к серверу, хосту или сети. Векторы исходят изнутри или снаружи корпоративной сети.\n\n**Data** — вероятно самый ценный актив организации. Нужно внедрять **DLP controls**, сочетающие **strategic, operational и tactical** меры. Частые векторы потери данных: **email and social networking, unencrypted data devices, cloud storage devices, removable media, hard copy, improper access control**.' },
            { title: 'Who is Attacking Our Network?', md: 'Понимание сетевой безопасности требует знания терминов: **threat, vulnerability, attack surface, exploit, risk**.\n\n**Risk management** — процесс, балансирующий операционные затраты на защиту с выгодой от защиты актива. Четыре способа: **risk acceptance, risk avoidance, risk reduction, risk transfer**.\n\n**White hat** — этичные хакеры с добрыми, этичными и законными целями. **Grey hat** — совершают преступления и неэтичные поступки, но **не ради личной выгоды и не ради ущерба**. **Black hat** — преступники, нарушающие безопасность ради личной выгоды или по злому умыслу.\n\nТипы threat actors: **script kiddies, vulnerability brokers, hacktivists, cybercriminals, state-sponsored hackers**.\n\nМногие атаки предотвращаются обменом информацией об **IOC**. Государства продвигают кибербезопасность: примеры организаций — **CISA** и **NCSA**.' },
          ],
        },
      ],
    },
    {
      id: '2.3.2', title: 'Securing Networks Quiz', titleRu: 'Квиз модуля 2', kind: 'activity',
      blocks: [
        { t: 'p', md: 'Параметры квиза: **20 вопросов**, режим «1 вопрос за раз», лимит **75 минут**, проходной балл **70%**, количество попыток не ограничено, рандомизация выключена, при повторной попытке жёсткий сброс.' },
        { t: 'h', text: 'Новые понятия, которых не было в 2.1 и 2.2' },
        { t: 'table', headers: ['Понятие', 'Определение'], rows: [
          ['**Hyperjacking**', 'Захват **гипервизора виртуальной машины**, после чего эта VM используется для атаки на остальные устройства дата-центра.'],
          ['**MDM**', '**Mobile Device Management**: secure, monitor и manage как корпоративных, так и личных устройств сотрудников — смартфонов, планшетов, ноутбуков и десктопов.'],
          ['**CAN**', '**Campus area network**. Отличительный признак: состоит из **interconnected LANs**.'],
          ['**WAN**', 'Охватывает большую территорию: главный офис плюс branch office, regional site, SOHO и mobile workers, обычно через публичное интернет-соединение. Типовые средства защиты: **firewall на каждой площадке** и **VPN для удалённых работников**.'],
          ['**Outside perimeter security**', '**Gate** и охрана периметра.'],
          ['**Inside perimeter security**', '**Security traps, biometrics access, exit sensors**.'],
          ['**Continuous video surveillance**', 'Единственная мера, которая встречается **и снаружи, и внутри** дата-центра. Классическая ловушка вопроса 1.'],
        ] },
        { t: 'table', caption: 'Ключи ко всем 20 вопросам', headers: ['№', 'Вопрос кратко', 'Правильный ответ'], rows: [
          ['1', 'Мера безопасности и внутри, и снаружи дата-центра', '**continuous video surveillance**'],
          ['2', 'Что такое hyperjacking', '**taking over a virtual machine hypervisor as part of a data center attack**'],
          ['3', 'Эволюция угроз сетевой безопасности', '**Internal threats can cause even greater damage than external threats**'],
          ['4', 'Самый ценный актив организации', '**data**'],
          ['5', 'Слабые настройки безопасности устройства компании в другом месте', '**cloud storage device**'],
          ['6', 'Изъян из видео anatomy of an attack', '**a flat network with no subnets or VLANs**'],
          ['7', 'Тип сети на exhibit', '**CAN**'],
          ['8', 'Две функции безопасности в дизайне WAN', '**VPNs used by mobile workers between sites + firewalls protecting the main and remote sites**'],
          ['9', 'Технология для teleworker', '**VPN**'],
          ['10', 'Secure, monitor, manage мобильных устройств', '**MDM**'],
          ['11', 'Группа Cisco, расследующая уязвимости продуктов Cisco', '**Cisco Product Security Incident Response Team (PSIRT)**'],
          ['12', 'Что такое attack vector', '**a path by which a threat actor can gain access to a server, host, or network**'],
          ['13', 'Сопоставить векторы потери данных с описанием', '**Email/Social Networking, Improper Access Control, Unencrypted Devices, Removable Media**'],
          ['14', 'Потенциальная опасность для актива', '**Threat**'],
          ['15', 'Что такое attack surface', '**total sum of the vulnerabilities in each system that are accessible to an attacker**'],
          ['16', 'Репликация в облако плюс страховка', '**Risk transfer**'],
          ['17', 'Сопоставить типы хакеров с описанием', '**Black hat, White hat, Gray hat**'],
          ['18', 'Самозанятые или в крупных киберпреступных организациях', '**Cybercriminals**'],
          ['19', 'Характеристики IOA', '**focus on the motivation behind an attack and the potential means of compromise**'],
          ['20', 'Две причины, почему внутренние угрозы опаснее', '**direct access to the building and infrastructure devices + knowledge of the corporate network, resources and confidential data**'],
        ] },
      ],
    },
    {
      id: '2.3.S', title: 'Summary table', titleRu: 'Итоговая таблица модуля 2', kind: 'summary',
      blocks: [
        { t: 'table', headers: ['Понятие', 'Определение или ключевое отличие', 'Где встречается'], rows: [
          ['Threat', 'Потенциальная опасность для актива', '2.3.1, В14'],
          ['Vulnerability', 'Слабость системы или её дизайна', '2.3.1, В14, В15'],
          ['Exploit', 'Механизм, использующий уязвимость для компрометации актива', '2.3.1, В14, В15'],
          ['Risk', 'Вероятность, что угроза реализует уязвимость с нежелательным исходом', '2.3.1, В14, В15'],
          ['Attack surface', 'Сумма уязвимостей всех систем, доступных атакующему', '2.3.1, В15'],
          ['Attack vector', 'Путь доступа к серверу, хосту или сети, изнутри или снаружи', '2.3.1, В12'],
          ['Risk acceptance', 'Стоимость защиты выше стоимости риска, ничего не делают', '2.3.1, В16'],
          ['Risk avoidance', 'Устраняют активность или устройство, теряя и выгоды', '2.3.1, В16'],
          ['Risk reduction', 'Снижают экспозицию или влияние риска', '2.3.1, В16'],
          ['Risk transfer', 'Передают риск третьей стороне: cloud provider, страховая', '2.3.1, В16'],
          ['White hat', 'Этичный хакер, легальные цели, пентесты', '2.3.1, В17'],
          ['Grey hat', 'Преступления и неэтичные вещи, но не ради выгоды и не ради ущерба', '2.3.1, В17'],
          ['Black hat', 'Преступник ради личной выгоды или из злого умысла', '2.3.1, В17'],
          ['Script kiddies', 'Тип threat actor из списка курса', '2.3.1'],
          ['Vulnerability brokers', 'Обычно grey hat, ищут эксплойты и сообщают вендорам', '2.3.1, В18'],
          ['Hacktivists', 'Grey hat, политический и социальный протест, утечки, DDoS', '2.3.1, В18'],
          ['Cybercriminals', 'Black hat, самозанятые или в крупных киберпреступных организациях', '2.3.1, В18'],
          ['State-Sponsored', 'Кража гостайн, разведка, саботаж сетей', '2.3.1, В18'],
          ['IOA', 'Мотивация и стратегии атакующих, проактивная защита', 'В19'],
          ['IOC', 'Файлы малвари, IP, имена файлов, изменения ПО, что уже произошло', '2.3.1, В19'],
          ['AIS', 'Система CISA для бесплатного автоматического обмена индикаторами', 'В19'],
          ['CISA', 'US Cybersecurity Infrastructure and Security Agency', '2.3.1, В11, В19'],
          ['NCSA', 'National Cyber Security Alliance', '2.3.1, В11'],
          ['Cisco PSIRT', 'Расследует и устраняет уязвимости в продуктах Cisco', 'В11'],
          ['Cisco Talos', 'Threat intelligence, помощь в mitigation techniques', '2.3.1, В11'],
          ['Data loss vectors', 'Email/social networking, unencrypted devices, cloud storage, removable media, hard copy, improper access control', '2.3.1, В5, В13'],
          ['DLP controls', 'Сочетание strategic, operational и tactical мер', '2.3.1'],
          ['Hyperjacking', 'Захват гипервизора VM и атака на остальные устройства ЦОД', 'В2'],
          ['MDM', 'Secure, monitor, manage мобильных устройств, корпоративных и личных', 'В10'],
          ['VPN', 'Связь между площадками и для mobile и remote работников', 'В8, В9'],
          ['CAN', 'Сеть из interconnected LANs', 'В7'],
          ['WAN', 'Главный офис плюс удалённые площадки через публичный интернет, firewall и VPN', 'В8'],
          ['Outside perimeter security', 'Gate, continuous video surveillance', 'В1'],
          ['Inside perimeter security', 'Security traps, biometrics access, exit sensors, continuous video surveillance', 'В1'],
          ['Flat network', 'Сеть без подсетей и VLAN, позволила атаку через термостат', 'В6'],
        ] },
      ],
    },
  ],
  atoms: [
    /* новые термины */
    { id: '2.3-t1', lesson: '2.3.2', kind: 'term', group: 'dc-security', groupLabel: 'Дата-центр и типы сетей', weight: 3,
      term: 'Hyperjacking', definition: 'Occurs when an attacker hijacks a virtual machine (VM) hypervisor and then uses that VM to launch an attack on other data center devices.',
      cloze: '___ is taking over a virtual machine hypervisor as part of a data center attack.',
      ru: 'Захват гипервизора VM и атака на остальные устройства ЦОД.' },
    { id: '2.3-t2', lesson: '2.3.2', kind: 'fact', group: 'dc-security', groupLabel: 'Дата-центр и типы сетей', weight: 3,
      term: 'The security measure found both inside and outside a data center', definition: 'Continuous video surveillance. A gate provides outside perimeter security; security traps, biometrics access and exit sensors provide inside perimeter security.',
      cloze: 'The security measure found both inside and outside a data center facility is ___ .', clozeAnswer: 'continuous video surveillance',
      decoys: ['a gate', 'exit sensors', 'biometrics access'],
      ru: 'Непрерывное видеонаблюдение есть и снаружи, и внутри.' },
    { id: '2.3-t3', lesson: '2.3.2', kind: 'enum', group: 'dc-security', groupLabel: 'Дата-центр и типы сетей', weight: 2,
      term: 'Inside perimeter security measures', definition: 'Security traps, biometrics access and exit sensors, plus continuous video surveillance.',
      items: ['Security traps', 'Biometrics access', 'Exit sensors', 'Continuous video surveillance'],
      decoys: ['A gate', 'A firewall', 'A VPN concentrator'],
      ru: 'Внутренний периметр дата-центра.' },
    { id: '2.3-t4', lesson: '2.3.2', kind: 'term', group: 'dc-security', groupLabel: 'Дата-центр и типы сетей', weight: 3,
      term: 'MDM', definition: 'Mobile Device Management: used to secure, monitor and manage both corporate-owned and employee-owned devices such as smartphones, tablets, laptops and desktops.',
      aliases: ['mobile device management'],
      cloze: '___ is used to secure, monitor and manage corporate-owned and employee-owned mobile devices.', clozeAnswer: 'MDM',
      ru: 'Управление мобильными устройствами.' },
    { id: '2.3-t5', lesson: '2.3.2', kind: 'term', group: 'dc-security', groupLabel: 'Дата-центр и типы сетей', weight: 3,
      term: 'CAN', definition: 'A campus area network; the distinguishing factor of CANs is that they have interconnected LANs.',
      aliases: ['campus area network'],
      cloze: 'The distinguishing factor of a ___ is that it has interconnected LANs.', clozeAnswer: 'CAN',
      ru: 'Сеть из связанных между собой LAN.' },
    { id: '2.3-t6', lesson: '2.3.2', kind: 'enum', group: 'dc-security', groupLabel: 'Дата-центр и типы сетей', weight: 3,
      term: 'Two security features commonly found in a WAN design', definition: 'VPNs used by mobile workers between sites, and firewalls protecting the main and remote sites.',
      items: ['VPNs used by mobile workers between sites', 'Firewalls protecting the main and remote sites'],
      decoys: ['Port security on all user-facing ports', 'WPA2 for data encryption of all data between sites', 'Outside perimeter security including continuous video surveillance'],
      ru: 'VPN для удалённых работников и firewall на каждой площадке.' },
    { id: '2.3-t7', lesson: '2.3.2', kind: 'fact', group: 'dc-security', groupLabel: 'Дата-центр и типы сетей', weight: 3,
      term: 'What a teleworker uses to reach the corporate network', definition: 'A VPN. VPNs are commonly used between corporate sites and between mobile or remote workers that connect to and use resources on the corporate network.',
      cloze: 'A teleworker accessing resources on the main corporate office network commonly uses a ___ .', clozeAnswer: 'VPN',
      decoys: ['IPS', 'SecureX', 'biometric access'],
      ru: 'VPN.' },
    { id: '2.3-t8', lesson: '2.3.2', kind: 'enum', group: 'internal-threats', groupLabel: 'Внутренние угрозы', weight: 3,
      term: 'Two reasons internal threats may cause greater damage than external threats', definition: 'Internal users have direct access to the building and its infrastructure devices, and they may have knowledge of the corporate network, its resources and its confidential data.',
      items: ['Internal users have direct access to the building and its infrastructure devices', 'Internal users may have knowledge of the corporate network, its resources and its confidential data'],
      decoys: ['Internal users have better access to attacking tools', 'Internal users can easily conceal their attacking trails', 'State-sponsored hacking is typically carried out by internal users'],
      ru: 'Прямой физический доступ и знание сети и данных.' },

    /* 20 вопросов квиза */
    { id: '2.3-q1', lesson: '2.3.2', kind: 'quiz', group: '2.3', groupLabel: 'Квиз модуля 2', weight: 3,
      term: 'continuous video surveillance', definition: 'Вопрос 1',
      quiz: { type: 'mcq', q: 'Which security measure is typically found both inside and outside a data center facility?',
        options: ['a gate', 'exit sensors', 'security traps', 'biometrics access', 'continuous video surveillance'],
        answers: ['continuous video surveillance'],
        why: 'Gate это защита внешнего периметра. Security traps, biometrics access и exit sensors это внутренний периметр. Видеонаблюдение есть и там, и там.' } },
    { id: '2.3-q2', lesson: '2.3.2', kind: 'quiz', group: '2.3', groupLabel: 'Квиз модуля 2', weight: 3,
      term: 'taking over a virtual machine hypervisor', definition: 'Вопрос 2',
      quiz: { type: 'mcq', q: 'What is hyperjacking?',
        options: ['taking over a virtual machine hypervisor as part of a data center attack', 'overclocking the mesh network which connects the data center servers', 'adding outdated security software to a virtual machine to gain access to a data center server', 'using processors from multiple computers to increase data processing power'],
        answers: ['taking over a virtual machine hypervisor as part of a data center attack'],
        why: 'Атакующий захватывает гипервизор VM и затем использует эту VM для атаки на другие устройства дата-центра.' } },
    { id: '2.3-q3', lesson: '2.3.2', kind: 'quiz', group: '2.3', groupLabel: 'Квиз модуля 2', weight: 3,
      term: 'Internal threats can cause even greater damage', definition: 'Вопрос 3',
      quiz: { type: 'mcq', q: 'Which statement accurately characterizes the evolution of threats to network security?',
        options: ['Internal threats can cause even greater damage than external threats.', 'Internet architects planned for network security from the beginning.', 'Early Internet users often engaged in activities that would harm other users.', 'Threats have become less sophisticated while the technical knowledge needed by an attacker has grown.'],
        answers: ['Internal threats can cause even greater damage than external threats.'],
        why: 'Внутренние угрозы бывают умышленными и случайными и наносят больший ущерб, потому что у внутреннего пользователя прямой доступ к корпоративной сети и данным.' } },
    { id: '2.3-q4', lesson: '2.3.2', kind: 'quiz', group: '2.3', groupLabel: 'Квиз модуля 2', weight: 3,
      term: 'data', definition: 'Вопрос 4',
      quiz: { type: 'mcq', q: 'When considering network security, what is the most valuable asset of an organization?',
        options: ['customers', 'data', 'financial resources', 'personnel'], answers: ['data'],
        why: 'Research and development, sales, financial, HR, legal, employee, contractor и customer data вероятнее всего самый ценный актив организации.' } },
    { id: '2.3-q5', lesson: '2.3.2', kind: 'quiz', group: '2.3', groupLabel: 'Квиз модуля 2', weight: 3,
      term: 'cloud storage device', definition: 'Вопрос 5',
      quiz: { type: 'mcq', q: 'Which resource is affected due to weak security settings for a device owned by the company, but housed in another location?',
        options: ['cloud storage device', 'hard copy', 'removable media', 'social networking'], answers: ['cloud storage device'],
        why: 'Облачное хранение даёт много выгод, но данные там могут быть скомпрометированы из-за слабых настроек безопасности.' } },
    { id: '2.3-q6', lesson: '2.3.2', kind: 'quiz', group: '2.3', groupLabel: 'Квиз модуля 2', weight: 3,
      term: 'a flat network with no subnets or VLANs', definition: 'Вопрос 6',
      quiz: { type: 'mcq', q: 'In the video that describes the anatomy of an attack, a threat actor was able to gain access through a network device, download data, and destroy it. Which flaw allowed the threat actor to do this?',
        options: ['open ports on the firewall', 'lack of a strong password policy', 'a flat network with no subnets or VLANs', 'improper physical security to gain access to the building'],
        answers: ['a flat network with no subnets or VLANs'],
        why: 'У компании была плоская сеть без подсетей. Атакующий добрался до всех корпоративных данных через термостат, который был в сети, но не сканировался в рамках процедур безопасности.' } },
    { id: '2.3-q7', lesson: '2.3.2', kind: 'quiz', group: '2.3', groupLabel: 'Квиз модуля 2', weight: 3,
      term: 'CAN', definition: 'Вопрос 7',
      quiz: { type: 'mcq', q: 'An IT security manager is planning security updates on a network made of interconnected LANs. Which type of network is this?',
        options: ['CAN', 'WAN', 'SOHO', 'data center'], answers: ['CAN'],
        why: 'Отличительный признак campus area network это взаимосвязанные LAN.' } },
    { id: '2.3-q8', lesson: '2.3.2', kind: 'quiz', group: '2.3', groupLabel: 'Квиз модуля 2', weight: 3,
      term: 'VPNs + firewalls', definition: 'Вопрос 8',
      quiz: { type: 'multi', q: 'What are two security features commonly found in a WAN design? (Choose two.)',
        options: ['port security on all user-facing ports', 'VPNs used by mobile workers between sites', 'firewalls protecting the main and remote sites', 'WPA2 for data encryption of all data between sites', 'outside perimeter security including continuous video surveillance'],
        answers: ['VPNs used by mobile workers between sites', 'firewalls protecting the main and remote sites'],
        why: 'WAN покрывает большую территорию и обычно соединяет главный офис с удалёнными площадками через публичный интернет. На каждой площадке есть firewall, а удалённые работники используют VPN.' } },
    { id: '2.3-q9', lesson: '2.3.2', kind: 'quiz', group: '2.3', groupLabel: 'Квиз модуля 2', weight: 3,
      term: 'VPN', definition: 'Вопрос 9',
      quiz: { type: 'mcq', q: 'Which security technology is commonly used by a teleworker when accessing resources on the main corporate office network?',
        options: ['IPS', 'VPN', 'SecureX', 'biometric access'], answers: ['VPN'],
        why: 'VPN обычно используются между корпоративными площадками и для мобильных или удалённых работников.' } },
    { id: '2.3-q10', lesson: '2.3.2', kind: 'quiz', group: '2.3', groupLabel: 'Квиз модуля 2', weight: 3,
      term: 'MDM', definition: 'Вопрос 10',
      quiz: { type: 'mcq', q: 'Which technology is used to secure, monitor, and manage mobile devices?',
        options: ['MDM', 'VPN', 'rootkit', 'ASA firewall'], answers: ['MDM'],
        why: 'Mobile Device Management защищает, мониторит и управляет как корпоративными, так и личными устройствами: смартфонами, планшетами, ноутбуками и десктопами.' } },
    { id: '2.3-q11', lesson: '2.3.2', kind: 'quiz', group: '2.3', groupLabel: 'Квиз модуля 2', weight: 3,
      term: 'Cisco Product Security Incident Response Team', definition: 'Вопрос 11',
      quiz: { type: 'mcq', q: 'Which Cisco group is responsible for investigating and mitigating potential vulnerabilities in Cisco products?',
        options: ['Cisco Talos Intelligence Group', 'National Cyber Security Alliance', 'Cisco Product Security Incident Response Team', 'Cybersecurity Infrastructure and Security Agency'],
        answers: ['Cisco Product Security Incident Response Team'],
        why: 'PSIRT отвечает именно за уязвимости в продуктах Cisco. Talos даёт threat intelligence в целом, CISA и NCSA это государственные организации США.' } },
    { id: '2.3-q12', lesson: '2.3.2', kind: 'quiz', group: '2.3', groupLabel: 'Квиз модуля 2', weight: 3,
      term: 'a path by which a threat actor can gain access', definition: 'Вопрос 12',
      quiz: { type: 'mcq', q: 'What is an attack vector?',
        options: ['It refers to a threat group that launches DDoS attacks.', 'It refers to attacks carried out specifically by internal users.', 'It is a tool by which a threat actor uses to attack an organization.', 'It is a path by which a threat actor can gain access to a server, host, or network.'],
        answers: ['It is a path by which a threat actor can gain access to a server, host, or network.'],
        why: 'Attack vector это путь доступа. Векторы исходят изнутри или снаружи корпоративной сети.' } },
    { id: '2.3-q13', lesson: '2.3.2', kind: 'quiz', group: '2.3', groupLabel: 'Квиз модуля 2', weight: 3,
      term: 'Data loss vectors', definition: 'Вопрос 13',
      quiz: { type: 'match', q: 'Match the common data loss vectors to the description.',
        pairs: [
          { item: 'Intercepted email or IM messages could be captured and reveal confidential information', match: 'Email/Social Networking' },
          { item: 'Stolen or weak passwords which have been compromised provide an attacker easy access to corporate data', match: 'Improper Access Control' },
          { item: 'If the data is not stored using an encryption algorithm, a thief can retrieve it from a stolen corporate laptop', match: 'Unencrypted Devices' },
          { item: 'An employee could perform an unauthorized transfer of data to a USB drive, or a USB drive with corporate data could be lost', match: 'Removable Media' },
        ],
        pool: ['Email/Social Networking', 'Improper Access Control', 'Unencrypted Devices', 'Removable Media'],
        why: 'Шесть векторов потери данных из 2.1.5. Email и соцсети самый распространённый, пароли это первая линия обороны.' } },
    { id: '2.3-q14', lesson: '2.3.2', kind: 'quiz', group: '2.3', groupLabel: 'Квиз модуля 2', weight: 3,
      term: 'Threat', definition: 'Вопрос 14',
      quiz: { type: 'mcq', q: 'Which term in network security is used to describe a potential danger to an asset such as data or the network itself?',
        options: ['Risk', 'Threat', 'Exploit', 'Vulnerability'], answers: ['Threat'],
        why: 'Threat это потенциальная опасность. Vulnerability это слабость системы, exploit это механизм использования уязвимости, risk это вероятность реализации.' } },
    { id: '2.3-q15', lesson: '2.3.2', kind: 'quiz', group: '2.3', groupLabel: 'Квиз модуля 2', weight: 3,
      term: 'the total sum of the vulnerabilities accessible to an attacker', definition: 'Вопрос 15',
      quiz: { type: 'mcq', q: 'Which statement describes the network security term attack surface?',
        options: ['It is a weakness in a system or its design that could be exploited by a threat.', 'It is the mechanism that is used to leverage a vulnerability to compromise an asset.', 'It is the total sum of the vulnerabilities in each system that are accessible to an attacker.', 'It is the likelihood that a particular threat will exploit a particular vulnerability of an asset and result in an undesirable consequence.'],
        answers: ['It is the total sum of the vulnerabilities in each system that are accessible to an attacker.'],
        why: 'Первый вариант это vulnerability, второй exploit, четвёртый risk.' } },
    { id: '2.3-q16', lesson: '2.3.2', kind: 'quiz', group: '2.3', groupLabel: 'Квиз модуля 2', weight: 3,
      term: 'Risk transfer', definition: 'Вопрос 16',
      quiz: { type: 'mcq', q: 'Critical data will be replicated to a cloud service provider and further insured with an insurance company. Which risk management strategy is employed?',
        options: ['Risk transfer', 'Risk reduction', 'Risk avoidance', 'Risk acceptance'], answers: ['Risk transfer'],
        why: 'Часть или весь риск передаётся согласной третьей стороне, например облачному провайдеру или страховой компании.' } },
    { id: '2.3-q17', lesson: '2.3.2', kind: 'quiz', group: '2.3', groupLabel: 'Квиз модуля 2', weight: 3,
      term: 'Black hat · White hat · Gray hat', definition: 'Вопрос 17',
      quiz: { type: 'match', q: 'Match the type of hackers to the description.',
        pairs: [
          { item: 'Unethical criminals who violate computer and network security for personal gain or for malicious reasons', match: 'Black hat hackers' },
          { item: 'Ethical hackers who use their programming skills for good, ethical and legal purposes and may perform penetration tests', match: 'White hat hackers' },
          { item: 'Individuals who commit crimes and do arguably unethical things, but not for personal gain or to cause damage', match: 'Gray hat hackers' },
        ],
        pool: ['Black hat hackers', 'White hat hackers', 'Gray hat hackers'],
        why: 'Ключ в авторизации и мотиве: white это разрешение и польза, gray это без разрешения, но без корысти, black это без разрешения и ради выгоды или вреда.' } },
    { id: '2.3-q18', lesson: '2.3.2', kind: 'quiz', group: '2.3', groupLabel: 'Квиз модуля 2', weight: 3,
      term: 'Cybercriminals', definition: 'Вопрос 18',
      quiz: { type: 'mcq', q: 'Which term refers to the type of threat actors who are either self-employed or working for large cybercrime organizations?',
        options: ['Hacktivists', 'Cybercriminals', 'State-Sponsored', 'Vulnerability brokers'], answers: ['Cybercriminals'],
        why: 'Cybercriminals это black hat hackers, самозанятые или работающие на крупные киберпреступные организации, ежегодно крадущие миллиарды долларов.' } },
    { id: '2.3-q19', lesson: '2.3.2', kind: 'quiz', group: '2.3', groupLabel: 'Квиз модуля 2', weight: 3,
      term: 'IOA focus on the motivation behind an attack', definition: 'Вопрос 19',
      quiz: { type: 'mcq', q: 'Which statement describes the characteristics of the indicators of attack (IOA)?',
        options: ['They are shared through the system AIS and help to limit the size of attack surface.', 'They help cybersecurity personnel identify what has happened in an attack and develop defenses against the attack.', 'They focus on the motivation behind an attack and the potential means by which threat actors have, or will, compromise vulnerabilities to gain access to assets.', 'They focus on identifying malware files, IP addresses of servers used in attacks, filenames, and characteristic changes made to end system software.'],
        answers: ['They focus on the motivation behind an attack and the potential means by which threat actors have, or will, compromise vulnerabilities to gain access to assets.'],
        why: 'IOA про стратегии и мотивацию, то есть проактивный подход. Варианты 2 и 4 описывают IOC, вариант 1 описывает AIS.' } },
    { id: '2.3-q20', lesson: '2.3.2', kind: 'quiz', group: '2.3', groupLabel: 'Квиз модуля 2', weight: 3,
      term: 'Direct access + knowledge of the network', definition: 'Вопрос 20',
      quiz: { type: 'multi', q: 'What are two reasons that internal threats from within an organization may cause greater damage than external threats? (Choose two.)',
        options: ['Internal users have better access to attacking tools.', 'Internet users can easily conceal their attacking trails.', 'State-Sponsored hacking is typically carried out by internal users.', 'Internal users have direct access to the building and its infrastructure devices.', 'Internal users may have knowledge of the corporate network, its resources, and its confidential data.'],
        answers: ['Internal users have direct access to the building and its infrastructure devices.', 'Internal users may have knowledge of the corporate network, its resources, and its confidential data.'],
        why: 'Внутренние угрозы опаснее из-за прямого доступа к зданию и инфраструктурным устройствам и знания корпоративной сети, её ресурсов и конфиденциальных данных.' } },
  ],
}
